---
title: "PC CRH Engagament: Engagement Metrics"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
set.seed(1234)
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
library(cowplot)
library(stargazer)
library(starpolishr)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
```

```{r reading-in}
starting_df = dbGetQuery(oabi_con,
                         "select *
                         from [OABI_myVAAccess].[pccrh_eng].Z_analytic_df") %>%
  filter(always_missing_gap == F & always_missing_pf == F) %>%
  mutate(vssc_month = ymd(vssc_month),
         gap_cat = factor(case_when(
           gap_metric < 1.0 ~ "< 1.0",
           gap_metric >= 1.0 & gap_metric <= 1.2 ~ "1.0 - 1.2",
           gap_metric > 1.2 ~ "> 1.2",
           TRUE ~ NA
         )),
         pf_cat = factor(case_when(
           panel_fullness > 1.0 ~ "> 100%",
           panel_fullness >= 0.8 & panel_fullness <= 1.0 ~ "80% - 100%",
           panel_fullness < 0.8 ~ "< 80%",
           TRUE ~ NA
         )),
         joint_def = fct_drop(factor(
           case_when(panel_fullness > 1.0 | gap_metric < 1.0 ~ 
                       "PF > 100% OR Gap < 1.0",
                     panel_fullness < 0.8 | gap_metric > 1.2 ~
                       "PF < 80% OR Gap > 1.2",
                     (panel_fullness >= 0.8 & panel_fullness <= 1.0) | 
                       (gap_metric <= 1.2 & gap_metric >= 1.0) ~
                       "PF 80%-100% OR Gap 1.0-1.2",
                     TRUE ~ NA)
         )),
         period_initiating_crh = relevel(factor(period_initiating_crh,
                                                ordered = FALSE,
                                                levels = c("Before March 2020", 
                                                           "March to September 2020",
                                                           "After September 2020")),
                                         ref = "Before March 2020"))
#===========
pf_avg = starting_df %>%
  group_by(sta5a) %>%
  summarise(pf_mean = mean(panel_fullness, na.rm = T),
            pf_cat_mean = factor(case_when(
              pf_mean > 1.0 ~ "> 100%",
              pf_mean >= 0.8 & pf_mean <= 1.0 ~ "80% - 100%",
              pf_mean < 0.8 ~ "< 80%",
              TRUE ~ "Missing"
            ))) %>%
  select(sta5a, pf_cat_mean)
#===========
gap_avg = starting_df %>%
  group_by(sta5a) %>%
  summarise(mean_gap = mean(gap_metric, na.rm = T)) %>%
  mutate(gap_cat_mean = factor(case_when(
    mean_gap < 1.0 ~ "< 1.0",
    mean_gap >= 1.0 & mean_gap <= 1.2 ~ "1.0 - 1.2",
    mean_gap > 1.2 ~ "> 1.2",
    TRUE ~ "Missing all Gap Obs."
  )),
  gap_cat_mean = fct_drop(gap_cat_mean)) %>%
  select(sta5a, gap_cat_mean)
#===========
joint_def_avg = starting_df %>%
  group_by(sta5a) %>%
  summarise(mean_gap = mean(gap_metric, na.rm = T),
            pf_mean = mean(panel_fullness, na.rm = T)) %>%
  mutate(joint_def_mean = fct_drop(factor(
    case_when(pf_mean > 1.0 | mean_gap < 1.0 ~ 
                "PF > 100% OR Gap < 1.0",
              pf_mean < 0.8 | mean_gap > 1.2 ~
                "PF < 80% OR Gap > 1.2",
              (pf_mean >= 0.8 & pf_mean <= 1.0) | 
                (mean_gap <= 1.2 & mean_gap >= 1.0) ~
                "PF 80%-100% OR Gap 1.0-1.2",
              TRUE ~ "Missing")
  ))) %>%
  select(sta5a, joint_def_mean)
#============
pen_rate = dbGetQuery(oabi_con,
                      "select a.* 
                      from [OABI_MyVAAccess].[crh_eval].[B1_crh_penRate] as a
                      left join [OABI_MyVAAccess].pccrh_eng.G_crh_flag as b
                      	on a.sta5a = b.sta5a
                      where crh_encounter_count > 9
                      	and a.crh_month >= b.first_mo_w_mt9_pc_crh") %>%
  mutate(this_month_crh = 1,
         vssc_month = ymd(crh_month)) %>%
  select(sta5a, vssc_month, this_month_crh)
#============
```

```{r, class.source = "fold-show"}
tot_crh_fte_visn = starting_df %>%
  group_by(vssc_month, visn) %>%
  summarise(tot_crh_fte = sum(pcp_fte_crh, na.rm = T))
#
tot_crh_fte_nat = starting_df %>%
  group_by(vssc_month) %>%
  summarise(tot_crh_fte = sum(pcp_fte_crh, na.rm = T))
#------------
analytic_df = starting_df %>%
  left_join(., gap_avg) %>%
  left_join(., pf_avg) %>%
  left_join(., joint_def_avg) %>%
  left_join(., pen_rate) %>%
  left_join(., tot_crh_fte_visn) %>%
  mutate(pc_cc_refs_per_1k_tot_pc = replace_na(pc_cc_refs_per_1k_tot_pc, 0),
         joint_def_mean = relevel(joint_def_mean, ref = "PF < 80% OR Gap > 1.2"),
         pf_cat_mean = relevel(pf_cat_mean, ref = "< 80%"),
         gap_cat_mean = relevel(gap_cat_mean, ref = "> 1.2"),
         joint_def = relevel(joint_def, ref = "PF < 80% OR Gap > 1.2"),
         pf_cat = relevel(pf_cat, ref = "< 80%"),
         gap_cat = relevel(gap_cat, ref = "> 1.2"),
         tc_pc_success_pct = tc_pc_success_prop * 100,
         crh_flag = relevel(factor(crh_flag), ref = "0"),
         scrssn_count_cat = relevel(factor(scrssn_count_cat, ordered = FALSE), ref = "450-2,399"),
         male_pct = prop_male * 100,
         #visn = relevel(factor(visn), ref = "06"),
         cHosp_90d_gt90_pct = cHosp_90d_gt90_prop * 100,
         this_month_crh = replace_na(this_month_crh, 0),
         this_month_crh = relevel(factor(this_month_crh), ref = "0"),
         period_initiating_crh = relevel(factor(
           if_else(is.na(period_initiating_crh), "Never Initiated CRH", period_initiating_crh)),
           ref = "Never Initiated CRH"),
         crh_fte_prop = pcp_fte_crh / tot_crh_fte,
         crh_fte_pct = crh_fte_prop * 100)
```

```{r}
vast = DBI::dbGetQuery(oabi_con,
                       "--
select distinct sta5a = stationno, parent_station = par_sta_no, visn = newvisn, city, st, stationname, s_abbr
from [PACT_CC].[Dim].VAST
where extractdate = '8-16-2022'
	AND s_abbr IN('HCC', 'VAMC', 'MSCBOC', 'PCCBOC', 'OOS')
	AND stationname NOT LIKE '%Mobile Clinic%'
	AND stationno IN(select distinct sta6aid from PACT_CC.Dim.VAST_Historic where snapshotDate = '2022-07-01')") %>%
  filter(sta5a %in% analytic_df$sta5a) %>%
  mutate(visn = str_pad(visn, width = 2, side = "left", pad = "0"))
```



# Proportion of CRH FTE Engaged   

```{r}
tot_crh_fte_visn %>%
  ggplot(data = .,
         aes(x = vssc_month, y = tot_crh_fte, group = visn, color = visn)) +
  geom_line() +
  facet_wrap(~visn) +
  theme(legend.position = "none", 
        axis.title.x = element_blank()) +
  labs(y = "Total PC CRH FTE",
       title = "Total PC CRH FTE") 
```


## Gap Metric   
```{r}
analytic_df %>% 
  filter(is.na(gap_cat) == F) %>%
  group_by(vssc_month, gap_cat) %>%
  mutate(gap_cat = factor(gap_cat,
                           ordered = TRUE,
                           levels = c("< 1.0", "1.0 - 1.2", "> 1.2"))) %>%
  summarise(crh_fte_in_group = sum(pcp_fte_crh, na.rm = T)) %>%
  left_join(., tot_crh_fte_nat) %>%
  mutate(value = crh_fte_in_group / tot_crh_fte) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = gap_cat, color = gap_cat)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Gap Category",
       color = "Gap Category",
       title = "National") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format(),
                     limits = c(0, 1))
```

```{r}
analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = factor(gap_cat, 
                          ordered = TRUE,
                          levels = c("< 1.0", "1.0 - 1.2", "> 1.2", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>% 
  filter(gap_cat != "Missing") %>%
  select(sta5a, gap_cat, vssc_month, visn, crh_fte_prop) %>%
  pivot_longer(-c(sta5a, gap_cat, visn, vssc_month)) %>%
  group_by(vssc_month, visn, gap_cat) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = gap_cat, color = gap_cat)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Gap Category",
       color = "Gap Category") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```

## Panel Fullness     

```{r}
analytic_df %>% 
  filter(is.na(pf_cat) == F) %>%
  group_by(vssc_month, pf_cat) %>%
  mutate(pf_cat = factor(pf_cat,
                           ordered = TRUE,
                           levels = c("> 100%", "80% - 100%", "< 80%", "Missing"))) %>%
  summarise(crh_fte_in_group = sum(pcp_fte_crh, na.rm = T)) %>%
  left_join(., tot_crh_fte_nat) %>%
  mutate(value = crh_fte_in_group / tot_crh_fte) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = pf_cat, color = pf_cat)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Panel Fullness Category",
       color = "Panel Fullness Category",
       title = "National") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format(),
                     limits = c(0, 1))
```

```{r}
analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = factor(pf_cat, 
                          ordered = TRUE,
                          levels =  c("> 100%", "80% - 100%", "< 80%", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>% 
  filter(pf_cat != "Missing") %>%
  select(sta5a, pf_cat, vssc_month, visn, crh_fte_prop) %>%
  pivot_longer(-c(sta5a, pf_cat, visn, vssc_month)) %>%
  group_by(vssc_month, visn, pf_cat) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = pf_cat, color = pf_cat)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Panel Fullness Category",
       color = "Panel Fullness") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```


## Joint Definition   

```{r}
analytic_df %>% 
  filter(is.na(joint_def) == F) %>%
  group_by(vssc_month, joint_def) %>%
  mutate(joint_def = factor(joint_def,
                           ordered = TRUE,
                           levels = c("PF > 100% OR Gap < 1.0", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF < 80% OR Gap > 1.2", "Missing"))) %>%
  summarise(crh_fte_in_group = sum(pcp_fte_crh, na.rm = T)) %>%
  left_join(., tot_crh_fte_nat) %>%
  mutate(value = crh_fte_in_group / tot_crh_fte) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = joint_def, color = joint_def)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Joint Definition Category",
       color = "Joint Definition Category",
       title = "National") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format(),
                     limits = c(0, 1))
```

```{r}
analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = factor(joint_def, 
                          ordered = TRUE,
                          levels = c("PF > 100% OR Gap < 1.0", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF < 80% OR Gap > 1.2", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>% 
  filter(joint_def != "Missing") %>%
  select(sta5a, joint_def, vssc_month, visn, crh_fte_prop) %>%
  pivot_longer(-c(sta5a, joint_def, visn, vssc_month)) %>%
  group_by(vssc_month, visn, joint_def) %>%
  summarise(value = sum(value, na.rm = T)) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = value, group = joint_def, color = joint_def)) +
  geom_line(linewidth = 1) +
  ggsci::scale_color_d3() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Joint Definition Category",
       color = "Joint Definition") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```

## Worst Category  

```{r}
gap_df = analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = case_when(gap_cat == "> 1.2" ~ "Gap > 1.2", 
                             gap_cat == "1.0 - 1.2" ~ "Gap 1.0 - 1.2", 
                             gap_cat == "< 1.0" ~ "Gap < 1.0", 
                             TRUE ~"Missing"),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  group_by(gap_cat, visn, vssc_month) %>%
  summarise(crh_fte_prop = sum(crh_fte_prop, na.rm = TRUE))
#--
pf_df = analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = case_when(pf_cat == "< 80%" ~ "PF < 80%", 
                            pf_cat == "80% - 100%" ~ "PF 80% - 100%", 
                            pf_cat == "> 100%" ~ "PF > 100%", 
                            TRUE ~ "Missing"),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  group_by(pf_cat, visn, vssc_month) %>%
  summarise(crh_fte_prop = sum(crh_fte_prop, na.rm = TRUE))
#--
joint_df = analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = as.character(factor(joint_def, 
                          ordered = FALSE,
                          levels = c("PF < 80% OR Gap > 1.2", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF > 100% OR Gap < 1.0", "Missing"))),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  group_by(joint_def, visn, vssc_month) %>%
  summarise(crh_fte_prop = sum(crh_fte_prop, na.rm = TRUE))
#
gap_df %>%
  rename(name = gap_cat) %>%
  bind_rows(., pf_df %>%
              rename(name = pf_cat)) %>%
  bind_rows(., joint_df %>%
              rename(name = joint_def)) %>% 
  filter(name %in% c("Gap < 1.0", "PF > 100%", "PF > 100% OR Gap < 1.0")) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = crh_fte_prop, group = name, color = name)) +
  geom_line(linewidth = 1) +
    ggsci::scale_color_jama() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Category",
       color = "Engagement Metric") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```

## Middle Category  

```{r}
gap_df %>%
  rename(name = gap_cat) %>%
  bind_rows(., pf_df %>%
              rename(name = pf_cat)) %>%
  bind_rows(., joint_df %>%
              rename(name = joint_def)) %>% 
  filter(name %in% c("Gap 1.0 - 1.2", "PF 80% - 100%", "PF 80%-100% OR Gap 1.0-1.2")) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = crh_fte_prop, group = name, color = name)) +
  geom_line(linewidth = 1) +
    ggsci::scale_color_jama() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Category",
       color = "Engagement Metric") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```

## Top Category  

```{r}
gap_df %>%
  rename(name = gap_cat) %>%
  bind_rows(., pf_df %>%
              rename(name = pf_cat)) %>%
  bind_rows(., joint_df %>%
              rename(name = joint_def)) %>% 
  filter(name %in% c("Gap > 1.2", "PF < 80%", "PF < 80% OR Gap > 1.2")) %>%
  ggplot(data = .,
         aes(x = vssc_month, y = crh_fte_prop, group = name, color = name)) +
  geom_line(linewidth = 1) +
    ggsci::scale_color_jama() +
  facet_wrap(~visn) +
  labs(y = "Proportion of PC CRH FTE at Sta5as in Category",
       color = "Engagement Metric") +
  theme(axis.title.x = element_blank()) +
  scale_y_continuous(labels = percent_format())
```

```{r}

```


# Engagement Metrics  

## Gap Metric   
### Time-Invariant CRH Flag    

```{r}
analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = factor(gap_cat, 
                          ordered = TRUE,
                          levels = c("> 1.2", "1.0 - 1.2", "< 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(gap_cat, crh_flag) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#
gap_year_x_crh_flag = analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = factor(gap_cat, 
                          ordered = TRUE,
                          levels = c("> 1.2", "1.0 - 1.2", "< 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(gap_cat, crh_flag, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
gap_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
gap_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
gap_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
gap_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```

### Time-Varying CRH Flag    


```{r}
analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = factor(gap_cat, 
                          ordered = TRUE,
                          levels = c("> 1.2", "1.0 - 1.2", "< 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(gap_cat, this_month_crh) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#--
gap_year_x_crh_flag = analytic_df %>% 
  mutate(gap_cat = if_else(is.na(gap_cat), "Missing", gap_cat),
         gap_cat = factor(gap_cat, 
                          ordered = TRUE,
                          levels = c("> 1.2", "1.0 - 1.2", "< 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(gap_cat, this_month_crh, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
gap_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
gap_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
gap_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
gap_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Gap Category", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```

## Panel Fullness   
### Time-Invariant CRH Flag    

```{r}
analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = factor(pf_cat, 
                          ordered = TRUE,
                          levels = c("< 80%", "80% - 100%", "> 100%", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(pf_cat, crh_flag) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#
pf_year_x_crh_flag = analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = factor(pf_cat, 
                          ordered = TRUE,
                          levels = c("< 80%", "80% - 100%", "> 100%", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(pf_cat, crh_flag, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
pf_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
pf_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
pf_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
pf_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```

### Time-Varying CRH Flag    


```{r}
analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = factor(pf_cat, 
                          ordered = TRUE,
                          levels = c("< 80%", "80% - 100%", "> 100%", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(pf_cat, this_month_crh) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#--
pf_year_x_crh_flag = analytic_df %>% 
  mutate(pf_cat = if_else(is.na(pf_cat), "Missing", pf_cat),
         pf_cat = factor(pf_cat, 
                          ordered = TRUE,
                          levels = c("< 80%", "80% - 100%", "> 100%", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(pf_cat, this_month_crh, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
pf_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
pf_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
pf_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
pf_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Panel Fullness", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```

## Joint Definition   
### Time-Invariant CRH Flag    

```{r}
analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = factor(joint_def, 
                          ordered = TRUE,
                          levels = c("PF < 80% OR Gap > 1.2", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF > 100% OR Gap < 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(joint_def, crh_flag) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#
joint_def_year_x_crh_flag = analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = factor(joint_def, 
                          ordered = TRUE,
                          levels = c("PF < 80% OR Gap > 1.2", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF > 100% OR Gap < 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(joint_def, crh_flag, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
joint_def_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
joint_def_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
joint_def_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
joint_def_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```

### Time-Varying CRH Flag    


```{r}
analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = factor(joint_def, 
                          ordered = TRUE,
                          levels = c("PF < 80% OR Gap > 1.2", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF > 100% OR Gap < 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(joint_def, this_month_crh) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE)
#--
joint_def_year_x_crh_flag = analytic_df %>% 
  mutate(joint_def = if_else(is.na(joint_def), "Missing", joint_def),
         joint_def = factor(joint_def, 
                          ordered = TRUE,
                          levels = c("PF < 80% OR Gap > 1.2", "PF 80%-100% OR Gap 1.0-1.2", 
                                     "PF > 100% OR Gap < 1.0", "Missing")),
         fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month))) %>%
  tabyl(joint_def, this_month_crh, fy) %>%
  adorn_totals("both") %>%
  adorn_percentages("all") %>%
  adorn_pct_formatting() %>%
  adorn_ns("front")
#
joint_def_year_x_crh_flag$`2021` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2021" = 3))
#
joint_def_year_x_crh_flag$`2022` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2022" = 3))
#
joint_def_year_x_crh_flag$`2023` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2023" = 3))
#
joint_def_year_x_crh_flag$`2024` %>%
  kbl(col.names = c("Joint Definition", "Never CRH", "Yes CRH", "Total"),
      align = c("l", "r", "r", "r")) %>%
  kable_classic("striped", 
                full_width = F) %>%
  row_spec(0, bold = TRUE) %>%
  row_spec(5, bold = TRUE) %>%
  add_header_above(c(" ", "FY 2024" = 3))
```