---
title: "CRH Encounters per 1,000 Total Encounters"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = FALSE, fig.width = 14, fig.height = 14)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = '-')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 15),
             strip.text = element_text(size = 15),
             legend.text = element_text(size = 14),
             legend.title = element_text(size = 16),
             plot.caption = element_text(size = 12))
#
#--
source(here("Input", "Functions", "customFacetWrap.R"))
source(here("Input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
spokes <- dbGetQuery(oabi_con,
                     "select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy20_working
                     UNION
                     select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy21_working")
#
spokes_v <- spokes %>% pull
#
vast <- read_csv(here("Input", "Data","VAST_from_A06_11jan21.csv"))
#
vast_spokes <- vast %>%
  inner_join(., spokes, by = c("sta5a" = "spoke_sta5a"))
#==
all_months <- seq.Date(ymd('2019-10-01'),ymd('2021-09-01'), by = 'month')
#--
all_encounters <- dbGetQuery(oabi_con,
                             "select * from [OABI_MyVAAccess].[crh_eval].encounter_counts") %>%
  select(-contains("Vax")) %>%
  mutate(vizMonth = ymd(vizMonth)) %>%
  left_join(., vast, by = c("sta6a" = "sta5a")) %>%
  mutate(sta5a_lab = paste0("(", sta6a, ") ", short_name),
         spoke_flag = if_else(sta6a %in% spokes_v, TRUE, FALSE),
         fy = if_else(month(vizMonth) > 9, year(vizMonth) + 1, year(vizMonth)),
         qtr = case_when(month(vizMonth) %in% c(10, 11, 12) ~ 1,
                         month(vizMonth) %in% c(1, 2, 3) ~ 2,
                         month(vizMonth) %in% c(4, 5, 6) ~ 3,
                         month(vizMonth) %in% c(7, 8, 9) ~ 4)) %>%
  filter(is.na(parent_visn) == F & fy %in% c(2020, 2021)) %>%
  rename("Primary Care" = pc_encounters,
         "Mental Health" = mh_encounters,
         "Pharmacy" = pharmacy_encounters,
         "PCMHI" = pcmhi_encounters)
#
spoke_encounters <- all_encounters %>% filter(spoke_flag == T)
#==
crh_encounters <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].crh_encounters_deDup") %>%
  rename_all(tolower) %>%
  filter(fy %in% c(2020, 2021) & care_type %ni% c("Specialty", "Missing")) %>%
  mutate(crh_month = ymd(crh_month))
```

```{r creating_data_frames}
#--TOTAL
crh_sta5a_total <- crh_encounters %>%
  group_by(crh_month, spoke_sta5a) %>%
  summarise(crh_encounters = n())
#
all_sta5a_total <- spoke_encounters %>%
  select(2:6, sta6a) %>%
  pivot_longer(-c(vizMonth, sta6a)) %>%
  group_by(vizMonth, sta6a) %>%
  summarise(total = sum(value, na.rm = T))
#
total_sta5a_df_1 <- crh_sta5a_total %>%
  left_join(., all_sta5a_total, by = c("crh_month" = "vizMonth", "spoke_sta5a" = "sta6a")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000) %>%
  filter(is.na(spoke_sta5a) == F) %>%
  ungroup %>%
  complete(crh_month = all_months, nesting(spoke_sta5a))
#
avg_tot_crh_sta5a <- total_sta5a_df_1 %>%
  filter(is.na(crh_encounters) == F) %>%
  group_by(spoke_sta5a) %>%
  summarise(number_of_crh_months = n(),
            avg_crh_per_month = mean(crh_encounters, na.rm = T),
            avg_crh_per_1k = mean(crh_per_1k_total, na.rm = T),
            avg_tot = mean(total, na.rm = T),
            sum_tot = sum(total)) %>%
  left_join(., vast, by = c("spoke_sta5a" = "sta5a"))
#--
total_sta5a_df <- total_sta5a_df_1 %>% left_join(., avg_tot_crh_sta5a) %>%
  mutate(sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name))
#==BY CARE TYPE
crh_sta5a_type <- crh_encounters %>%
  group_by(crh_month, spoke_sta5a, care_type) %>%
  summarise(crh_encounters = n())
#
all_sta5a_type <- spoke_encounters %>%
  select(2:6, sta6a) %>%
  pivot_longer(-c(vizMonth, sta6a)) %>%
  group_by(vizMonth, sta6a, name) %>%
  summarise(total = sum(value, na.rm = T))
#
type_sta5a_df_1 <- crh_sta5a_type %>%
  left_join(., all_sta5a_type, by = c("crh_month" = "vizMonth", "care_type" = "name", "spoke_sta5a" = "sta6a")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000) %>%
  filter(is.na(spoke_sta5a) == F) %>%
  ungroup %>%
  complete(crh_month = all_months, nesting(spoke_sta5a, care_type))
#
avg_type_sta5a <- type_sta5a_df_1 %>%
  group_by(spoke_sta5a, care_type) %>%
  summarise(number_of_crh_months = n(),
            avg_crh_per_month = mean(crh_encounters),
            avg_crh_per_1k = mean(crh_per_1k_total),
            sum_tot = sum(total)) %>%
  left_join(., vast, by = c("spoke_sta5a" = "sta5a"))
#==
type_sta5a_df <- type_sta5a_df_1 %>% left_join(., avg_type_sta5a) %>%
  mutate(sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name))
```

# Overall
## Distribution of CRH Usage - I      
```{r}
crh_months <- ggplot(data = avg_tot_crh_sta5a,
       aes(x = number_of_crh_months)) +
  geom_histogram(bins = 24, fill = "royalblue", color = "black") +
  scale_x_continuous(breaks = seq(0, 24, 2)) +
  labs(x = "Months with > 0 CRH Encounters",
       y = "Count of Sta5as")
#
avg_crh_tot <- ggplot(data = subset(avg_tot_crh_sta5a, avg_crh_per_month < 1000),
                      aes(x = avg_crh_per_month)) +
  geom_histogram(fill = "red", color = "black") +
  labs(caption = "*Removed 2 observations > 1,000",
       x = "Average CRH Encounters per Month",
       y = "Count of Sta5as")
#
avg_crh_1k <- ggplot(data = subset(avg_tot_crh_sta5a, avg_crh_per_1k < 1000),
                     aes(x = avg_crh_per_1k)) +
  geom_histogram(fill = "forestgreen", color = "black") +
  labs(caption = "*Removed 8 observations > 1,000",
       x = "Average CRH Encounters/1,000 per Month",
       y = "Count of Sta5as")
#
avg_tot <- ggplot(data = avg_tot_crh_sta5a,
                     aes(x = avg_tot)) +
  geom_histogram(fill = "goldenrod", color = "black") +
  labs(x = "Average Total Encounters Month",
       y = "Count of Sta5as") +
  scale_x_continuous(labels = scales::comma_format())
#--
multiplot(crh_months, avg_crh_tot, cols = 2)
```

\newpage
## Distribution of CRH Usage - II  
```{r}
multiplot(avg_crh_1k, avg_tot, cols = 2)
```

\newpage

# VISN 20  
## Distribution of CRH Usage 
### I        
```{r}
crh_months <- ggplot(data = subset(avg_tot_crh_sta5a, parent_visn == 20),
       aes(x = number_of_crh_months)) +
  geom_histogram(bins = 24, fill = "royalblue", color = "black") +
  scale_x_continuous(breaks = seq(0, 24, 2)) +
  labs(x = "Months with > 0 CRH Encounters",
       y = "Count of Sta5as")
#
avg_crh_tot <- ggplot(data = subset(avg_tot_crh_sta5a, parent_visn == 20 & avg_crh_per_month < 1000),
                      aes(x = avg_crh_per_month)) +
  geom_histogram(fill = "red", color = "black") +
  labs(caption = "*Removed 1 observations > 1,000",
       x = "Average CRH Encounters per Month",
       y = "Count of Sta5as")
#
avg_crh_1k <- ggplot(data = subset(avg_tot_crh_sta5a, parent_visn == 20),
                     aes(x = avg_crh_per_1k)) +
  geom_histogram(fill = "forestgreen", color = "black") +
  labs(x = "Average CRH Encounters/1,000 per Month",
       y = "Count of Sta5as")
#
avg_tot <- ggplot(data = subset(avg_tot_crh_sta5a, parent_visn == 20),
                     aes(x = avg_tot)) +
  geom_histogram(fill = "goldenrod", color = "black") +
  labs(x = "Average Total Encounters Month",
       y = "Count of Sta5as") +
  scale_x_continuous(labels = scales::comma_format())
#--
multiplot(crh_months, avg_crh_tot, cols = 2)
```

\newpage
### II  
```{r}
multiplot(avg_crh_1k, avg_crh_tot, cols = 2)
```

\newpage

## CRH Encounters per 1,000 Total Encounters  
### I  
```{r}
#
outliers <- c("668", "668GA", "668GB", "668QB", "668QD")
#
visn_sta5as_1k <- avg_tot_crh_sta5a %>%
  filter(parent_visn == 20 & spoke_sta5a %ni% outliers) %>% 
  arrange(desc(avg_crh_per_1k)) %>% 
  select(spoke_sta5a) %>% pull
#
encounters_1 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_sta5as_1k[1:9]) %>%
  select(crh_month, sta5a_lab, crh_per_1k_total) %>%
  ggplot(data = .,
         aes(x = crh_month, y = crh_per_1k_total, group = sta5a_lab)) +
  geom_line(size = 1, color = "darkorchid4") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "CRH Encounters per 1,000 Total Encounters")
#
encounters_2 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_sta5as_1k[10:18]) %>%
  select(crh_month, sta5a_lab, crh_per_1k_total) %>%
  ggplot(data = .,
         aes(x = crh_month, y = crh_per_1k_total, group = sta5a_lab)) +
  geom_line(size = 1, color = "darkorchid4") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "CRH Encounters per 1,000 Total Encounters")
#==
multiplot(encounters_1, encounters_2, cols = 2)
```

\newpage

### II  
```{r}
encounters_3 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_sta5as_1k[19:27]) %>%
  select(crh_month, sta5a_lab, crh_per_1k_total) %>%
  ggplot(data = .,
         aes(x = crh_month, y = crh_per_1k_total, group = sta5a_lab)) +
  geom_line(size = 1, color = "darkorchid4") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "CRH Encounters per 1,000 Total Encounters")
#
encounters_4 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_sta5as_1k[28:nrow(table(visn_sta5as_1k))]) %>%
  select(crh_month, sta5a_lab, crh_per_1k_total) %>%
  ggplot(data = .,
         aes(x = crh_month, y = crh_per_1k_total, group = sta5a_lab)) +
  geom_line(size = 1, color = "darkorchid4") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "CRH Encounters per 1,000 Total Encounters")
#==
multiplot(encounters_3, encounters_4, cols = 2)
```

\newpage

### III  
```{r}
total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% outliers) %>%
  select(crh_month, sta5a_lab, crh_per_1k_total) %>%
  ggplot(data = .,
         aes(x = crh_month, y = crh_per_1k_total, group = sta5a_lab)) +
  geom_line(size = 1, color = "darkorchid4") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "CRH Encounters per 1,000 Total Encounters")
```


## By Care Type  
### Primary Care I  
```{r}
visn_pc_sta5as <- avg_type_sta5a %>%
  filter(parent_visn == 20 & care_type == "Primary Care") %>%
  arrange(desc(sum_tot)) %>% 
  select(spoke_sta5a) %>% pull
#
visn_mh_sta5as <- avg_type_sta5a %>%
  filter(parent_visn == 20 & care_type == "Mental Health") %>%
  arrange(desc(sum_tot)) %>% 
  select(spoke_sta5a) %>% pull
#
visn_ph_sta5as <- avg_type_sta5a %>%
  filter(parent_visn == 20 & care_type == "Pharmacy") %>%
  arrange(desc(sum_tot)) %>% 
  select(spoke_sta5a) %>% pull
#
visn_pcmhi_sta5as <- avg_type_sta5a %>%
  filter(parent_visn == 20 & care_type == "PCMHI") %>%
  arrange(desc(sum_tot)) %>% 
  select(spoke_sta5a) %>% pull
#
encounters_1 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_pc_sta5as[1:13]) %>%
  select(crh_month, sta5a_lab, crh_encounters, total) %>%
  pivot_longer(-c(crh_month, sta5a_lab)) %>%
  mutate(name_lab = if_else(name == "total", "Total", "CRH")) %>%
  ggplot(data = .,
         aes(x = crh_month, y = value, group = name_lab, color = name_lab)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "Encounters")
#
encounters_2 <- total_sta5a_df %>%
  filter(parent_visn == 20 & spoke_sta5a %in% visn_sta5as[14:26]) %>%
  select(crh_month, sta5a_lab, crh_encounters, total) %>%
  pivot_longer(-c(crh_month, sta5a_lab)) %>%
  mutate(name_lab = if_else(name == "total", "Total", "CRH")) %>%
  ggplot(data = .,
         aes(x = crh_month, y = value, group = name_lab, color = name_lab)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(~sta5a_lab) +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3, hjust = 0),
        axis.title.x = element_blank()) +
  labs(y = "Encounters")
#==
multiplot(encounters_1, encounters_2, cols = 2)
```