---
title: "CRH Encounters - VISN 23"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = FALSE, fig.width = 14, fig.height = 14)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = '-')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 15),
             strip.text = element_text(size = 15),
             legend.text = element_text(size = 14),
             legend.title = element_text(size = 16),
             plot.caption = element_text(size = 12))
#
source(here("Input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
institution_lookup <- dbGetQuery(oabi_con,
                                 "select distinct a.InstitutionName, b.Sta6a
                                  from [CDWWork].[Dim].Institution as a
                                  left join [CDWWork].[Dim].Division as b
                                  	on a.InstitutionSID = b.InstitutionSID
                                  where b.Sta6a IS NOT NULL and a.InstitutionName <> '*Missing*'") %>%
  rename_all(tolower)
#--
vast <- read_csv(here("Input", "Data","VAST_from_A06_11jan21.csv"))
#==
spokes <- dbGetQuery(oabi_con,
                     "select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy20_working
                     UNION
                     select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy21_working") %>%
  left_join(., vast, by = c("spoke_sta5a" = "sta5a"))
#===========
hubs <- dbGetQuery(oabi_con,
                   "select distinct hub_sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY20]
                    UNION 
                    select distinct Hub_Sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY21_working]") %>%
  pull
#--
v23_dina_check <- read_xlsx("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Data/CRH_PCAT_Check.xlsx") %>%
  rename_all(tolower) %>%
  left_join(., institution_lookup) %>%
  mutate(psc = as.numeric(str_sub(stopcodename, start = 2, end = 4)),
         ssc = if_else(creditstopname == "NULL", NA_real_, as.numeric(str_sub(creditstopname, start = 2, end = 4))),
         care_type = 
           case_when(
             (psc %in% c(156, 176, 177, 178, 301, 322, 323, 338, 348) 
              & (ssc != 160 | is.na(ssc) == T)) 
             | (psc != 160 
                & ssc %in% c(156, 176, 177, 178, 301, 322, 323, 338, 348))    ~ "Primary Care",
             (psc %in% c(502, 509, 510, 513, 516, 527, 538, 545, 550, 562, 576, 579, 586, 587) 
              & (ssc %ni% c(160, 534) | is.na(ssc) == T)) 
             | (psc %ni% c(160, 534)
                & ssc %in% c(502, 509, 510, 513, 516, 527, 538, 545, 550, 
                                    562, 576, 579, 586, 587))                  ~ "Mental Health",
             (psc %in% c(534, 539) 
              & (ssc != 160 | is.na(ssc) == T)) 
             | (psc != 160 & ssc %in% c(534, 539)) ~ "PCMHI",
             psc == 160 | ssc == 160  ~ "Pharmacy",
             is.na(psc) == T ~ "Missing",
             TRUE                                                                          ~ "Specialty"),
         visitdate = as_date(visitdatetime),
         hub_flag = if_else(sta6a %in% hubs, 2, 1),
         visit_month = ymd(str_c(year(visitdate), month(visitdate), "01", sep = "-")),
         fy = if_else(month(visitdate) > 9, year(visitdate) + 1, year(visitdate)),
         qtr = case_when(month(visitdate) %in% c(10, 11, 12) ~ 1,
                         month(visitdate) %in% c(1, 2, 3) ~ 2,
                         month(visitdate) %in% c(4, 5, 6) ~ 3,
                         month(visitdate) %in% c(7, 8, 9) ~ 4)) %>%
  arrange(`pat id`, visitdatetime, hub_flag) %>%
  group_by(`pat id`, visitdatetime, care_type) %>%
  mutate(rowNum = row_number()) %>%
  ungroup
#--
bjarni_crh <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].crh_encounters_deDup
                         where fy in(2020, 2021)") %>%
  rename_all(tolower)
#--
chelle_crh <- dbGetQuery(oabi_con,
                         "select a.*, b.most_freq_spoke_sta5a
                          from PACT_CC.CRH.crh_full_utilization_CLEAN_update as a
                          left join [OABI_MyVAAccess].[crh_eval].freq_crh_scrssn_sta5a as b
                          	on a.ScrSSN = b.ScrSSN") %>%
  rename_all(tolower) %>%
  mutate(visitdate = ymd(visitdateformat),
         crh_month = ymd(str_c(year(visitdate), month(visitdate), "01", sep = "-")),
         fy = if_else(month(visitdate) > 9, year(visitdate) + 1, year(visitdate)),
         qtr = case_when(month(visitdate) %in% c(10, 11, 12) ~ 1,
                         month(visitdate) %in% c(1, 2, 3) ~ 2,
                         month(visitdate) %in% c(4, 5, 6) ~ 3,
                         month(visitdate) %in% c(7, 8, 9) ~ 4)
         ,spoke_sta5a = most_freq_spoke_sta5a
         ) %>%
  filter(fy %in% c(2020, 2021) & care_type %ni% c("Missing")) %>%
  left_join(., vast, by = c("spoke_sta5a" = "sta5a"))
```

# VISN 23  
```{r}
bjarni_crh_visn23 <- bjarni_crh %>%
  filter(parent_visn == 23 & care_type != "Missing")
#
chelle_crh_visn23 <- chelle_crh %>%
  filter(parent_visn == 23 & care_type != "Missing")
#
dina_nat_wDupes <- v23_dina_check %>%
  filter(care_type != "Missing") %>%
  group_by(care_type, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "V23")
#
dina_nat_noDupes <- v23_dina_check %>%
  filter(rowNum == 1) %>%
  filter(care_type != "Missing") %>%
  group_by(care_type, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "V23")
#----
b_crh_visn23_summ_qtr <- bjarni_crh_visn23 %>%
  group_by(care_type, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "Bjarni")
#
c_crh_visn23_summ_qtr <- chelle_crh_visn23 %>%
  group_by(care_type, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "Chelle")
#---
wDupes <- b_crh_visn23_summ_qtr %>%
  bind_rows(., c_crh_visn23_summ_qtr) %>%
  bind_rows(., dina_nat_wDupes) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_")) %>%
  select(-c(fy, qtr)) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = care_type_source, color = source)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter",
       title = "With Duplicates") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~care_type)
#
noDupes <- b_crh_visn23_summ_qtr %>%
  bind_rows(., c_crh_visn23_summ_qtr) %>%
  bind_rows(., dina_nat_noDupes) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_")) %>%
  select(-c(fy, qtr)) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = care_type_source, color = source)) +
  geom_line(size = 1) +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter",
       title = "Without Duplicates") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~care_type)
#
multiplot(wDupes, noDupes, cols = 2)
```

### Mental Health: A subset of Sta5a's in VISN 23 (that are ever-spokes)  
```{r}
visn23_spokes <- spokes %>% filter(parent_visn == 23) %>% select(spoke_sta5a) %>% distinct %>% pull
#======
b_crh_visn23_summ_qtr_sta5a <- bjarni_crh_visn23 %>%
  group_by(care_type, spoke_sta5a, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "Bjarni") %>%
  filter(spoke_sta5a %in% visn23_spokes)
#
b_sta5a_w_MT_100_crh <- b_crh_visn23_summ_qtr_sta5a %>%
  group_by(spoke_sta5a, care_type) %>%
  summarise(tot_crh = sum(count, na.rm = T)) %>%
  filter(tot_crh > 100)
#
b_mh_sta5a <- b_sta5a_w_MT_100_crh %>% filter(care_type == "Mental Health") %>% select(spoke_sta5a) %>% pull
#--
c_crh_visn23_summ_qtr_sta5a <- chelle_crh_visn23 %>%
  group_by(care_type, spoke_sta5a, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "Chelle") %>%
  filter(spoke_sta5a %in% visn23_spokes)
#--
dina_crh_visn23_summ_qtr_sta5a <- v23_dina_check %>%
  filter(rowNum == 1) %>%
  rename(spoke_sta5a = sta6a) %>%
  group_by(care_type, spoke_sta5a, fy, qtr) %>%
  summarise(count = n()) %>%
  mutate(source = "V23")
#---
b_crh_visn23_summ_qtr_sta5a %>%
  bind_rows(., c_crh_visn23_summ_qtr_sta5a) %>%
  bind_rows(., dina_crh_visn23_summ_qtr_sta5a) %>%
  inner_join(., vast %>% select(spoke_sta5a = sta5a, short_name)) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_"),
         sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(-c(fy, qtr)) %>% ungroup %>%
  filter(care_type == "Mental Health" & str_detect(sta5a_lab, "Minneapolis|Omaha|Moines|Cloud") == F) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = source, color = source)) +
  geom_line(size = 1) +
  geom_jitter() +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~sta5a_lab)
#
b_crh_visn23_summ_qtr_sta5a %>%
  bind_rows(., c_crh_visn23_summ_qtr_sta5a) %>%
  bind_rows(., dina_crh_visn23_summ_qtr_sta5a) %>%
  inner_join(., vast %>% select(spoke_sta5a = sta5a, short_name)) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_"),
         sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(-c(fy, qtr)) %>% ungroup %>%
  filter(care_type == "Mental Health" & str_detect(sta5a_lab, "Minneapolis|Omaha|Moines|Cloud") == T) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = source, color = source)) +
  geom_line(size = 1) +
  geom_jitter() +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~sta5a_lab)
```

### Primary Care     
```{r}
b_crh_visn23_summ_qtr_sta5a %>%
  bind_rows(., c_crh_visn23_summ_qtr_sta5a) %>%
  bind_rows(., dina_crh_visn23_summ_qtr_sta5a) %>%
  left_join(., vast %>% select(spoke_sta5a = sta5a, short_name)) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_"),
         sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(-c(fy, qtr)) %>% ungroup %>%
  filter(care_type == "Primary Care" & str_detect(sta5a_lab, "Minneapolis|Omaha|Moines|Cloud") == F) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = source, color = source)) +
  geom_line(size = 1) +
  geom_jitter() +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~sta5a_lab)
#
b_crh_visn23_summ_qtr_sta5a %>%
  bind_rows(., c_crh_visn23_summ_qtr_sta5a) %>%
  bind_rows(., dina_crh_visn23_summ_qtr_sta5a) %>%
  left_join(., vast %>% select(spoke_sta5a = sta5a, short_name)) %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_"),
         care_type_source = str_c(care_type, source, sep = "_"),
         sta5a_lab = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(-c(fy, qtr)) %>% ungroup %>%
  filter(care_type == "Primary Care" & str_detect(sta5a_lab, "Minneapolis|Omaha|Moines|Cloud") == T) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = count, group = source, color = source)) +
  geom_line(size = 1) +
  geom_jitter() +
  scale_y_continuous(labels = scales::comma_format(),
                     limits = c(0, NA)) +
  labs(x = "FY_Qtr",
       y = "Encounters per Quarter") +
  guides(color = guide_legend(override.aes = list(size = 1.25))) +
  theme(axis.text.x = element_text(angle = 270,
                                   vjust = 0.3),
        legend.title = element_blank()) +
  facet_wrap(~sta5a_lab)
```