---
title: "CRH Encounters Over Time - National"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = FALSE, fig.width = 14, fig.height = 14)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = '-')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 18),
             strip.text = element_text(size = 20),
             legend.text = element_text(size = 18),
             legend.title = element_text(size = 20),
             plot.caption = element_text(size = 12))
#
#--
source(here("Input", "Functions", "customFacetWrap.R"))
source(here("Input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
spokes <- dbGetQuery(oabi_con,
                     "select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy20_working
                     UNION
                     select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy21_working")
#
spokes_v <- spokes %>% pull
#
vast <- read_csv(here("Input", "Data","VAST_from_A06_11jan21.csv"))
#
vast_spokes <- vast %>%
  inner_join(., spokes, by = c("sta5a" = "spoke_sta5a"))
#==
all_encounters <- dbGetQuery(oabi_con,
                             "select * from [OABI_MyVAAccess].[crh_eval].all_encounters_E_counts") %>%
  select(-contains("Vax")) %>%
  mutate(vizMonth = ymd(vizMonth)) %>%
  left_join(., vast, by = c("sta6a" = "sta5a")) %>%
  mutate(sta5a_lab = paste0("(", sta6a, ") ", short_name),
         spoke_flag = if_else(sta6a %in% spokes_v, TRUE, FALSE),
         fy = if_else(month(vizMonth) > 9, year(vizMonth) + 1, year(vizMonth)),
         qtr = case_when(month(vizMonth) %in% c(10, 11, 12) ~ 1,
                         month(vizMonth) %in% c(1, 2, 3) ~ 2,
                         month(vizMonth) %in% c(4, 5, 6) ~ 3,
                         month(vizMonth) %in% c(7, 8, 9) ~ 4),
         fyqtr = str_c("fy", str_sub(fy, start = -2), "qtr", qtr)) %>%
  filter(is.na(parent_visn) == F & fy %in% c(2020, 2021)) %>%
  rename("Primary Care" = pc_encounters,
         "Mental Health" = mh_encounters,
         "Pharmacy" = pharmacy_encounters,
         "PCMHI" = pcmhi_encounters)
#
spoke_encounters <- all_encounters %>% filter(spoke_flag == T)
#==
crh_encounters <- dbGetQuery(oabi_con,
                         "select * from [PACT_CC].[CRH].[crh_full_utilization_final_fy20_21]") %>%
  rename_all(tolower) %>%
  mutate(visitdate = ymd(visitdate),
         crh_month = ymd(str_c(year(visitdate), month(visitdate), "01", sep = "-")),
         fy = if_else(month(visitdate) > 9, year(visitdate) + 1, year(visitdate))) %>%
  filter(fy %in% c(2020, 2021) & care_type %ni% c("Specialty", "Missing"))
```


# Total    
```{r}
aaas_pal5 <- ggsci::pal_aaas("default")(5)
#--
crh_nat_total <- crh_encounters %>%
  group_by(qtr) %>%
  summarise(crh_encounters = n())
#
all_nat_total <- spoke_encounters %>%
  select(3:6, 23) %>%
  pivot_longer(-fyqtr) %>%
  group_by(fyqtr) %>%
  summarise(total = sum(value, na.rm = T))
#
total_df <- crh_nat_total %>%
  left_join(., all_nat_total, by = c("qtr" = "fyqtr")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000)
#
p1_tot <- ggplot(data = total_df,
         aes(x = qtr, y = crh_per_1k_total, color = "1", group = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[1]) +
  theme(legend.position = "none") +
  labs(x = "Quarter",
       y = "CRH/1,000 Total")

#
p2_tot <- ggplot(data = total_df,
         aes(x = qtr, y = crh_encounters, color = "1", group = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[2]) +
  theme(legend.position = "none") +
  labs(x = "Quarter",
       y = "CRH Encounters")
#
p3_tot <- ggplot(data = total_df,
         aes(x = qtr, y = total, color = "1", group = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, 8000000),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[3]) +
  theme(legend.position = "none") +
  labs(x = "Quarter",
       y = "Total Encounters")
#
multiplot(p1_tot, p2_tot, p3_tot, cols = 1)
```

---

## As a Table  

```{r}
total_df %>% 
  mutate(crh_per_1k_total = round(crh_per_1k_total, 1)) %>%
  rename("CRH Encounters" = crh_encounters,
         "Total" = total,
         "CRH/1,000 total" = crh_per_1k_total) %>%
  kbl(col.names = c("FY-Qtr", "CRH Encounters", "Total Encounters", "CRH/1,000 Total"),
      format.args = list(big.mark = ","),
      align = c("l", rep("r", 4))) %>%
  kable_classic(latex_options = c("striped", "hold_position"))
```

---

# By Type      
## Mental Health  
```{r}
crh_nat_type <- crh_encounters %>%
  group_by(qtr, care_type) %>%
  summarise(crh_encounters = n())
#
all_nat_type <- spoke_encounters %>%
  select(3:6, 23) %>%
  pivot_longer(-fyqtr) %>%
  group_by(fyqtr, name) %>%
  summarise(total = sum(value, na.rm = T))
#
type_nat_df <- crh_nat_type %>%
  left_join(., all_nat_type, by = c("qtr" = "fyqtr", "care_type" = "name")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000)
#
p1_mh <- ggplot(data = subset(type_nat_df, care_type == "Mental Health"),
         aes(x = qtr, y = crh_per_1k_total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, 30),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[1]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH MH/1,000 Total MH")
#
p2_mh <- ggplot(data = subset(type_nat_df, care_type == "Mental Health"),
         aes(x = qtr, y = crh_encounters, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[2]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH MH Encounters")
#
p3_mh <- ggplot(data = subset(type_nat_df, care_type == "Mental Health"),
         aes(x = qtr, y = total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[3]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "Total MH Encounters")
#--
multiplot(p1_mh, p2_mh, p3_mh)
```

---
      
## Primary Care    
```{r}
p1_pc <- ggplot(data = subset(type_nat_df, care_type == "Primary Care"),
         aes(x = qtr, y = crh_per_1k_total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, 30),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[1]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH PC/1,000 Total PC")
#
p2_pc <- ggplot(data = subset(type_nat_df, care_type == "Primary Care"),
         aes(x = qtr, y = crh_encounters, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[2]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH PC Encounters")
#
p3_pc <- ggplot(data = subset(type_nat_df, care_type == "Primary Care"),
         aes(x = qtr, y = total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[3]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "Total PC Encounters")
#--
multiplot(p1_pc, p2_pc, p3_pc)
```

---

## Pharmacy      
```{r}
p1_cps <- ggplot(data = subset(type_nat_df, care_type == "Pharmacy"),
         aes(x = qtr, y = crh_per_1k_total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, 30),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[1]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH CPS/1,000 Total CPS")
#
p2_cps <- ggplot(data = subset(type_nat_df, care_type == "Pharmacy"),
         aes(x = qtr, y = crh_encounters, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[2]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH CPS Encounters")
#
p3_cps <- ggplot(data = subset(type_nat_df, care_type == "Pharmacy"),
         aes(x = qtr, y = total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[3]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "Total CPS Encounters")
#--
multiplot(p1_cps, p2_cps, p3_cps)
```

---

## PCMHI      
```{r}
p1_pcmhi <- ggplot(data = subset(type_nat_df, care_type == "PCMHI"),
         aes(x = qtr, y = crh_per_1k_total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[1]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH PCMHI/1,000 Total PCMHI")
#
p2_pcmhi <- ggplot(data = subset(type_nat_df, care_type == "PCMHI"),
         aes(x = qtr, y = crh_encounters, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[2]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "CRH PCMHI Encounters")
#
p3_pcmhi <- ggplot(data = subset(type_nat_df, care_type == "PCMHI"),
         aes(x = qtr, y = total, group = "1", color = "1")) +
  geom_line(size = 1) +
  scale_y_continuous(limits = c(0, NA),
                     labels = scales::comma_format(accuracy = 1)) +
  scale_color_manual(values = aaas_pal5[3]) +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3)) +
  labs(x = "Quarter",
       y = "Total PCMHI Encounters")
#--
multiplot(p1_pcmhi, p2_pcmhi, p3_pcmhi)
```

---

## As a Table  
### Mental Health and Primary Care  
```{r}
type_nat_df %>%
  mutate(crh_per_1k_total = round(crh_per_1k_total, 1)) %>%
  pivot_longer(-c(qtr, care_type)) %>%
  pivot_wider(names_from = c(care_type, name), values_from = value) %>%
  select(qtr, contains("Mental"), contains("Primary")) %>%
  kbl(col.names = c("Quarter",
                    rep(c("CRH", "Total", "CRH/1,000"), 2)),
      align = c("l", rep("r", 6)),
      format.args = list(big.mark = ",")) %>%
  column_spec(c(4), border_right = T) %>%
  kable_classic(latex_options = c("striped", "hold_position")) %>%
  add_header_above(c(" " = 1, "Mental Health" = 3, "Primary Care" = 3))
#=====
```


---

### Pharmacy and PCMHI  

```{r}

type_nat_df %>%
  mutate(crh_per_1k_total = round(crh_per_1k_total, 1)) %>%
  pivot_longer(-c(qtr, care_type)) %>%
  pivot_wider(names_from = c(care_type, name), values_from = value) %>%
  select(qtr, contains("Pharm"), contains("PCMHI")) %>%
  kbl(col.names = c("Quarter",
                    rep(c("CRH", "Total", "CRH/1,000"), 2)),
      align = c("l", rep("r", 6)),
      format.args = list(big.mark = ",")) %>%
  column_spec(c(4), border_right = T) %>%
  kable_classic(latex_options = c("striped", "hold_position")) %>%
  add_header_above(c(" " = 1, "Pharmacy" = 3, "PCMHI" = 3))
```