---
title: "Primary Care CRH: Matching"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 12, fig.height = 12)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(weights)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
```

```{r reading-in}
#--Penetration Rate
penetration_rate <- dbGetQuery(oabi_con,
                               "select *
                               from [crh_eval].B1_crh_penRate") %>%
  mutate(crh_month = ymd(crh_month))
#--
access_metrics <- dbGetQuery(oabi_con,
                             "select * 
                             from [crh_eval].E2_VSSC_access_metrics")
#
crh_flag <- dbGetQuery(oabi_con,
                       "select *
                         from [crh_eval].C1_crh_flag")
```


```{r}
sta5a_demog <- dbGetQuery(oabi_con,
                          "select distinct c2.sta5a
                          , c2.state
	, crh_flag = case 
		when c1.crh_10_flag = 1 then 1
		else 0 end
	, c2.s_abbr, c2.parent_visn
	, d1.avg_age_oct1_2020
	, d2.*
	, d3.adi_natRnk_avg
from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06 as c2
left join [OABI_MyVAAccess].[crh_eval].C1_crh_flag as c1
	on c2.sta5a = c1.sta5a
left join [OABI_MyVAAccess].[crh_eval].D1_age_sta5a_qtr as d1
	on c2.sta5a = d1.Sta5a
left join [OABI_MyVAAccess].[crh_eval].D2_race_gender_urh_count as d2
	on c2.sta5a = d2.Sta5a
left join [OABI_MyVAAccess].[crh_eval].D3_adi_sta5a_qtr as d3
	on c2.sta5a = d3.Sta5a
where d1.fy = 2020 
	AND d1.QTR = 1
	AND d2.fy = 2020
	AND d2.QTR = 1
	AND d3.fy = 2020
	AND d3.qtr = 1") %>%
  mutate(prop_male = male_count / (scrssn_count),
         prop_rural = urh_rural_count / (scrssn_count),
         prop_white = race_white_count / scrssn_count,
         census_division = case_when(state %in% c("CT", "ME", "MA", "NH", "RI", "VT") ~ "New England",
                                   state %in% c("NJ", "NY", "PA") ~ "Middle Atlantic",
                                   state %in% c("IN", "IL", "MI", "OH", "WI") ~ "East North Central",
                                   state %in% c("IA", "KS", "MN", "MO", "NE", "ND", "SD") ~ "West North Central",
                                   state %in% c("DE", "DC", "FL", "GA", "MD", "NC", "SC", "VA", "WV") ~ "South Atlantic",
                                   state %in% c("AL", "KY", "MS", "TN") ~ "East South Central",
                                   state %in% c("AR", "LA", "OK", "TX") ~ "West South Central",
                                   state %in% c("AZ", "CO", "ID", "NM", "MT", "UT", "NV", "WY") ~ "Mountain",
                                   state %in% c("AK", "CA", "HI", "OR", "WA") ~ "Pacific"))
#
# sta5a_demog %>% 
#   tabyl(crh_flag, census_division) %>% 
#   adorn_totals(where = "both") %>%
#   kbl(col.names = c("CRH Flag", "EN Central", "ES Central", "Mid Atlantic", "Mountain", "New England", "Pacific", "South Atlantic",
#                     "WN Central", "WS Central", "Total")) %>%
#   kable_classic("striped") %>%
#   row_spec(0, bold = TRUE) %>%
#   row_spec(3, bold = TRUE) %>%
#   column_spec(11, bold = TRUE)
```

# Matching CRH to No CRH  
## Mean by CRH Flag  

```{r}
sta5a_demog %>%
  select(crh_flag, prop_male, prop_rural, adi_natRnk_avg, prop_white, scrssn_count) %>%
  group_by(crh_flag) %>%
  summarise_at(c("prop_male", "prop_rural", "adi_natRnk_avg", "prop_white"), ~ weighted.mean(., scrssn_count)) %>%
  left_join(., sta5a_demog %>% group_by(crh_flag) %>% summarise(scrssn_count = mean(scrssn_count, na.rm = T))) %>%
  mutate(prop_male = percent(prop_male, accuracy = 0.1),
         prop_rural = percent(prop_rural, accuracy = 0.1),
         prop_white = percent(prop_white, accuracy = 0.1),
         adi_natRnk_avg = round(adi_natRnk_avg, 1),
         scrssn_count = comma(scrssn_count, accuracy = 1)) %>%
  kbl(col.names = c("CRH Flag", "Male", "Rural", "ADI", "White", "In PCMM"),
      align = rep("r", 6)) %>%
  kable_classic("striped") %>%
  row_spec(0, bold = TRUE)
```

### Weighted t-test: Proportion Male  
```{r}
wtd.t.test(sta5a_demog %>% filter(crh_flag == 1) %>% select(prop_male) %>% pull,
           sta5a_demog %>% filter(crh_flag == 0) %>% select(prop_male) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 1) %>% select(scrssn_count) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 0) %>% select(scrssn_count) %>% pull)
```

### Weighted t-test: Proportion Rural  
```{r}
wtd.t.test(sta5a_demog %>% filter(crh_flag == 1) %>% select(prop_rural) %>% pull,
           sta5a_demog %>% filter(crh_flag == 0) %>% select(prop_rural) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 1) %>% select(scrssn_count) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 0) %>% select(scrssn_count) %>% pull)
```

### Weighted t-test: ADI  
```{r}
wtd.t.test(sta5a_demog %>% filter(crh_flag == 1) %>% select(adi_natRnk_avg) %>% pull,
           sta5a_demog %>% filter(crh_flag == 0) %>% select(adi_natRnk_avg) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 1) %>% select(scrssn_count) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 0) %>% select(scrssn_count) %>% pull)
```

### Weighted t-test: Proportion White    
```{r}
wtd.t.test(sta5a_demog %>% filter(crh_flag == 1) %>% select(prop_white) %>% pull,
           sta5a_demog %>% filter(crh_flag == 0) %>% select(prop_white) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 1) %>% select(scrssn_count) %>% pull, 
           sta5a_demog %>% filter(crh_flag == 0) %>% select(scrssn_count) %>% pull)
```

### T-test: Uniques in PCMM  
```{r}
t.test(scrssn_count ~ crh_flag,
       data = sta5a_demog)
```
