---
title: "PC CRH & Total PC Over Time - National & VISNs 19, 20, and 23"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, fig.width = 8, fig.height = 8)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 18),
             strip.text = element_text(size = 20),
             legend.text = element_text(size = 18),
             legend.title = element_text(size = 20),
             plot.caption = element_text(size = 12))
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r}
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].[C2_vast_from_a06]")
#
penRate <- dbGetQuery(oabi_con,
                      "select pr.*
                    	, crh_flag = case 
                    		when c1.crh_10_flag = 1 then 1
                    		else 0 end
                      from [OABI_MyVAAccess].[crh_eval].B1_crh_penRate as pr
                      left join [OABI_MyVAAccess].[crh_eval].C1_crh_flag as c1
	                    on pr.sta5a = c1.sta5a") %>%
  inner_join(., vast) %>%
  mutate(crh_month = ymd(crh_month),
         fy = if_else(month(crh_month) > 9, year(crh_month) + 1, year(crh_month)),
         qtr = case_when(
           month(crh_month) %in% c(10, 11, 12) ~ 1,
           month(crh_month) %in% c(1, 2, 3) ~ 2,
           month(crh_month) %in% c(4, 5, 6) ~ 3,
           month(crh_month) %in% c(7, 8, 9) ~ 4),
         fy_qtr = str_c(fy, qtr, sep = "-"),
         scrssn_count_cat = factor(scrssn_count_cat, ordered = TRUE,
                                   levels = c("< 450", "450 - 2,499", "2,500 - 9,999", "10,000+")))
```

# National  
* The results below include only those sta5as meeting our inclusion criteria of at least 2 consecutive months with 10 or more Primary Care CRH Encounters


```{r}
#======
p1 <- penRate %>%
  filter(crh_flag == 1) %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH Encounters" = sum(crh_encounter_count, na.rm = T),
            "Total PC Encounters" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  labs(y = "Count",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.position = "none")
#======
p2 <- penRate %>%
  filter(crh_flag == 1) %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(y = "Proportion",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
#
multiplot(p1, p2, cols = 2)
```

### By Uniques in PCMM  

```{r}
penRate %>%
  filter(crh_flag == 1 & is.na(scrssn_count_cat) == F) %>%
  group_by(fy_qtr, scrssn_count_cat) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  ungroup %>%
  pivot_longer(-c(fy_qtr, scrssn_count_cat)) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  facet_wrap(~scrssn_count_cat) +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  labs(y = "Count",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
```

```{r}
penRate %>%
  filter(crh_flag == 1 & is.na(scrssn_count_cat) == F) %>%
  group_by(fy_qtr, scrssn_count_cat) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  ungroup %>%
  pivot_longer(-c(fy_qtr, scrssn_count_cat)) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  facet_wrap(~scrssn_count_cat) +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(y = "Proportion",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
```


# VISN 19   

```{r}
#======
p1 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "19") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH Encounters" = sum(crh_encounter_count, na.rm = T),
            "Total PC Encounters" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_igv() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  labs(y = "Count",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.position = "none")
#======
p2 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "19") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_igv() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(y = "Proportion",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
#
multiplot(p1, p2, cols = 2)
```

# VISN 20  

```{r}
#======
p1 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "20") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH Encounters" = sum(crh_encounter_count, na.rm = T),
            "Total PC Encounters" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  labs(y = "Count",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.position = "none")
#======
p2 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "20") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(y = "Proportion",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
#
multiplot(p1, p2, cols = 2)
```


# VISN 23   

```{r}
#======
p1 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "23") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH Encounters" = sum(crh_encounter_count, na.rm = T),
            "Total PC Encounters" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_lancet() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  labs(y = "Count",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.position = "none")
#======
p2 <- penRate %>%
  filter(crh_flag == 1 & parent_visn == "23") %>%
  group_by(fy_qtr) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "Total PC" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-fy_qtr) %>%
  ggplot(data = .,
         aes(x = fy_qtr, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_lancet() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  labs(y = "Proportion",
       x = "FY-Qtr") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank())
#
multiplot(p1, p2, cols = 2)
```

