---
title: "VISN 23"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = FALSE, fig.width = 14, fig.height = 14)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 18),
             strip.text = element_text(size = 20),
             legend.text = element_text(size = 18),
             legend.title = element_text(size = 20),
             plot.caption = element_text(size = 12))
#
#--
source(here("Input", "Functions", "customFacetWrap.R"))
source(here("Input", "Functions", "multiplot_05jan21.R"))
```



```{r reading-in}
hubs <- dbGetQuery(oabi_con,
                   "select distinct hub_sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY20]
                    UNION 
                    select distinct Hub_Sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY21_working]") %>%
  pull
#--
spokes <- dbGetQuery(oabi_con,
                     "select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy20_working
                     UNION
                     select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy21_working")
#
spokes_v <- spokes %>% pull
#
vast <- read_csv(here("Input", "Data","VAST_from_A06_11jan21.csv"))
#
vast_spokes <- vast %>%
  inner_join(., spokes, by = c("sta5a" = "spoke_sta5a"))
#==
all_encounters <- dbGetQuery(oabi_con,
                             "select * from [OABI_MyVAAccess].[crh_eval].all_encounters_E_counts") %>%
  select(-contains("Vax")) %>%
  mutate(vizMonth = ymd(vizMonth)) %>%
  left_join(., vast, by = c("sta6a" = "sta5a")) %>%
  mutate(sta5a_lab = paste0("(", sta6a, ") ", short_name),
         spoke_flag = if_else(sta6a %in% spokes_v, TRUE, FALSE),
         fy = if_else(month(vizMonth) > 9, year(vizMonth) + 1, year(vizMonth)),
         qtr = case_when(month(vizMonth) %in% c(10, 11, 12) ~ 1,
                         month(vizMonth) %in% c(1, 2, 3) ~ 2,
                         month(vizMonth) %in% c(4, 5, 6) ~ 3,
                         month(vizMonth) %in% c(7, 8, 9) ~ 4),
         fyqtr = str_c(fy, "-", qtr)) %>%
  filter(is.na(parent_visn) == F & fy %in% c(2020, 2021)) %>%
  rename("Primary Care" = pc_encounters,
         "Mental Health" = mh_encounters,
         "Pharmacy" = pharmacy_encounters,
         "PCMHI" = pcmhi_encounters)
#
all_mnths <- all_encounters %>% select(vizMonth) %>% distinct
#
spoke_encounters <- all_encounters %>% filter(spoke_flag == T) %>%
  rename(sta5a = sta6a)
#-----
crh_encounters <- dbGetQuery(oabi_con,
                         "select * from [PACT_CC].[CRH].[crh_full_utilization_final_fy20_21]") %>%
  rename_all(tolower) %>%
  mutate(visitdate = ymd(visitdate),
         crh_month = ymd(str_c(year(visitdate), month(visitdate), "01", sep = "-")),
         fy = if_else(month(crh_month) > 9, year(crh_month) + 1, year(crh_month)),
         qtr = case_when(month(crh_month) %in% c(10, 11, 12) ~ 1,
                         month(crh_month) %in% c(1, 2, 3) ~ 2,
                         month(crh_month) %in% c(4, 5, 6) ~ 3,
                         month(crh_month) %in% c(7, 8, 9) ~ 4),
         fyqtr = str_c(fy, "-", qtr)) %>%
  filter(fy %in% c(2020, 2021) & care_type %in% c("Primary Care", "Pharmacy")) %>%
  left_join(., vast, by = c("spoke_sta5a_combined_cdw" = "sta5a")) %>%
  rename(sta5a = spoke_sta5a_combined_cdw)
#--==================
access_metrics_sta5a <- read_csv(here("Input", "Data", "pc_access_metrics_sta5a_qtr.csv")) %>%
  mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum) %>%
  select(-ends_with("avg"), -ends_with("sum"), -tc_success_prop) %>%
  left_join(., vast, by = c("sta6a" = "sta5a")) %>%
  rename(sta5a = sta6a) %>%
  mutate(sta5a_lab = paste0("(", sta5a, ") ", short_name),
         fy_qtr = str_replace(fy_qtr, "_", "-"))
#====================
pcmm_scrssn_count <- dbGetQuery(oabi_con,
                                "select count(distinct scrssn_num) as pcmm_scrssn_count
                                  	, Sta5a, fy
                                  from [PACT_CC].[econ].PatientPCP
                                  where fy in(2019, 2020, 2021)
                                  group by Sta5a, fy")
```

```{r creating_sta5a_data_frames}
#==BY CARE TYPE
crh_sta5a_type <- all_mnths %>% left_join(., crh_encounters, by = c("vizMonth" = "crh_month")) %>%
  group_by(vizMonth, sta5a, care_type) %>%
  summarise(crh_encounters = n()) %>%
  ungroup
#
all_sta5a_type <- all_mnths %>% left_join(., spoke_encounters) %>%
  select(3:6, sta5a, vizMonth) %>%
  pivot_longer(-c(vizMonth, sta5a)) %>%
  group_by(vizMonth, sta5a, name) %>%
  summarise(total = sum(value, na.rm = T)) %>%
  ungroup
#
type_avg <- crh_sta5a_type %>% 
  group_by(sta5a, care_type) %>%
  summarise(avg_crh_per_month = mean(crh_encounters, na.rm = T))
#
type_sta5a_df <- all_mnths %>% 
  full_join(., crh_sta5a_type) %>%
  full_join(., all_sta5a_type, by = c("vizMonth" = "vizMonth", "care_type" = "name", "sta5a" = "sta5a")) %>%
  mutate(fy = if_else(month(vizMonth) > 9, year(vizMonth) + 1, year(vizMonth))) %>%
  left_join(., pcmm_scrssn_count, by = c("fy" = "fy", "sta5a" = "Sta5a")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000,
         crh_per_1k_pcmm = crh_encounters / pcmm_scrssn_count * 1000) %>%
  ungroup %>%
  left_join(., vast %>% select(sta5a, parent_visn, short_name)) %>%
  mutate(sta5a_lab = paste0("(", sta5a, ") ", short_name)) %>%
  left_join(., type_avg) %>%
  filter(sta5a %in% spokes_v)
#-------
access_metrics_sta5a <- access_metrics_sta5a %>%
  inner_join(., type_avg %>% filter(care_type == "Primary Care")) %>%
  filter(sta5a %in% spokes_v)
```

```{r sta5a_functions}
crh_plot_fxn_1 <- function(visn_var, care_type_var, metric){
  if (metric == "total"){
    y_axis <- paste0("Total ", care_type_var, " Encounters")
  }
  else if (metric == "crh_encounters"){
    y_axis <- paste0(care_type_var, " CRH Encounters")
  }
  else if (metric == "crh_per_1k_total") {
    y_axis <- paste0(care_type_var, " CRH Encounters per 1,000 total ", care_type_var, " Encounters")
  }
  else if (metric == "crh_per_1k_pcmm") {
    y_axis <- paste0(care_type_var, " CRH Encounters per 1,000 in PCMM/FY")
  }
  type_sta5a_df %>%
    filter(parent_visn == visn_var & avg_crh_per_month > 100 & care_type == care_type_var) %>% 
    select(-care_type) %>%
    mutate(sta5a_lab = fct_reorder2(factor(sta5a_lab),
                                           vizMonth, crh_encounters)) %>%
    select(-c(sta5a, parent_visn, short_name)) %>%
    pivot_longer(-c(vizMonth, sta5a_lab)) %>%
    filter(name == metric) %>%
    ggplot(data = .,
           aes(y = value, x = vizMonth, group = sta5a_lab, color = sta5a_lab)) +
    geom_line(size = 1) +
    geom_point(size = 1) +
    scale_y_continuous(limits = c(0, NA),
                       labels = scales::comma_format(accuracy = 1)) +
    theme(axis.text.x = element_text(angle = 270, vjust = 0.3)) +
    labs(color = "Sta5a",
         x = "Month",
         y = y_axis,
         caption = "*Legend is ordered by the last datapoint") +
    guides(color = guide_legend(override.aes = list(size = 1.25)))
}
#-------
crh_plot_fxn_2 <- function(visn_var, care_type_var, metric){
  if (metric == "total"){
    y_axis <- paste0("Total ", care_type_var, " Encounters")
  }
  else if (metric == "crh_encounters"){
    y_axis <- paste0(care_type_var, " CRH Encounters")
  }
  else {
    y_axis <- paste0(care_type_var, " CRH Encounters per 1,000 ", care_type_var, " Encounters")
  }
  type_sta5a_df %>%
    filter(parent_visn == visn_var & avg_crh_per_month <= 100 & care_type == care_type_var) %>% 
    select(-care_type) %>%
    mutate(sta5a_lab = fct_reorder2(factor(sta5a_lab),
                                           vizMonth, crh_encounters)) %>%
    select(-c(sta5a, parent_visn, short_name)) %>%
    pivot_longer(-c(vizMonth, sta5a_lab)) %>%
    filter(name == metric) %>%
    ggplot(data = .,
           aes(y = value, x = vizMonth, group = sta5a_lab, color = sta5a_lab)) +
    geom_line(size = 1) +
    geom_point(size = 1) +
    scale_y_continuous(limits = c(0, NA),
                       labels = scales::comma_format(accuracy = 1)) +
    theme(axis.text.x = element_text(angle = 270, vjust = 0.3)) +
    labs(color = "Sta5a",
         x = "Month",
         y = y_axis,
         caption = "*Legend is ordered by the last datapoint") +
    guides(color = guide_legend(override.aes = list(size = 1.25)))
}
```

## Primary Care   
### PC CRH Encounters - I    
```{r}
crh_plot_fxn_1(visn_var = 23, "Primary Care", "crh_encounters")
```

### PC CRH Encounters - II    
```{r}
crh_plot_fxn_2(visn_var = 23, "Primary Care", "crh_encounters")
```

### Total PC Encounters - I    
```{r}
crh_plot_fxn_1(visn_var = 23, "Primary Care", "total")
```

### Total PC Encounters - II    
```{r}
crh_plot_fxn_2(visn_var = 23, "Primary Care", "crh_encounters")
```

### PC CRH Encounters per 1,000 Total PC Encounters - I    
```{r}
crh_plot_fxn_1(visn_var = 23, "Primary Care", "crh_per_1k_total")
```

### PC CRH Encounters per 1,000 Total PC Encounters - II    
```{r}
crh_plot_fxn_2(visn_var = 23, "Primary Care", "crh_per_1k_total")
```

### PC CRH Encounters per 1,000 in PCMM - I    
```{r}
crh_plot_fxn_1(visn_var = 23, "Primary Care", "crh_per_1k_pcmm")
```

### PC CRH Encounters per 1,000 in PCMM - II    
```{r}
crh_plot_fxn_2(visn_var = 23, "Primary Care", "crh_per_1k_pcmm")
```
