---
title: "Primary Care CRH: PC CRH + Non-CRH PC"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 12, fig.height = 12)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
##---------- Connection to PACT_CC
pactcc_con <- dbConnect(odbc::odbc(),
                        Driver = "SQL Server",
                        Server = "vhacdwsql13.vha.med.va.gov",
                        Database = "PACT_CC",
                        Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 18),
             strip.text = element_text(size = 20),
             legend.text = element_text(size = 18),
             legend.title = element_text(size = 20),
             plot.caption = element_text(size = 12))
#---
source(here("Input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#=========================
# VAST
vast <- read_csv(here("Input", "Data", "vast_from_a06.csv")) %>%
  filter(is.na(s_abbr) == F) %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count < 450 ~ "< 450",
    scrssn_count >= 450 & scrssn_count < 2500 ~ "450 - 2,499",
    scrssn_count >= 2500 & scrssn_count < 10000 ~ "2,500 - 9,999",
    scrssn_count >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,499", "2,500 - 9,999", "10,000+")))
#----
# crh flags
crh_flags <- dbGetQuery(oabi_con,
                        "select * from [crh_eval].yoon_flag")
#=============================
# CRH Penetration rate
pen_rate_month <- dbGetQuery(oabi_con,
                             "select * from [OABI_MyVAAccess].[crh_eval].crh_penRate_month") %>%
  inner_join(., vast) %>%
  left_join(., crh_flags) %>%
  mutate(crh_month = ymd(crh_month),
         table_1_columns = factor(case_when(yoon_10_flag == 1 ~ "CRH",
                                            crh_flag == 1 & yoon_10_flag == 0 ~ "Not Enough CRH",
                                            is.na(crh_flag) == T ~ "No CRH",
                                            TRUE ~ "Uh-oh"), 
                                  ordered = TRUE,
                                  levels = c("CRH", "Not Enough CRH", "No CRH")),
         analytic_period = factor(case_when(
           crh_month >= ymd("2019-04-01") & crh_month <= ymd("2019-09-01") ~ "6 Months Before",
           crh_month >= ymd("2019-10-01") & crh_month <= ymd("2020-03-01") ~ "First 6 Months of CRH",
           crh_month >= ymd("2020-04-01") & crh_month <= ymd("2020-09-01") ~ "6 Months After",
           TRUE ~ NA_character_),
           ordered = TRUE,
           levels = c("6 Months Before", "First 6 Months of CRH", "6 Months After"))) %>%
  filter(is.na(analytic_period) == F)
#=====
sta5as_w_6mos <- pen_rate_month %>%
  filter(first_6_mos_w_10_flag == 1) %>%
  select(sta5a) %>% distinct %>%
  left_join(., vast)
```

```{r}
sta5as_w_6mos %>%
  group_by(scrssn_count_cat) %>%
  summarise(count = n()) %>%
  mutate(prop = count / nrow(sta5as_w_6mos)) %>%
  adorn_totals() %>%
  mutate(prop = percent(prop, accuracy = 1)) %>%
  kbl(col.names = c("Uniques in PCMM", "Sta5a", "%"),
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = FALSE) %>%
  row_spec(0, bold = TRUE)
```

# All 42 Sta5as  
```{r}
p1 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a) %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#--==
p2 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a) %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Proportion of Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
  #
multiplot(p1, p2, cols = 2)
```

# Sta5as With 450 - 2,499 PCMM Uniques  
```{r}
p3 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "450 - 2,499") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_jco() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#
p4 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "450 - 2,499") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_jco() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Proportion of PC Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#
multiplot(p3, p4, cols = 2)
```

# Sta5as With 2,500 - 9,999 PCMM Uniques  
```{r}
p5 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "2,500 - 9,999") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#--
p6 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "2,500 - 9,999") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Proportion of PC Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#
multiplot(p5, p6, cols = 2)
```

# Sta5as With 10,000+ PCMM Uniques  
```{r}
p7 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "10,000+") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_nejm() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p8 <- pen_rate_month %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & scrssn_count_cat == "10,000+") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_nejm() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p7, p8, cols = 2)
```

# By Site Classification      
  
```{r}
sta5as_w_6mos %>%
  group_by(s_abbr) %>%
  summarise(count = n(),
            prop = count / nrow(sta5as_w_6mos)) %>%
  adorn_totals() %>%
  mutate(prop = percent(prop, accuracy = 1)) %>%
  kbl(col.names = c("Site Type", "Count", "%"),
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = FALSE) %>%
  row_spec(0, bold = TRUE)
```

## Sta5a Classified as PCCBOC  
```{r}
p9 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "PCCBOC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p10 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "PCCBOC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p9, p10, cols = 2)
```


## Sta5a Classified as MSCBOC  
```{r}
p9b <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "MSCBOC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p10b <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "MSCBOC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_d3() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p9b, p10b, cols = 2)
```

## Sta5as Classified as OOS       
  
```{r}
p11 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "OOS") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_npg() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p12 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "OOS") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_npg() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p11, p12, cols = 2)
```

## Sta5as Classified as VAMC        
  
```{r}
p13 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "VAMC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_ucscgb() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p14 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "VAMC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_ucscgb() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p13, p14, cols = 2)
```

## Sta5as Classified as HCC      
  
```{r}
p15 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "HCC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_uchicago() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
p16 <- pen_rate_month %>%
  left_join(., vast %>% select(sta5a, s_abbr)) %>% 
  filter(sta5a %in% sta5as_w_6mos$sta5a & s_abbr == "HCC") %>%
  select(sta5a, crh_month, crh_encounter_count, pc_encounter_noVax_total) %>%
  pivot_longer(-c(sta5a, crh_month)) %>%
  mutate(name_lab = factor(if_else(name == "crh_encounter_count", "PC CRH Encounters", "All PC Encounters"),
                           ordered = TRUE,
                           levels = c("PC CRH Encounters", "All PC Encounters"))) %>%
  ggplot(data = .,
         aes(fill = name_lab, y = value, x = crh_month)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_uchicago() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(date_breaks = "3 months") +
  labs(y = "Encounters",
       x = "Month") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3))
#==
multiplot(p15, p16, cols = 2)
```