---
title: "New Patient Wait Time: PID vs. Create Date"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             legend.position = "bottom")
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#vast file for s_abbr and others
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
#making PC CRH criteria for this analysis
crh_flag <- dbGetQuery(oabi_con,
                       "select * from [crh_eval].C1_crh_flag") %>%
  left_join(., vast %>% select(sta5a, s_abbr))
#propensity score matched sta5as if being used
ps_matched <- read_csv(here("Input","Data", "ps_matched_sta5as_v6_post_COVID.csv"))
#pulling timely care
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month)
#pulling vssc access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  left_join(timely_care)
#making a time column
dates <- access_metrics %>%
  filter(vssc_month > ymd("2020-02-01")) %>%
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#counting average # of unique scrssns in FY2021 by sta5a and making a categorical variable
  # that we use for exclusion
scrssn_count <- dbGetQuery(oabi_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PACT_CC].[econ].PatientPCP
                            	where fy = 2021
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy21, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy21 < 450 ~ "< 450",# exclusion criteria
    scrssn_count_avg_fy21 >= 450 & scrssn_count_avg_fy21 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy21 >= 2400 & scrssn_count_avg_fy21 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy21 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#---------------
covariates <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].Z_analytic_df") %>%
  rename(sta5a = Sta6a, vssc_month = visitMonth) %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  mutate(pct_male = male_count / scrssn_count * 100,
         pct_white = race_white_count / scrssn_count * 100,
         pct_rural = urh_rural_count / scrssn_count * 100) %>%
  select(pc_crh_per_1k_total_pc, #pcccr_per_10k_uniques,
         avg_age_oct1_2022, sta5a, vssc_month, 
         parent_visn, census_division,
         nosos_risk_score, obs_exp_panel_ratio, team_pcp_ap_fte_total,
         pcmm_count_fy_qtr,
         adi_natRnk_avg, pct_male, pct_white, pct_rural, avg_driveDist,
         shep_access_metric)
```

```{r}
# a vector of sta5as meeting our pc crh criteria
crh_sta5as <- ps_matched %>%
  filter(pc_crh_criteria_met_after_march_20 == 1) %>%
  select(sta5a) %>%
  pull
#this is where exclusion criteria are applied:
sta5as_to_include <- ps_matched %>%
  inner_join(., vast %>% select(sta5a, s_abbr)) %>%#2: must be in VAST
  distinct %>%
  mutate(crh_flag = if_else(sta5a %in% crh_sta5as, 
                            "PC CRH", "No PC CRH")) %>%#making the crh_flag
  left_join(., scrssn_count)
#=================
#making the analytic dataset
analytic_df <- access_metrics %>%# start with access metrics
      inner_join(., sta5as_to_include) %>%#restrict to our table from above
      filter(vssc_month > ymd("2020-06-01")) %>%#restrict to our timeframe
      left_join(., dates) %>%
  filter(scrssn_count_cat != "< 450")#3: must have scrssn_count_avg_fy21 >= 450
```



# New Patient Wait-Time  

```{r}
new_wt_pid <- read_csv(here("Input", "Data", "VSSC", "Appointments - Completed Summary", 
                            "appt_cube_new_pt_wt_from_indicated.csv")) %>%
  rename_all(tolower) %>%
  rename(date = 1,
         div_name = 2) %>%
  mutate(month_n = match(str_to_title(str_sub(date, end = 3)), month.abb),
         fy = as.numeric(str_sub(date, start = -2)),
         cy2 = if_else(month_n > 9, fy - 1, fy),
         cy = as.numeric(str_c("20", cy2)),
         vssc_month = ymd(str_c(cy, month_n, "01", sep = "-")),
         sta5a = if_else(str_sub(div_name, start = 11, end = 11) == ")",
                         str_sub(div_name, start = 8, end = 10),
                         str_sub(div_name, start = 8, end = 12))) %>%
  select(vssc_month, sta5a, new_pc_pt_wt_pid = 3)
#---
new_wt_created <- read_csv(here("Input", "Data", "VSSC", "Appointments - Completed Summary", 
                            "appt_cube_new_pt_wt_create_date.csv")) %>%
  rename_all(tolower) %>%
  rename(date = 1,
         div_name = 2) %>%
  mutate(month_n = match(str_to_title(str_sub(date, end = 3)), month.abb),
         fy = as.numeric(str_sub(date, start = -2)),
         cy2 = if_else(month_n > 9, fy - 1, fy),
         cy = as.numeric(str_c("20", cy2)),
         vssc_month = ymd(str_c(cy, month_n, "01", sep = "-")),
         sta5a = if_else(str_sub(div_name, start = 11, end = 11) == ")",
                         str_sub(div_name, start = 8, end = 10),
                         str_sub(div_name, start = 8, end = 12))) %>%
  select(vssc_month, sta5a, new_pc_pt_wt_create = 3)
```

```{r}
new_create_df <- new_wt_created %>%
  select(sta5a, vssc_month, new_pc_pt_wt_create) %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  filter(sta5a %in% sta5as_to_include$sta5a
         & vssc_month > ymd("2020-06-01")
         & vssc_month < ymd("2023-01-01")) %>%
  left_join(., scrssn_count) %>%
  filter(is.na(scrssn_count_cat) == F
         & scrssn_count_cat != "< 450")
#
new_pid_df <- new_wt_pid %>%
  select(sta5a, vssc_month, new_pc_pt_wt_pid) %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  filter(sta5a %in% sta5as_to_include$sta5a
         & vssc_month > ymd("2020-06-01")
         & vssc_month < ymd("2023-01-01")) %>%
  left_join(., scrssn_count) %>%
  filter(is.na(scrssn_count_cat) == F
         & scrssn_count_cat != "< 450")
```

# New Pt WT, from Patient Indicated Date  
```{r}
new_pid_df %>%
  rename(value = new_pc_pt_wt_pid) %>%
  mutate(type = "Patient Indicated") %>%
  bind_rows(new_create_df %>% mutate(type = "Create Date") %>% 
              rename(value = new_pc_pt_wt_create)) %>%
  filter(type == "Patient Indicated") %>%
  ggplot(data = .,
         aes(x = value, fill = type)) +
  geom_histogram(bins = 100,
                 alpha = 0.5,
                 color = "black",
                 position = "identity") +
  labs(x = "New Pt WT (days)",
       y = "Observations") +
  theme(legend.position = "none") +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  ggsci::scale_fill_jco()
```

# Established Pt WT, from Create Date  
```{r}
new_pid_df %>%
  rename(value = new_pc_pt_wt_pid) %>%
  mutate(type = "Patient Indicated") %>%
  bind_rows(new_create_df %>% mutate(type = "Create Date") %>% 
              rename(value = new_pc_pt_wt_create)) %>%
  filter(type != "Patient Indicated") %>%
  ggplot(data = .,
         aes(x = value, fill = type)) +
  geom_histogram(bins = 100,
                 alpha = 0.5,
                 color = "black",
                 position = "identity") +
  labs(x = "New Pt WT (days)",
       y = "Observations") +
  theme(legend.position = "none") +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  ggsci::scale_fill_igv()
```

# New Pt WT, both together    
```{r}
new_pid_df %>%
  rename(value = new_pc_pt_wt_pid) %>%
  mutate(type = "Patient Indicated") %>%
  bind_rows(new_create_df %>% mutate(type = "Create Date") %>% 
              rename(value = new_pc_pt_wt_create)) %>%
  ggplot(data = .,
         aes(x = value, fill = type)) +
  geom_histogram(bins = 100,
                 alpha = 0.5,
                 color = "black",
                 position = "identity") +
  labs(x = "New Pt WT (days)",
       y = "Observations") +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  ggsci::scale_fill_lancet()
```