---
title: "PC CRH Analysis: Interrupted Time-Series"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
pactcc_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "PACT_CC",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             legend.position = "bottom")
#===========
#source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
#
crh_flag <- dbGetQuery(oabi_con,
                       "select * from [crh_eval].C1_crh_flag") %>%
  mutate(first_mo_w_mt9_pc_crh = ymd(first_mo_w_mt9_pc_crh),
         initiated_pc_crh_b4_march_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-03-01"), TRUE, FALSE),
         initiated_pc_crh_b4_feb_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-02-01"), TRUE, FALSE)) %>%
  left_join(., vast %>% select(sta5a, s_abbr))
#
pilot_sites <- dbGetQuery(pactcc_con,
                          "select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY20_working 
                          UNION
                          select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY21_working ") %>%
  filter(vimpact_pilot == 1) %>%
  select(sta5a = spoke_sta5a)
#--
sta5as_w_gt9 <- crh_flag %>%
  filter(first_6_mos_w_10_flag == 1) %>%
  select(sta5a) %>% pull
#
ps_matched <- read_csv("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Data/ps_matched_sta5as.csv")
#
ps_groups_w_gt9 <- ps_matched %>%
  filter(at_least_10_pc_crh_flag == 1
         & sta5a %in% sta5as_w_gt9) %>%
  select(subclass) %>%
  inner_join(., ps_matched) %>%
  select(sta5a) %>%
  pull
#
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month)
#==
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  left_join(timely_care)
#
dates <- access_metrics %>%
  filter(vssc_month >= ymd("2019-04-01") & vssc_month <= ymd("2020-02-01")) %>%
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#
vline_xint <- as.numeric(ymd("2019-10-01"))
```

# Established Patient Wait Time, Over Time  

```{r}
sta5as_model_1a <- crh_flag %>%
  filter(initiated_pc_crh_b4_feb_2020 == TRUE) %>%
  select(sta5a) %>%
  inner_join(., ps_matched) %>%
  select(subclass) %>%
  inner_join(., ps_matched) %>%
  select(sta5a, at_least_10_pc_crh_flag)
#----------------------------------------------------------
```

```{r}

interrupted_ts_plot_fxn <- function(access_metric){
  access_metric_var <- ensym(access_metric)
  #
  y_axis_lab <- if (str_detect(access_metric, "est") == T){
    "Established Patient Wait Time"
  }
      else if (str_detect(access_metric, "new") == T){
        "Established Patient Wait Time"
      }
      else if (str_detect(access_metric, "third") == T){
        "Third Next Available"
      }
      else if (str_detect(access_metric, "tc_success_prop") == T){
        "Timely Care Success Rate"
      }
  #-----
model_1a <- access_metrics %>%
    select(sta5a, vssc_month, access_metric_var) %>%
    inner_join(., sta5as_model_1a) %>%
    filter(vssc_month >= ymd("2019-05-01") & vssc_month <= ymd("2020-02-01")) %>%
    mutate(crh_flag = factor(if_else(at_least_10_pc_crh_flag == 1, "PC CRH", "No PC CRH"))) %>%
    left_join(., dates) %>%
    left_join(., crh_flag %>% select(sta5a, first_6_mos_w_10_flag)) %>%
    mutate(all_first_6_months = if_else(sta5a %in% ps_groups_w_gt9, "All First 6 Months", "Not All First 6 Months"))
  #--
  p1 <- ggplot(data = model_1a,
       aes(x = vssc_month, y = !!access_metric_var, group = sta5a, color = crh_flag)) +
  geom_vline(xintercept = vline_xint,
             lty = 3) +
  scale_x_date(breaks = "2 months") +
  geom_line() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3)) +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_axis_lab)
  #-----
  p2 <- ggplot(data = model_1a,
       aes(x = vssc_month, y = !!access_metric_var, group = sta5a)) +
  geom_vline(xintercept = vline_xint,
             lty = 3) +
  scale_x_date() +
  geom_line(alpha = 0.35) +
  geom_smooth(aes(x = vssc_month, y = !!access_metric_var, group = crh_flag, lty = crh_flag),
              color = "red",
              inherit.aes = FALSE,
              se = FALSE,
              method = "lm") +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3)) +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_axis_lab) +
  facet_wrap(~all_first_6_months)
  #--
  p3 <- ggplot(data = model_1a,
       aes(x = vssc_month, y = !!access_metric_var, group = sta5a)) +
  geom_vline(xintercept = vline_xint,
             lty = 3) +
  scale_x_date(breaks = "2 months") +
  geom_line(alpha = 0.35) +
  geom_smooth(data = subset(model_1a, vssc_month > ymd("2019-09-30")),
              aes(x = vssc_month, y = !!access_metric_var, group = crh_flag, lty = crh_flag),
              color = "darkorchid3",
              inherit.aes = FALSE,
              se = FALSE,
              method = "lm",
              size = 2) +
  geom_smooth(data = subset(model_1a, vssc_month <= ymd("2019-10-01")),
              aes(x = vssc_month, y = !!access_metric_var, group = crh_flag, lty = crh_flag),
              color = "forestgreen",
              inherit.aes = FALSE,
              se = FALSE,
              method = "lm",
              size = 2) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3)) +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_axis_lab)
  #
  p4 <- ggplot(data = model_1a,
       aes(x = vssc_month, y = !!access_metric_var, group = sta5a)) +
  geom_vline(xintercept = vline_xint,
             lty = 3) +
  scale_x_date(breaks = "2 months") +
  geom_line(alpha = 0.35) +
  geom_smooth(data = subset(model_1a, vssc_month > ymd("2019-09-30")),
              aes(x = vssc_month, y = !!access_metric_var, group = crh_flag, lty = crh_flag),
              color = "darkorchid3",
              inherit.aes = FALSE,
              se = FALSE,
              method = "lm",
              size = 2) +
  geom_smooth(data = subset(model_1a, vssc_month <= ymd("2019-10-01")),
              aes(x = vssc_month, y = !!access_metric_var, group = crh_flag, lty = crh_flag),
              color = "forestgreen",
              inherit.aes = FALSE,
              se = FALSE,
              method = "lm",
              size = 2) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3)) +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_axis_lab) +
  facet_wrap(~all_first_6_months)
  #==========================
  if (str_detect(access_metric, "tc_") == T){
    print(p1 + scale_y_continuous(labels = percent_format(accuracy = 1)))
    print(p2 + scale_y_continuous(labels = percent_format(accuracy = 1)))
    print(p3 + scale_y_continuous(labels = percent_format(accuracy = 1)))
    print(p4 + scale_y_continuous(labels = percent_format(accuracy = 1)))
  }
  else {
    print(p1)
    print(p2)
    print(p3)
    print(p4)
  }
}
```

# Established Patient Wait Time  

```{r}
interrupted_ts_plot_fxn("est_pc_pt_wt")
```


# New Patient Wait Time  

```{r}
interrupted_ts_plot_fxn("new_pc_pt_wt")
```


# Third Next Available Appointment    

```{r}
interrupted_ts_plot_fxn("third_next_avail")
```


# Timely Care Success Rate    

```{r}
interrupted_ts_plot_fxn("tc_success_prop")
```