---
title: "VISN 23 - CRH Encounters Over Time"
date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = TRUE,
                      fig.width = 12, fig.height = 12)

library(tidyverse)
library(readxl)
library(ggplot2)
library(ggthemes)
library(kableExtra)
library(lubridate)
library(scales)
library(grid)
library(DT)
library(RODBC)
library(DBI)
library(janitor)
#
options(scipen = 999)
###
`%ni%` <- negate(`%in%`)
#
theme_update(
  strip.text = element_text(size = 20),
  axis.text = element_text(size = 15),
  axis.title.y = element_text(size = 18),
  axis.title.x = element_blank(),
  axis.text.x = element_text(angle = 270, hjust = 0, vjust = 0.3),
  legend.text = element_text(size = 14),
  plot.title = element_text(size = 20)
)
```

```{r reading-in}
crh_df <- read_csv("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Output/Data/analytic_df_v3_04oct21.csv") %>%
  na_if(., 0) %>%
  filter(mean_tot_crh_encounters > 1) %>%
  mutate(viz_fy = case_when(month(all_months) > 9 ~ year(all_months) + 1,
                            month(all_months) < 10 ~ year(all_months)),
         viz_qtr = case_when(month(all_months) %in% c(10, 11, 12) ~ 1,
                             month(all_months) %in% c(1, 2, 3) ~ 2,
                             month(all_months) %in% c(4, 5, 6) ~ 3,
                             month(all_months) %in% c(7, 8, 9) ~ 4)) %>%
  filter(parent_visn == 23)
#
vast <- read_csv("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Data/VAST_from_A06_11jan21.csv")
```

# Total CRH Encounters  

```{r}
visn23_crh_df <- crh_df %>%
  select(spoke_sta5a, viz_fy, viz_qtr, ends_with('_crh'), -starts_with("mean"))
#
visn23_crh_df %>%
  group_by(viz_fy, viz_qtr) %>%
  summarise('Total' = sum(encounters_crh, na.rm = T),
            'Mental Health' = sum(mental_health_crh, na.rm = T),
            'Primary Care' = sum(primary_care_crh, na.rm = T),
            'Pharmacy' = sum(pharmacy_crh, na.rm = T),
            'PCMHI' = sum(pcmhi_crh, na.rm = T),
            'Specialty' = sum(specialty_crh, na.rm = T)) %>%
  mutate(fy_qtr = str_c(viz_fy, viz_qtr, sep = "_")) %>%
  ungroup %>%
  select(-c(viz_fy, viz_qtr)) %>%
  pivot_longer(-fy_qtr) %>%
  pivot_wider(names_from = fy_qtr) %>%
  kbl(col.names = c("Care Type", "FY20, Q1", "FY20, Q2", "FY20, Q3", "FY20, Q4", "FY21, Q1", "FY21, Q2", "FY21, Q3", "FY21, Q4")) %>%
  kable_classic('striped')

```


# Mental Health Encounters  

```{r}
visn23_crh_df %>%
  group_by(spoke_sta5a, viz_fy, viz_qtr) %>%
  summarise('MH CRH Encounters' = sum(mental_health_crh, na.rm = T)) %>%
  mutate(fy_qtr = str_c(viz_fy, viz_qtr, sep = "_")) %>%
  ungroup %>%
  select(-c(viz_fy, viz_qtr)) %>%
  pivot_longer(-c(spoke_sta5a, fy_qtr)) %>%
  left_join(vast, by = c("spoke_sta5a" = "sta5a")) %>%
  mutate(label = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(label, fy_qtr, value) %>%
  pivot_wider(names_from = fy_qtr, values_from = value) %>%
  mutate(drop_flag = if_else(`2020_1` == 0 & `2020_2` == 0 & `2020_3` == 0 & `2020_4` == 0
                             & `2021_1` == 0 & `2021_2` == 0 & `2021_3` == 0, 1, 0)) %>%
  filter(drop_flag == 0) %>% select(-drop_flag) %>%
  adorn_totals() %>%
  kbl(col.names = c("Spoke Site", "FY20, Q1", "FY20, Q2", "FY20, Q3", "FY20, Q4", "FY21, Q1", "FY21, Q2", "FY21, Q3", "FY21, Q4")) %>%
  kable_classic('striped')
```

# Primary Care Encounters  

```{r}
visn23_crh_df %>%
  group_by(spoke_sta5a, viz_fy, viz_qtr) %>%
  summarise('PC CRH Encounters' = sum(primary_care_crh, na.rm = T)) %>%
  mutate(fy_qtr = str_c(viz_fy, viz_qtr, sep = "_")) %>%
  ungroup %>%
  select(-c(viz_fy, viz_qtr)) %>%
  pivot_longer(-c(spoke_sta5a, fy_qtr)) %>%
  left_join(vast, by = c("spoke_sta5a" = "sta5a")) %>%
  mutate(label = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(label, fy_qtr, value) %>%
  pivot_wider(names_from = fy_qtr, values_from = value) %>%
  mutate(drop_flag = if_else(`2020_1` == 0 & `2020_2` == 0 & `2020_3` == 0 & `2020_4` == 0
                             & `2021_1` == 0 & `2021_2` == 0 & `2021_3` == 0, 1, 0)) %>%
  filter(drop_flag == 0) %>% select(-drop_flag) %>%
  adorn_totals() %>%
  kbl(col.names = c("Spoke Site", "FY20, Q1", "FY20, Q2", "FY20, Q3", "FY20, Q4", "FY21, Q1", "FY21, Q2", "FY21, Q3", "FY21, Q4")) %>%
  kable_classic('striped')
```

# Pharmacy Encounters  

```{r}
visn23_crh_df %>%
  group_by(spoke_sta5a, viz_fy, viz_qtr) %>%
  summarise('Pharmacy CRH Encounters' = sum(pharmacy_crh, na.rm = T)) %>%
  mutate(fy_qtr = str_c(viz_fy, viz_qtr, sep = "_")) %>%
  ungroup %>%
  select(-c(viz_fy, viz_qtr)) %>%
  pivot_longer(-c(spoke_sta5a, fy_qtr)) %>%
  left_join(vast, by = c("spoke_sta5a" = "sta5a")) %>%
  mutate(label = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(label, fy_qtr, value) %>%
  pivot_wider(names_from = fy_qtr, values_from = value) %>%
  mutate(drop_flag = if_else(`2020_1` == 0 & `2020_2` == 0 & `2020_3` == 0 & `2020_4` == 0
                             & `2021_1` == 0 & `2021_2` == 0 & `2021_3` == 0, 1, 0)) %>%
  filter(drop_flag == 0) %>% select(-drop_flag) %>%
  adorn_totals() %>%
  kbl(col.names = c("Spoke Site", "FY20, Q1", "FY20, Q2", "FY20, Q3", "FY20, Q4", "FY21, Q1", "FY21, Q2", "FY21, Q3", "FY21, Q4")) %>%
  kable_classic('striped')
```


# PCMHI Encounters  

```{r}
visn23_crh_df %>%
  group_by(spoke_sta5a, viz_fy, viz_qtr) %>%
  summarise('PCMHI' = sum(pcmhi_crh, na.rm = T)) %>%
  mutate(fy_qtr = str_c(viz_fy, viz_qtr, sep = "_")) %>%
  ungroup %>%
  select(-c(viz_fy, viz_qtr)) %>%
  pivot_longer(-c(spoke_sta5a, fy_qtr)) %>%
  left_join(vast, by = c("spoke_sta5a" = "sta5a")) %>%
  mutate(label = paste0("(", spoke_sta5a, ") ", short_name)) %>%
  select(label, fy_qtr, value) %>%
  pivot_wider(names_from = fy_qtr, values_from = value) %>%
  mutate(drop_flag = if_else(`2020_1` == 0 & `2020_2` == 0 & `2020_3` == 0 & `2020_4` == 0
                             & `2021_1` == 0 & `2021_2` == 0 & `2021_3` == 0, 1, 0)) %>%
  filter(drop_flag == 0) %>% select(-drop_flag) %>%
  adorn_totals() %>%
  kbl(col.names = c("Spoke Site", "FY20, Q1", "FY20, Q2", "FY20, Q3", "FY20, Q4", "FY21, Q1", "FY21, Q2", "FY21, Q3", "FY21, Q4")) %>%
  kable_classic('striped')
```