---
title: "Time-Varying Meaningful CRH Use X Panel Fullness and Gap Metric"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
set.seed(1234)
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             plot.title = element_text(size = 24),
             legend.position = "bottom")
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#vast file for s_abbr and others
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06") %>%
  mutate(drop_flag = if_else(str_detect(short_name, "Mobile") & state != "AL", 1, 0)) %>%
  filter(drop_flag == 0) %>%
  select(-drop_flag)
#propensity score matched sta5as, as well as 
  #flags for treated/control
  #PS matching weights
  #flags for meeting inclusion criteria in 3 periods
ps_matched <- read_csv(here("Input","Post-COVID", "ps_matched_sites_post_covid.csv"))
#pulling vssc access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  mutate(tna_new_source = as.numeric(tna_new_source))
#making a time/date dataset
dates <- tibble(
  vssc_month = seq.Date(ymd("2020-10-01"), ymd("2023-09-01"), "1 month")) %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time") %>%
  mutate(fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month)),
         qtr = case_when(month(vssc_month) %in% c(10, 11, 12) ~ 1,
                         month(vssc_month) %in% c(1, 2, 3) ~ 2,
                         month(vssc_month) %in% c(4, 5, 6) ~ 3,
                         month(vssc_month) %in% c(7, 8, 9) ~ 4,
                         TRUE ~ 99))
#counting average # of unique scrssns in FY2020 by sta5a and making a categorical variable
  # that we use for exclusion
scrssn_count <- dbGetQuery(oabi_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PCS_PCAT].[econ].PatientPCP_2020_2024
                            	where fy = 2020
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy20, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy20 < 450 ~ "< 450",# exclusion criteria
    scrssn_count_avg_fy20 >= 450 & scrssn_count_avg_fy20 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy20 >= 2400 & scrssn_count_avg_fy20 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy20 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#---------------
#average age on october 1st 2022
age_sta5a_qtr <- dbGetQuery(oabi_con,
                            "select * from [OABI_MyVAAccess].[crh_eval].D1_age_sta5a_qtr")
#sta5a-fy-specific counts of gender, race, and urh, as well as total uniques
race_gender_urh <- dbGetQuery(oabi_con,
                              "select * from [OABI_MyVAAccess].[crh_eval].D2_race_gender_urh_count") %>%
  mutate(pct_male = male_count / scrssn_count * 100,
         pct_white = race_white_count / scrssn_count * 100,
         pct_rural = urh_rural_count / scrssn_count * 100)
#sta5a-fy_qtr-specific average ADI and quartile counts, as well as total
adi_sta5a_fy <- dbGetQuery(oabi_con,
                            "select * from [OABI_MyVAAccess].[crh_eval].D3_adi_sta5a_fy")
#sta5a-month-specific average Nosos, Obs:Exp, and Team PCP/AP FTE
nosos_obs_exp_team_fte <- dbGetQuery(oabi_con,
                                     "select * from [OABI_MyVAAccess].[crh_eval].F1_2_vssc_covars") %>%
  mutate(vssc_month = ymd(vssc_month))
#sta5a-fy-specific average drive distance and time to closest PC site
drive_time <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].D4_avg_drive_time")
#--
gap_metric <- dbGetQuery(oabi_con,
                         "select * from [crh_eval].H_gap_metric") %>%
  mutate(vssc_month = ymd(vssc_month))
#sta5a-month-specific timely care success rate
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month) %>%
  mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum)
#sta5a-month-specific PC CRH penetration rate and it's components
pen_rate <- dbGetQuery(oabi_con, 
                       "select *
                       from [OABI_MyVAAccess].[crh_eval].B1_crh_penRate") %>%
  rename(vssc_month = crh_month) %>%
  mutate(vssc_month = ymd(vssc_month),
         treated_month = if_else(crh_encounter_count > 9, 1, 0))#time-varying treated
```

```{r time_varying_treated}
treated_sta5a <- ps_matched %>%
  filter(treated_num == 1) %>%
  select(sta5a)
#
months_meeting_inclusion_criteria <- pen_rate %>%
  arrange(sta5a, vssc_month) %>%#ordering by station and month
  group_by(sta5a) %>%#grouping by station
  mutate(this_mo_mt9_pc_crh = if_else(crh_encounter_count > 9, 1, 0),#flag for this month meeting criteria 
         last_mo_mt9_pc_crh = if_else(lag(crh_encounter_count) > 9, 1, 0),#flag for last month
         next_mo_mt9_pc_crh = if_else(lead(crh_encounter_count) > 9, 1, 0),#flag for next month
         meets_inc_crit = if_else(this_mo_mt9_pc_crh == 1 & # IF this month meets criteria
                                    ((last_mo_mt9_pc_crh == 1 | is.na(last_mo_mt9_pc_crh)) 
                                     | (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh))),#AND either this or last month
                                  1, 0),#THEN 1, ELSE 0
         meets_inc_crit_both = meets_inc_crit,
         meets_inc_crit_fwd = if_else(this_mo_mt9_pc_crh == TRUE & (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh)), 1, 0)
         ) %>%
  filter(sta5a %in% treated_sta5a$sta5a) %>%
  right_join(., dates %>%
               select(vssc_month) %>%
               cross_join(., treated_sta5a)) %>%
  mutate(meets_inc_crit_both = replace_na(meets_inc_crit_both, 0),
         meets_inc_crit_fwd = replace_na(meets_inc_crit_fwd, 0),
         crh_enc_count_na = crh_encounter_count,
         crh_encounter_count = replace_na(crh_encounter_count, 0))
```

```{r matched_analytic_df}
#making the analytic dataset
analytic_df <- ps_matched %>%
  select(sta5a, treated, treated_num, weights, starts_with("period")) %>%
  mutate(period_flag = case_when(period1_inc == 1 ~ "Period 1",
                                 period1_inc == 0 & period2_inc == 1 ~ "Period 2",
                                 TRUE ~ "Period 3")) %>%
  cross_join(., dates) %>%
  left_join(., timely_care %>%
              select(sta5a, vssc_month, tc_pc_success_prop)) %>%
  left_join(., access_metrics %>%
              select(sta5a, vssc_month, est_pc_pt_wt_pid, new_pc_pt_wt_create, tna_new_source, new_0_20_days_create, panel_fullness)) %>%
  left_join(., adi_sta5a_fy %>%
              select(sta5a = Sta5a, fy, adi_natRnk_avg)) %>%
  left_join(., age_sta5a_qtr %>%
              select(sta5a = Sta5a, fy = FY, qtr = QTR, avg_age_oct1_2022)) %>%
  left_join(., drive_time %>%
              select(sta5a = CLOSESTPCSITE, fy, avg_driveTime) %>%
              bind_rows(., drive_time %>%
                          filter(fy == 2022) %>%
                          select(sta5a = CLOSESTPCSITE, fy, avg_driveTime) %>%
                          mutate(fy = 2023))) %>%
  left_join(., gap_metric %>%
              select(sta5a, vssc_month, gap_metric)) %>%
  left_join(., nosos_obs_exp_team_fte) %>%
  left_join(., race_gender_urh %>%
              select(sta5a = Sta5a, fy = FY, pct_male, pct_white, pct_rural)) %>%
  left_join(., vast %>%
              select(sta5a, s_abbr, parent_visn)) %>%
  left_join(., pen_rate) %>%
  left_join(., scrssn_count) %>%
  mutate(treated_num = relevel(as.factor(treated_num), ref = "0"),
         new_0_20_days_create_pct = new_0_20_days_create * 100,
         treated = relevel(as.factor(treated), ref = "Control"),
         treated_month = relevel(as.factor(replace_na(treated_month, 0)), ref = "0"),
         tc_pc_success_pct = tc_pc_success_prop * 100,
         time_t = time,
         gap_metric_cat_ord = factor(case_when(gap_metric >= 1.2 ~ "> 1.2",
                                    gap_metric < 1 ~ "< 1.0",
                                    gap_metric < 1.2 & gap_metric >= 1.0 ~ "1.0-1.2"),
                                 ordered = T,
                                 levels = c("< 1.0", "1.0-1.2", "> 1.2")),
         gap_metric_cat = factor(case_when(gap_metric >= 1.2 ~ "> 1.2",
                                    gap_metric < 1 ~ "< 1.0",
                                    gap_metric < 1.2 & gap_metric >= 1.0 ~ "1.0-1.2")),
         gap_metric_num = case_when(gap_metric >= 1.2 ~ 3,
                                    gap_metric < 1 ~ 1,
                                    gap_metric < 1.2 & gap_metric >= 1.0 ~ 2),
         new_0_20_binary_success = if_else(new_0_20_days_create_pct >= 80, 1, 0),
         panel_fullness_pct = panel_fullness * 100,
         panel_fullness_cat = factor(case_when(panel_fullness_pct < 80 ~ "<80%",
                                        panel_fullness_pct > 105 ~ ">105%",
                                        panel_fullness_pct >= 80 & panel_fullness_pct <= 105 ~ "80-105%")))
#--
analytic_panel <- analytic_df %>%
  panelr::panel_data(.,
                     id = sta5a,
                     wave = time)
```



# Gap Metric X treated_month  

```{r class.source = 'fold-show'}
analytic_df$treated_month <- relevel(analytic_df$treated_month, ref = "0")
analytic_df$gap_metric_cat <- relevel(analytic_df$gap_metric_cat, ref = "< 1.0")
```

```{r}
#
chisq_gap_df <- analytic_df %>%
  filter(is.na(gap_metric_cat) == F) %>%
  tabyl(gap_metric_cat, treated_month) %>%
  arrange(gap_metric_cat) %>%
  column_to_rownames(., "gap_metric_cat") %>%
  chisq.test()
#
chisq_gap_df$observed %>%
  as.data.frame %>%
  rownames_to_column() %>%
  mutate(rowname = factor(rowname,
                          ordered = T,
                          levels = c("< 1.0", "1.0-1.2", "> 1.2"))) %>%
  arrange(rowname)%>%
  mutate(across(where(is.numeric), ~comma(.x, accuracy = 1)))%>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      caption = "<b>Observed</b>",
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = F) %>%
  row_spec(0, bold = T)
#--
chisq_gap_df$expected %>%
  as.data.frame %>%
  rownames_to_column() %>%
  mutate(rowname = factor(rowname,
                          ordered = T,
                          levels = c("< 1.0", "1.0-1.2", "> 1.2"))) %>%
  arrange(rowname)%>%
  mutate(across(where(is.numeric), ~comma(.x, accuracy = 0.1)))%>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      caption = "<b>Expected</b>",
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = F) %>%
  row_spec(0, bold = T)
```

## Odds Ratio  
```{r}
tibble(col_1 = c("Exposed/Gap <1.0", "Not Exposed/Gap 1.0-1.2"),
       col_2 = c("2,164", "5,765"),
       col_3 = c("247", "932")) %>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      align = c("l", "r","r")) %>%
  kable_classic("striped",
                full_width = T) %>%
  row_spec(0, bold = T)
```

* If:

$$
\text{Odds Ratio}=\frac{\text{Odds of Exposure Among Cases}}{\text{Odds of Exposure Among Controls}}
$$

* Which is:

$$
\frac{(\frac{a}{c})}{(\frac{b}{d})}=\frac{a\times d}{b\times c}
$$

* Then we get:

$$
\frac{2,164\times 932}{5,765\times 247}=\frac{2,016,848}{1,423,955}=1.42
$$

```{r}
tibble(col_1 = c("Exposed/Gap <1.0", "Not Exposed/Gap >1.2"),
       col_2 = c("2,164", "12,938"),
       col_3 = c("247", "3,322")) %>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      align = c("l", "r","r")) %>%
  kable_classic("striped",
                full_width = T) %>%
  row_spec(0, bold = T)
```

* Here we get:

$$
\frac{2,164\times 3,322}{247\times 12,938}=\frac{7,188,808}{3,195,686}=2.25
$$


```{r}
mod1 <- glmer(treated_month ~ gap_metric_cat + (1|sta5a),
              data = analytic_df,
              weights = weights,
              family = binomial)
tab_model(mod1)
```



# Panel Fullness X treated_month  

```{r class.source = 'fold-show'}
analytic_df$panel_fullness_cat <- relevel(analytic_df$panel_fullness_cat, ref = ">105%")
```


```{r}
chisq_pf_df <- analytic_df %>%
  filter(is.na(panel_fullness_cat) == F) %>%
  tabyl(panel_fullness_cat, treated_month) %>%
  arrange(panel_fullness_cat) %>%
  column_to_rownames(., "panel_fullness_cat") %>%
  chisq.test()
#
chisq_pf_df$observed %>%
  as.data.frame %>%
  rownames_to_column() %>%
  mutate(rowname = factor(rowname,
                          ordered = T,
                          levels = c(">105%", "80-105%", "<80%"))) %>%
  arrange(rowname)%>%
  mutate(across(where(is.numeric), ~comma(.x, accuracy = 1)))%>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      caption = "<b>Observed</b>",
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = F) %>%
  row_spec(0, bold = T)
#--
chisq_pf_df$expected %>%
  as.data.frame %>%
  rownames_to_column() %>%
  mutate(rowname = factor(rowname,
                          ordered = T,
                          levels = c(">105%", "80-105%", "<80%"))) %>%
  arrange(rowname)%>%
  mutate(across(where(is.numeric), ~comma(.x, accuracy = 0.1)))%>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      caption = "<b>Expected</b>",
      align = c("l", "r", "r")) %>%
  kable_classic("striped",
                full_width = F) %>%
  row_spec(0, bold = T)
```

## Odds Ratio  
```{r}
tibble(col_1 = c("Exposed/PF > 105%", "Not Exposed/PF <80%"),
       col_2 = c("2,364", "5,817"),
       col_3 = c("351", "1,421")) %>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      align = c("l", "r","r")) %>%
  kable_classic("striped",
                full_width = T) %>%
  row_spec(0, bold = T)
```

* If:

$$
\text{Odds Ratio}=\frac{\text{Odds of Exposure Among Cases}}{\text{Odds of Exposure Among Controls}}
$$

* Which is:

$$
\frac{(\frac{a}{c})}{(\frac{b}{d})}=\frac{a\times d}{b\times c}
$$

* Then we get:

$$
\frac{2,364\times 1,421}{351\times 5,817}=\frac{3,359,244}{2,041,767}=1.64
$$

```{r}
tibble(col_1 = c("Exposed/PF > 105%", "Not Exposed/PF 80-105%"),
       col_2 = c("2,364", "12,769"),
       col_3 = c("351", "2,806")) %>%
  kbl(col.names = c("", "Outcome/Meaningful Use", "No Outcome/Meaningful Use"),
      align = c("l", "r","r")) %>%
  kable_classic("striped",
                full_width = T) %>%
  row_spec(0, bold = T)
```

* Here we get:

$$
\frac{2,364\times 2,806}{12,769\times 351}=\frac{6,633,384}{4,481,919}=1.48
$$


```{r}
mod2 <- glmer(treated_month ~ panel_fullness_cat + (1|sta5a),
              data = analytic_df,
              weights = weights,
              family = binomial)
tab_model(mod2)
```