---
title: "CRH Outcomes: Are we past the pandemic?"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
pactcc_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "PACT_CC",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#
every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12))
#===========
#source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r}
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
# setting flag for initiated_pc_crh_b4_feb_2020
crh_flag <- dbGetQuery(oabi_con,
                       "select * from [crh_eval].C1_crh_flag") %>%
  mutate(first_mo_w_mt9_pc_crh = ymd(first_mo_w_mt9_pc_crh),
         initiated_pc_crh_b4_march_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-03-01"), TRUE, FALSE),
         initiated_pc_crh_b4_feb_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-02-01"), TRUE, FALSE)) %>%
  left_join(., vast %>% select(sta5a, s_abbr))
#identifying sta5as that had at least 10 PC CRH encounters per month from October, 2019 through March, 2020
sta5as_w_gt9 <- crh_flag %>%
  filter(first_6_mos_w_10_flag == 1) %>%
  select(sta5a) %>% pull
# identifying sta5as that initiated PC CRH before February, 2020
crh_sta5as <- crh_flag %>%
  filter(initiated_pc_crh_b4_feb_2020 == TRUE) %>%
  select(sta5a) %>%
  pull
# identifying pilot sta5as
pilot_sites <- dbGetQuery(pactcc_con,
                          "select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY20_working 
                          UNION
                          select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY21_working ") %>%
  filter(vimpact_pilot == 1) %>%
  select(sta5a = spoke_sta5a)
# propensity score-matched sta5as
ps_matched <- read_csv("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Data/ps_matched_sta5as.csv")
# identifying ps-matched sta5as 
ps_groups_w_gt9 <- ps_matched %>%
  filter(at_least_10_pc_crh_flag == 1
         & sta5a %in% sta5as_w_gt9) %>%
  select(subclass) %>%
  inner_join(., ps_matched) %>%
  select(sta5a) %>%
  pull
# timely care success rate
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month)
#VSSC access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  left_join(timely_care)
#make dataframe of all dates and a column for time
dates <- access_metrics %>%
  filter(vssc_month <= ymd("2020-02-01")) %>%#this is where we DO NOT drop October, 2019
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#Uniques in PCMM, categorized
scrssn_count <- dbGetQuery(pactcc_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PACT_CC].[econ].PatientPCP
                            	where fy = 2019
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy19, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy19 < 450 ~ "< 450",
    scrssn_count_avg_fy19 >= 450 & scrssn_count_avg_fy19 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy19 >= 2400 & scrssn_count_avg_fy19 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy19 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#scrssn count at parent-sta5a
pcmm_parent_sta5a <- dbGetQuery(pactcc_con,
                                "with CTE as(
                                	select a.*, b.parent_station_sta5a
                                	from [PACT_CC].[econ].PatientPCP as a
                                	inner join [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06 as b
                                	on a.Sta5a = b.sta5a
                                	where fy > 2018
                                	)
                                select count(distinct ScrSSN_num) as scrssn_count, parent_station_sta5a, fy, qtr
                                from CTE
                                group by parent_station_sta5a, fy, qtr")
#==
pcmm_sta5a_qtr <- dbGetQuery(oabi_con,
                             "select count(distinct scrssn_char) as scrssn_count
                              	, sta5a, fy, qtr
                              from [PACT_CC].[econ].PatientPCP
                              where fy > 2018
                              group by sta5a, fy, qtr") %>%
  mutate(fy_qtr = str_c(fy, qtr, sep = "_")) %>%
  inner_join(., vast %>% select(sta5a)) %>%
  filter(scrssn_count > 450)
#x intercept at October, 2019
vline_xint <- as.numeric(ymd("2019-10-01"))
#####
sta5as_to_include <- scrssn_count %>% 
  filter(scrssn_count_cat != "< 450") %>%
  left_join(., vast %>% select(sta5a, parent_visn)) %>%
  filter(is.na(parent_visn) == F)
```




```{r df_fxn}
outcome_df_fxn <- function(level, variable){
  search_pattern <- if(level == "sta5a"){"sta6a"}
                    else{level}
  #
  file_paths <- list.files(path = "H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Analytic df/E2_vssc_cube_access_metrics",
                                           pattern = search_pattern,
                                           full.names = TRUE)
  #
  number_in_filePath <- if(variable == "est_pc_pt_wt"){1}
                        else if(variable == "new_pc_pt_wt"){2}
                        else if(variable == "tna"){3}
  #
  df_to_use <- 
    if(level == "sta5a"){
      read_csv(file_paths[number_in_filePath]) %>%
      rename_all(tolower) %>%
      mutate(month_n = match(str_to_title(str_sub(`fiscal date`, end = 3)), month.abb),
             fy = as.numeric(str_sub(`fiscal date`, start = -2)),
             cy2 = if_else(month_n > 9, fy - 1, fy),
             cy = as.numeric(str_c("20", cy2)),
             vssc_month = ymd(str_c(cy, month_n, "01", sep = "-"))) %>%
      select(vssc_month, sta5a = sta6a, value = 3) %>%
      inner_join(sta5as_to_include)}
  else if(level == "visn"){
      read_csv(file_paths[number_in_filePath]) %>%
      rename_all(tolower) %>%
      mutate(month_n = match(str_to_title(str_sub(`fiscal date`, end = 3)), month.abb),
             fy = as.numeric(str_sub(`fiscal date`, start = -2)),
             cy2 = if_else(month_n > 9, fy - 1, fy),
             cy = as.numeric(str_c("20", cy2)),
             vssc_month = ymd(str_c(cy, month_n, "01", sep = "-")),
             visn = str_sub(visn, start = 2)) %>%
      select(visn, vssc_month, value = 3)}
  else if(level == "facility"){
      read_csv(file_paths[number_in_filePath]) %>%
      rename_all(tolower) %>%
  mutate(month_n = match(str_to_title(str_sub(`fiscal date`, end = 3)), month.abb),
         fy = as.numeric(str_sub(`fiscal date`, start = -2)),
         cy2 = if_else(month_n > 9, fy - 1, fy),
         cy = as.numeric(str_c("20", cy2)),
         vssc_month = ymd(str_c(cy, month_n, "01", sep = "-")),
         position_11 = str_sub(facility, start = 11, end = 11),
         parent_station_sta5a = if_else(position_11 == ")",
                                        str_sub(facility, start = 8, end = 10),
                                        str_sub(facility, start = 8, end = 12)),
         parent_visn = str_sub(facility, start = 3, end = 4)) %>%
      select(parent_station_sta5a, vssc_month, value = 3, parent_visn)}
  else if(level == "national"){
      read_csv(file_paths[number_in_filePath]) %>%
      rename_all(tolower) %>%
      mutate(month_n = match(str_to_title(str_sub(`fiscal date`, end = 3)), month.abb),
             fy = as.numeric(str_sub(`fiscal date`, start = -2)),
             cy2 = if_else(month_n > 9, fy - 1, fy),
             cy = as.numeric(str_c("20", cy2)),
             vssc_month = ymd(str_c(cy, month_n, "01", sep = "-"))) %>%
      select(value = 2, vssc_month)}
}
```

```{r plot_fxn}
all_visns <- vast %>% select(parent_visn) %>% distinct %>% pull
#
color_pal <- ggsci::pal_jama("default")(4)
#
outcome_plot_fxn <- function(level, variable){
  
  y_label <-  if (variable == "tna"){"Third Next Available"}
              else if(variable == "new_pc_pt_wt"){"New Patient Wait Time"}
              else if(variable == "est_pc_pt_wt"){"Established Patient Wait Time"}
  #
  internal_df <-  outcome_df_fxn(level = level, variable = variable)
  #
  color_number <-  if (variable == "tna"){1}
              else if(variable == "new_pc_pt_wt"){2}
              else if(variable == "est_pc_pt_wt"){3}
  #
  if(level == "national"){
    ggplot(data = internal_df,
           aes(x = vssc_month, y = value, group = "a")) +
      geom_smooth(data = subset(internal_df, vssc_month < ymd("2020-03-01")),
                  method = "lm", se = FALSE) +
      geom_smooth(data = subset(internal_df, vssc_month > ymd("2021-03-01")),
                  method = "lm", se = FALSE,
                  color = "red") +
      geom_line(size = 1,
                color = color_pal[color_number]) +
      scale_y_continuous(limits = c(0, NA),
                         labels = comma_format(accuracy = 1)) +
      labs(x = "Month",
           y = y_label) +
      geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
                 lty = 2) +
      geom_vline(xintercept = as.numeric(ymd("2021-03-15")),
                 lty = 3)}
  else if(level == "visn"){
    ggplot(data = internal_df,
           aes(x = vssc_month, y = value, group = visn, color = visn)) +
      geom_smooth(data = subset(internal_df, vssc_month < ymd("2020-03-01")),
                  method = "lm", se = FALSE,
                  color = "black") +
      geom_smooth(data = subset(internal_df, vssc_month > ymd("2021-03-01")),
                  method = "lm", se = FALSE,
                  color = "red") +
      geom_line(size = 1) +
      scale_y_continuous(limits = c(0, NA),
                         labels = comma_format(accuracy = 1)) +
      labs(x = "Month",
           y = y_label) +
      geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
                 lty = 2) +
      geom_vline(xintercept = as.numeric(ymd("2021-03-15")),
                 lty = 3) +
      facet_wrap(~visn) +
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 270, vjust = 0.4))}
  else if(level == "facility"){
    internal_df <- internal_df %>% filter(parent_visn %in% all_visns[1:6])
    ggplot(data = internal_df,
           aes(x = vssc_month, y = value, group = parent_station_sta5a, color = parent_station_sta5a)) +
      geom_smooth(data = subset(internal_df, vssc_month < ymd("2020-03-01") & parent_visn %in% all_visns[1:6]),
                  method = "lm", se = FALSE,
                  color = "black") +
      geom_smooth(data = subset(internal_df, vssc_month > ymd("2021-03-01") & parent_visn %in% all_visns[1:6]),
                  method = "lm", se = FALSE,
                  color = "red") +
      geom_line(size = 1) +
      scale_y_continuous(limits = c(0, NA),
                         labels = comma_format(accuracy = 1)) +
      labs(x = "Month",
           y = y_label) +
      geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
                 lty = 2) +
      geom_vline(xintercept = as.numeric(ymd("2021-03-15")),
                 lty = 3) +
      facet_wrap(~parent_visn) +
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 270, vjust = 0.4))
    #
    ggplot(data = subset(internal_df, parent_visn %in% all_visns[7:12]),
           aes(x = vssc_month, y = value, group = parent_station_sta5a, color = parent_station_sta5a)) +
      geom_smooth(data = subset(internal_df, vssc_month < ymd("2020-03-01")),
                  method = "lm", se = FALSE,
                  color = "black") +
      geom_smooth(data = subset(internal_df, vssc_month > ymd("2021-03-01")),
                  method = "lm", se = FALSE,
                  color = "red") +
      geom_line(size = 1) +
      scale_y_continuous(limits = c(0, NA),
                         labels = comma_format(accuracy = 1)) +
      labs(x = "Month",
           y = y_label) +
      geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
                 lty = 2) +
      geom_vline(xintercept = as.numeric(ymd("2021-03-15")),
                 lty = 3) +
      facet_wrap(~parent_visn) +
      theme(legend.position = "none",
            axis.text.x = element_text(angle = 270, vjust = 0.4))}
}
```

# New Patient Wait Time  
## National  
```{r}
outcome_plot_fxn("national", "new_pc_pt_wt")
```

## By VISN  
```{r}
outcome_plot_fxn("visn", "new_pc_pt_wt")
```


# Established Patient Wait Time  
## National  
```{r}
outcome_plot_fxn("national", "est_pc_pt_wt")
```

## By VISN  
```{r}
outcome_plot_fxn("visn", "est_pc_pt_wt")
```

# Third Next Available Appointment    
## National  
```{r}
outcome_plot_fxn("national", "tna")
```

## By VISN  
```{r}
outcome_plot_fxn("visn", "tna")
```