---
title: "Access to Care appendix plots"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             legend.position = "bottom")
#===========
#source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#vast file for s_abbr and others
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
#making PC CRH criteria for this analysis
crh_flag <- dbGetQuery(oabi_con,
                       "select * from [crh_eval].C1_crh_flag") %>%
  mutate(first_mo_w_mt9_pc_crh = ymd(first_mo_w_mt9_pc_crh),
         #initiated before february to account for needing two consecutive months with > 9
         initiated_pc_crh_b4_feb_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-02-01"), TRUE, FALSE)) %>%
  left_join(., vast %>% select(sta5a, s_abbr))
#propensity score matched sta5as if being used
ps_matched <- read_csv(here("Input","Data", "ps_matched_sta5as_v5.csv"))
#pulling timely care
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month)
#pulling vssc access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  left_join(timely_care)
#making a time column
dates <- access_metrics %>%
  filter(vssc_month < ymd("2020-03-01")) %>%
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#counting average # of unique scrssns in FY2018 by sta5a and making a categorical variable
  # that we use for exclusion
scrssn_count <- dbGetQuery(oabi_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PACT_CC].[econ].PatientPCP
                            	where fy = 2018
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy18, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy18 < 450 ~ "< 450",# exclusion criteria
    scrssn_count_avg_fy18 >= 450 & scrssn_count_avg_fy18 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy18 >= 2400 & scrssn_count_avg_fy18 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy18 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#---------------
covariates <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].Z_analytic_df") %>%
  rename(sta5a = Sta6a, vssc_month = visitMonth) %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  mutate(pct_male = male_count / scrssn_count * 100,
         pct_white = race_white_count / scrssn_count * 100,
         pct_rural = urh_rural_count / scrssn_count * 100) %>%
  select(pc_crh_per_1k_total_pc, pcccr_per_10k_uniques,
         avg_age_oct1_2022, sta5a, vssc_month, 
         parent_visn, census_division,
         nosos_risk_score, obs_exp_panel_ratio, team_pcp_ap_fte_total,
         pcmm_count_fy_qtr,
         adi_natRnk_avg, pct_male, pct_white, pct_rural, avg_driveDist,
         shep_access_metric)
```

```{r}
# a vector of sta5as meeting our pc crh criteria
crh_sta5as <- crh_flag %>%
  filter(initiated_pc_crh_b4_feb_2020 == TRUE) %>%
  select(sta5a) %>%
  pull
#this is where exclusion criteria are applied:
sta5as_to_include <- ps_matched %>%
  select(subclass) %>%
  inner_join(., ps_matched) %>%
  select(sta5a, at_least_10_pc_crh_flag) %>%
  mutate(crh_flag = factor(if_else(at_least_10_pc_crh_flag == 1, "PC CRH", "No PC CRH"),
                           ordered = TRUE,
                           levels = c("PC CRH", "No PC CRH")))
#=================
#making the analytic dataset
analytic_df <- access_metrics %>%# start with access metrics
      inner_join(., sta5as_to_include) %>%#restrict to our table from above
      filter(vssc_month < ymd("2020-03-01") 
             & vssc_month > ymd("2019-04-01")) %>%#restrict to our timeframe
      left_join(., dates) %>%
      left_join(., vast %>% select(sta5a, s_abbr)) %>%
  left_join(., scrssn_count)
#-----------
penRate <- dbGetQuery(oabi_con,
                      "select * from [OABI_MyVAAccess].[crh_eval].[B1_crh_penRate]") %>%
  inner_join(., sta5as_to_include) %>%
  mutate(crh_month = ymd(crh_month)) %>%
  filter(crh_month < ymd("2020-03-01")
         & crh_month >= ymd("2019-10-01")) %>%
  left_join(., scrssn_count)
```

# Front Matter  

## Description of this report  

* This is an attempt to re-create te appendix figures from the Access to Care .pdf

# Established Patient Wait Time in Small Clinics (450 - 2,399 uniques)     
```{r}
ggplot(data = subset(analytic_df, scrssn_count_cat == "450 - 2,399"),
       aes(x = vssc_month, y = est_pc_pt_wt, group = sta5a)) +
  geom_line(alpha = 0.2) +
  geom_smooth(data = subset(analytic_df, scrssn_count_cat == "450 - 2,399"),
       aes(x = vssc_month, y = est_pc_pt_wt, group = crh_flag, lty = crh_flag), 
       method = "lm", se = F) +
  scale_x_date(date_labels = "%b-%Y") +
  labs(y = "Established Patient Wait Time (days)") +
  theme(axis.title.x = element_blank()) +
  geom_vline(xintercept = as.numeric(ymd("2019-10-01")), lty = 3)
```

# New Patient Wait Time in Medium Clinics (2,400 - 9,999 uniques)     
```{r}
ggplot(data = subset(analytic_df, scrssn_count_cat == "2,400 - 9,999"),
       aes(x = vssc_month, y = new_pc_pt_wt, group = sta5a)) +
  geom_line(alpha = 0.2) +
  geom_smooth(data = subset(analytic_df, scrssn_count_cat == "2,400 - 9,999"),
       aes(x = vssc_month, y = new_pc_pt_wt, group = crh_flag, lty = crh_flag), 
       method = "lm", se = F) +
  scale_x_date(date_labels = "%b-%Y") +
  labs(y = "New Patient Wait Time (days)") +
  theme(axis.title.x = element_blank()) +
  geom_vline(xintercept = as.numeric(ymd("2019-10-01")), lty = 3)
```

# New Patient Wait Time in Large Clinics (10,000+ uniques)     
```{r}
ggplot(data = subset(analytic_df, scrssn_count_cat == "10,000+"),
       aes(x = vssc_month, y = new_pc_pt_wt, group = sta5a)) +
  geom_line(alpha = 0.2) +
  geom_smooth(data = subset(analytic_df, scrssn_count_cat == "10,000+"),
       aes(x = vssc_month, y = new_pc_pt_wt, group = crh_flag, lty = crh_flag), 
       method = "lm", se = F) +
  scale_x_date(date_labels = "%b-%Y") +
  labs(y = "New Patient Wait Time (days)") +
  theme(axis.title.x = element_blank()) +
  geom_vline(xintercept = as.numeric(ymd("2019-10-01")), lty = 3)
```