---
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
params:
  care_type_param: "foo"
title: "`r params$care_type_param` CRH Encounters Over Time"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, echo = FALSE, fig.width = 25, fig.height = 14)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 26, face = "bold"),
             axis.text = element_text(size = 22),
             strip.text = element_text(size = 22),
             legend.text = element_text(size = 22),
             legend.title = element_text(size = 26, face = "bold"),
             plot.caption = element_text(size = 18))
#
#--
source(here("Input", "Functions", "customFacetWrap.R"))
source(here("Input", "Functions", "multiplot_05jan21.R"))
```



```{r reading-in}
hubs <- dbGetQuery(oabi_con,
                   "select distinct hub_sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY20]
                    UNION 
                    select distinct Hub_Sta3n as hub_sta5a
                    FROM [PACT_CC].[CRH].[CRH_sites_FY21_working]") %>%
  pull
#--
spokes <- dbGetQuery(oabi_con,
                     "select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy20_working
                     UNION
                     select spoke_sta5a from [PACT_CC].[CRH].CRH_sites_fy21_working")
#
spokes_v <- spokes %>% pull
#
vast <- read_csv(here("Input", "Data","VAST_from_A06_11jan21.csv"))
#
vast_spokes <- vast %>%
  inner_join(., spokes, by = c("sta5a" = "spoke_sta5a"))
#==
all_encounters <- dbGetQuery(oabi_con,
                             "select * from [OABI_MyVAAccess].[crh_eval].all_encounters_E_counts") %>%
  select(-contains("Vax")) %>%
  mutate(vizMonth = ymd(vizMonth)) %>%
  left_join(., vast, by = c("sta6a" = "sta5a")) %>%
  mutate(sta5a_lab = paste0("(", sta6a, ") ", short_name),
         spoke_flag = if_else(sta6a %in% spokes_v, TRUE, FALSE),
         fy = if_else(month(vizMonth) > 9, year(vizMonth) + 1, year(vizMonth)),
         qtr = case_when(month(vizMonth) %in% c(10, 11, 12) ~ 1,
                         month(vizMonth) %in% c(1, 2, 3) ~ 2,
                         month(vizMonth) %in% c(4, 5, 6) ~ 3,
                         month(vizMonth) %in% c(7, 8, 9) ~ 4),
         fyqtr = str_c(fy, "-", qtr)) %>%
  filter(is.na(parent_visn) == F & fy %in% c(2020, 2021)) %>%
  rename("Primary Care" = pc_encounters,
         "Mental Health" = mh_encounters,
         "Pharmacy" = pharmacy_encounters,
         "PCMHI" = pcmhi_encounters)
#
all_qtrs <- all_encounters %>% select(fyqtr) %>% distinct
#
spoke_encounters <- all_encounters %>% filter(spoke_flag == T) %>%
  rename(sta5a = sta6a)
#-----
crh_encounters <- dbGetQuery(oabi_con,
                         "select * from [PACT_CC].[CRH].[crh_full_utilization_final_fy20_21]") %>%
  rename_all(tolower) %>%
  mutate(visitdate = ymd(visitdate),
         crh_month = ymd(str_c(year(visitdate), month(visitdate), "01", sep = "-")),
         fy = if_else(month(crh_month) > 9, year(crh_month) + 1, year(crh_month)),
         qtr = case_when(month(crh_month) %in% c(10, 11, 12) ~ 1,
                         month(crh_month) %in% c(1, 2, 3) ~ 2,
                         month(crh_month) %in% c(4, 5, 6) ~ 3,
                         month(crh_month) %in% c(7, 8, 9) ~ 4),
         fyqtr = str_c(fy, "-", qtr)) %>%
  filter(fy %in% c(2020, 2021) & care_type %in% c("Primary Care", "Pharmacy", "Mental Health", "PCMHI")) %>%
  left_join(., vast, by = c("spoke_sta5a_combined_cdw" = "sta5a")) %>%
  rename(sta5a = spoke_sta5a_combined_cdw)
#--==================
access_metrics_nat <- read_csv(here("Input", "Data", "pc_access_metrics_nat_qtr.csv")) %>%
  mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum) %>%
  select(-ends_with("avg"), -ends_with("sum"), -tc_success_prop) %>%
  mutate(fy_qtr = str_replace(fy_qtr, "_", "-"))
#
access_metrics_visn <- read_csv(here("Input", "Data", "pc_access_metrics_visn_qtr.csv")) %>%
  mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum) %>%
  select(-ends_with("avg"), -ends_with("sum"), -tc_success_prop) %>%
  mutate(fy_qtr = str_replace(fy_qtr, "_", "-"))
```

```{r creating_nat_data_frames}
#--TOTAL
crh_nat_total <- crh_encounters %>%
  group_by(fyqtr) %>%
  summarise(crh_encounters = n()) %>%
  ungroup
#
all_nat_total <- spoke_encounters %>%
  select(3:6, 23) %>%
  pivot_longer(-c(fyqtr)) %>%
  group_by(fyqtr) %>%
  summarise(total = sum(value, na.rm = T)) %>%
  ungroup
#
total_nat_df <- all_qtrs %>%
  full_join(., crh_nat_total) %>%
  full_join(., all_nat_total, by = c("fyqtr" = "fyqtr")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000) %>%
  ungroup
#==BY CARE TYPE
crh_nat_type <- crh_encounters %>%
  group_by(fyqtr, care_type) %>%
  summarise(crh_encounters = n()) %>%
  ungroup
#
all_nat_type <- spoke_encounters %>%
  select(3:6, fyqtr) %>%
  pivot_longer(-c(fyqtr)) %>%
  group_by(fyqtr, name) %>%
  summarise(total = sum(value, na.rm = T)) %>%
  ungroup
#
type_nat_df <- all_qtrs %>%
  full_join(., crh_nat_type) %>%
  full_join(., all_nat_type, by = c("fyqtr" = "fyqtr", "care_type" = "name")) %>%
  mutate(crh_per_1k_total = round(crh_encounters / total * 1000, 1)) %>%
  ungroup
#
type_nat_avg <- crh_nat_type %>% 
  group_by(care_type) %>%
  summarise(avg_crh_per_qtr = mean(crh_encounters, na.rm = T))
#-------
```

```{r creating_visn_data_frames}
#--TOTAL
crh_visn_total <- crh_encounters %>%
  group_by(fyqtr, parent_visn) %>%
  summarise(crh_encounters = n()) %>%
  ungroup
#
all_visn_total <- all_qtrs %>% left_join(., spoke_encounters) %>%
  select(4:7, parent_visn, fyqtr) %>%
  pivot_longer(-c(fyqtr, parent_visn)) %>%
  group_by(fyqtr, parent_visn) %>%
  summarise(total = sum(value, na.rm = T)) %>%
  ungroup
#
total_visn_df <- all_qtrs %>%
  full_join(., crh_visn_total) %>%
  full_join(., all_visn_total, by = c("fyqtr" = "fyqtr", "parent_visn" = "parent_visn")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000) %>%
  filter(is.na(parent_visn) == F) %>%
  ungroup
#==BY CARE TYPE
crh_visn_type <- crh_encounters %>%
  group_by(fyqtr, parent_visn, care_type) %>%
  summarise(crh_encounters = n()) %>%
  ungroup
#
all_visn_type <- all_qtrs %>% left_join(., spoke_encounters) %>%
  select(4:7, parent_visn, fyqtr) %>%
  pivot_longer(-c(fyqtr, parent_visn)) %>%
  group_by(fyqtr, parent_visn, name) %>%
  summarise(total = sum(value, na.rm = T)) %>%
  ungroup
#
type_visn_df <- all_qtrs %>%
  full_join(., crh_visn_type) %>%
  full_join(., all_visn_type, by = c("fyqtr" = "fyqtr", "care_type" = "name", 
                                     "parent_visn" = "parent_visn")) %>%
  mutate(crh_per_1k_total = crh_encounters / total * 1000) %>%
  filter(is.na(parent_visn) == F) %>%
  ungroup
```

```{r functions}
crh_plot_fxn <- function(type_var, care_type_var, metric, metric_quote){
  if (metric_quote == "total"){
    y_axis <- paste0("Total ", care_type_var, " Encounters")
  }
  else if (metric_quote == "crh_encounters"){
    y_axis <- paste0(care_type_var, " CRH Encounters")
  }
  else {
    y_axis <- paste0(care_type_var, " CRH Encounters per 1,000 ", care_type_var, " Encounters")
  }
  #--
  if (type_var == "visn"){
      type_visn_df %>%
        filter(care_type == {{care_type_var}}) %>%
        select(-care_type) %>%
        mutate(parent_visn = fct_reorder2(factor(parent_visn),
                                        fyqtr, {{metric}})) %>%
        pivot_longer(-c(fyqtr, parent_visn)) %>%
        filter(name == {{metric_quote}}) %>%
        ggplot(data = .,
               aes(y = value, x = fyqtr, group = parent_visn, color = parent_visn)) +
        geom_line(size = 1.5) +
        geom_point(size = 1.5) +
        scale_y_continuous(limits = c(0, NA),
                           labels = scales::comma_format(accuracy = 1)) +
        theme(axis.text.x = element_text(angle = 270, vjust = 0.3)) +
        labs(color = "VISN",
             x = "FY-Quarter",
             y = y_axis,
             caption = "*Legend is ordered by the last datapoint") +
        guides(color = guide_legend(override.aes = list(size = 1.5)))
    }
  #--
  else if(care_type_var == "Primary Care"){
    type_nat_df %>%
      filter(care_type == {{care_type_var}}) %>%
      select(-care_type) %>%
      pivot_longer(-fyqtr) %>%
      filter(name == {{metric_quote}}) %>%
      ggplot(data = .,
             aes(y = value, x = fyqtr, group = "A")) +
      geom_line(size = 1.5, color = "forestgreen") +
      geom_point(size = 1.5, color = "forestgreen") +
      scale_y_continuous(limits = c(0, NA),
                         labels = scales::comma_format(accuracy = 1)) +
      theme(axis.text.x = element_text(angle = 270, vjust = 0.3)) +
      labs(color = "VISN",
           x = "FY-Quarter",
           y = y_axis) +
      guides(color = guide_legend(override.aes = list(size = 1.5)))
  }
  #--
  else {
    type_nat_df %>%
      filter(care_type == {{care_type_var}}) %>%
      select(-care_type) %>%
      pivot_longer(-fyqtr) %>%
      filter(name == {{metric_quote}}) %>%
      ggplot(data = .,
             aes(y = value, x = fyqtr, group = "A")) +
      geom_line(size = 1.5, color = "red") +
      geom_point(size = 1.5, color = "red") +
      scale_y_continuous(limits = c(0, NA),
                         labels = scales::comma_format(accuracy = 1)) +
      theme(axis.text.x = element_text(angle = 270, vjust = 0.3)) +
      labs(color = "VISN",
           x = "FY-Quarter",
           y = y_axis) +
      guides(color = guide_legend(override.aes = list(size = 1.5)))
  }
}
#======
crh_table_fxn <- function(type_var, care_type_var){
  if (type_var == "visn"){
  type_visn_df %>% 
    filter(care_type == care_type_var) %>%
    select(fyqtr, parent_visn, crh_encounters, total, crh_per_1k_total) %>%
    mutate(crh_encounters = format(crh_encounters, digits = 0, big.mark = ","),
           total = format(total, digits = 0, big.mark = ","),
           crh_per_1k_total = format(round(crh_per_1k_total, 1), digits = 1)) %>%
    pivot_longer(-c(fyqtr, parent_visn)) %>%
    mutate(
      name_lab = case_when(
        name == "total" ~ "Total",
        name == "crh_per_1k_total" ~ "CRH per 1,000",
        name == "crh_encounters" ~ "CRH"),
      value = if_else(str_trim(value) == "NA", NA_character_, value)
    ) %>%
    select(-name) %>%
    pivot_wider(names_from = c(name_lab, fyqtr), values_from = value) %>%
    mutate(visn_char = str_pad(parent_visn, side = "left", width = 2, pad = "0")) %>%
    arrange(visn_char) %>%
    select(-visn_char, parent_visn, contains("20-1"), contains("20-2"), contains("20-3"), contains("20-4"),
           contains("21-1"), contains("21-2"), contains("21-3"), contains("21-4")) %>%
    kbl(col.names = c("VISN", rep(c("CRH Encounters", "Total", "CRH per 1,000"), 8)),
        align = c("c", rep("r", 24))) %>%
    kable_classic("striped") %>%
    add_header_above(bold = TRUE,
                     c(" ",
                       "2020-1" = 3, "2020-2" = 3, "2020-3" = 3, "2020-4" = 3,
                       "2021-1" = 3, "2021-2" = 3, "2021-3" = 3, "2021-4" = 3)) %>%
    column_spec(c(1, 4, 7, 10, 13, 16, 19, 22, 25), border_right = TRUE)
  }
  else {
  type_nat_df %>% 
    filter(care_type == care_type_var) %>%
    select(fyqtr, crh_encounters, total, crh_per_1k_total) %>%
    mutate(crh_encounters = format(crh_encounters, digits = 0, big.mark = ","),
           total = format(total, digits = 0, big.mark = ","),
           crh_per_1k_total = format(round(crh_per_1k_total, 1), digits = 2)) %>%
    pivot_longer(-fyqtr) %>%
    mutate(
      name_lab = case_when(
        name == "total" ~ "Total",
        name == "crh_per_1k_total" ~ "CRH per 1,000",
        name == "crh_encounters" ~ "CRH"),
      value = if_else(str_trim(value) == "NA", NA_character_, value)
    ) %>%
    select(-name) %>%
    pivot_wider(names_from = c(name_lab, fyqtr), values_from = value) %>%
    select(contains("20-1"), contains("20-2"), contains("20-3"), contains("20-4"),
           contains("21-1"), contains("21-2"), contains("21-3"), contains("21-4")) %>%
    kbl(col.names = c(rep(c("CRH Encounters", "Total", "CRH per 1,000"), 8)),
        align = c(rep("r", 24))) %>%
    kable_classic("striped") %>%
    add_header_above(bold = TRUE,
                     c("2020-1" = 3, "2020-2" = 3, "2020-3" = 3, "2020-4" = 3,
                       "2021-1" = 3, "2021-2" = 3, "2021-3" = 3, "2021-4" = 3)) %>%
    column_spec(seq(3, 24, 3), border_right = TRUE)
  }
}
```

# National  
## `r params$care_type_param` CRH  
```{r}
crh_plot_fxn("nat", params$care_type_param, crh_encounters, "crh_encounters")
```

## Total `r params$care_type_param`       
```{r}
crh_plot_fxn("nat", params$care_type_param, total, "total")
```

## `r params$care_type_param` CRH per 1,000 Total `r params$care_type_param`      
```{r}
crh_plot_fxn("nat", params$care_type_param, crh_per_1k_total, "crh_per_1k_total")
```

## As a Table  
```{r}
crh_table_fxn("nat", params$care_type_param)
```

# VISN    
## `r params$care_type_param` CRH  
```{r}
crh_plot_fxn("visn", params$care_type_param, crh_encounters, "crh_encounters")
```

## Total `r params$care_type_param`       
```{r}
crh_plot_fxn("visn", params$care_type_param, total, "total")
```

## `r params$care_type_param` CRH per 1,000 Total `r params$care_type_param`      
```{r}
crh_plot_fxn("visn", params$care_type_param, crh_per_1k_total, "crh_per_1k_total")
```

## As a Table  
```{r}
crh_table_fxn("visn", params$care_type_param)
```