---
title: "Gap Metric Plots - National & VISN"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             legend.position = "right")
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#vast file for s_abbr and others
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06") %>%
  mutate(drop_flag = if_else(str_detect(short_name, "Mobile") & state != "AL", 1, 0)) %>%
  filter(drop_flag == 0) %>%
  select(-drop_flag)
#making PC CRH criteria for this analysis
# crh_flag <- dbGetQuery(oabi_con,
#                        "select * from [crh_eval].C1_crh_flag") %>%
#   left_join(., vast %>% select(sta5a, s_abbr))
#propensity score matched sta5as if being used
# ps_matched <- read_csv(here("Input","Data", "ps_matched_sta5as_v6_post_COVID.csv"))
#pulling timely care
#timely_care <- dbGetQuery(oabi_con,
  #                         "select *
  #                         from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  # mutate(viz_month = ymd(viz_month)) %>%
  # rename(sta5a = req_sta5a,
  #        vssc_month = viz_month)
#pulling vssc access metrics
# access_metrics <- dbGetQuery(oabi_con,
#                              "select * from [crh_eval].E2_VSSC_access_metrics") %>%
#   mutate(vssc_month = ymd(vssc_month)) %>%
#   left_join(timely_care)
#making a time column
dates <- tibble(
  vssc_month = seq.Date(ymd("2020-02-01"), ymd("2022-12-01"), "1 month")) %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#counting average # of unique scrssns in FY2020 by sta5a and making a categorical variable
  # that we use for exclusion
# scrssn_count <- dbGetQuery(oabi_con,
#                            "with CTE as(
#                             	select count(distinct ScrSSN_num) as scrssn_count
#                             		, sta5a, fy, qtr
#                             	from [PCS_PCAT].[econ].PatientPCP_2020_2024
#                             	where fy = 2020
#                             	group by Sta5a, fy, QTR
#                             	)
#                             select AVG(scrssn_count) as scrssn_count_avg_fy20, sta5a
#                             from CTE
#                             group by Sta5a") %>%
#   mutate(scrssn_count_cat = factor(case_when(
#     scrssn_count_avg_fy20 < 450 ~ "< 450",# exclusion criteria
#     scrssn_count_avg_fy20 >= 450 & scrssn_count_avg_fy20 < 2400 ~ "450 - 2,399",
#     scrssn_count_avg_fy20 >= 2400 & scrssn_count_avg_fy20 < 10000 ~ "2,400 - 9,999",
#     scrssn_count_avg_fy20 >= 10000 ~ "10,000+"
#   ), ordered = TRUE,
#   levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#---------------
# covariates <- dbGetQuery(oabi_con,
#                          "select * from [OABI_MyVAAccess].[crh_eval].Z_analytic_df") %>%
#   rename(sta5a = Sta6a, vssc_month = visitMonth) %>%
#   mutate(vssc_month = ymd(vssc_month)) %>%
#   mutate(pct_male = male_count / scrssn_count * 100,
#          pct_white = race_white_count / scrssn_count * 100,
#          pct_rural = urh_rural_count / scrssn_count * 100) %>%
#   select(pc_crh_per_1k_total_pc, #pcccr_per_10k_uniques,
#          avg_age_oct1_2022, sta5a, vssc_month, 
#          parent_visn, census_division,
#          nosos_risk_score, obs_exp_panel_ratio, team_pcp_ap_fte_total,
#          pcmm_count_fy_qtr,
#          adi_natRnk_avg, pct_male, pct_white, pct_rural, avg_driveDist,
#          shep_access_metric)
#--
nat_gap_metric <- read_csv(here("Input", "Data", "Gap Metric", "nat_gap_metric.csv"))
#--
visn_gap_metric <- read_csv(here("Input", "Data", "Gap Metric", "visn_gap_metric.csv"))
#--
# timely_care <- dbGetQuery(oabi_con,
#                           "select *
#                           from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
#   mutate(viz_month = ymd(viz_month)) %>%
#   rename(sta5a = req_sta5a,
#          vssc_month = viz_month) %>%
#   mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum)
# #--
# pen_rate <- dbGetQuery(oabi_con, 
#                        "select *
#                        from [OABI_MyVAAccess].[crh_eval].B1_crh_penRate") %>%
#   rename(vssc_month = crh_month) %>%
#   mutate(vssc_month = ymd(vssc_month))
```



# Front Matter  

## Description of this report  

* This report aims to develop a graphical display of the __Gap Metric__ at both the National- and VISN-levels

    
# National  

```{r}
nat_gap_metric %>%
  ggplot(data = .,
         aes(x = vssc_month, y = gap_metric)) +
  geom_line() + 
  scale_y_continuous(limits = c(1, NA),
                     breaks = c(1, 1.2, 1.5)) +
  geom_hline(yintercept = 1.2, lty = 2) +
  labs(x = "Month",
       y = "Gap Metric")
```

# VISN  

```{r}
visn_gap_metric %>%
  ggplot(data = .,
         aes(x = vssc_month, y = gap_metric, 
             group = visn,
             color = visn)) +
  geom_line() + 
  scale_y_continuous(limits = c(1, NA),
                     breaks = c(1.0, 1.2, 1.5)) +
  geom_hline(yintercept = 1.2, lty = 2) +
  labs(x = "Month",
       y = "Gap Metric")
```

```{r}
visn_gap_metric %>%
  ggplot(data = .,
         aes(x = vssc_month, y = gap_metric, 
             group = visn,
             color = visn)) +
  geom_line() + 
  scale_y_continuous(limits = c(1, NA),
                     breaks = c(1.0, 1.2, 1.5)) +
  geom_hline(yintercept = 1.2, lty = 2) +
  labs(x = "Month",
       y = "Gap Metric") +
  gghighlight::gghighlight(visn %in% c("23", "07", "10", "01", "21", "02"))
```

```{r}
library(plotly)
visn_gap_metric %>%
  mutate(gap_metric = round(gap_metric, 2)) %>%
  plot_ly(data = .,
               x = ~vssc_month,
               y = ~gap_metric,
               color = ~visn) %>%
  add_lines() %>%
  layout(showlegend = FALSE,
         xaxis = list(
           title = "Month"
         ),
         yaxis = list(
           range = c(1, 1.6),
           title = "Gap Metric"
         ))
```

## Caterpillar  
```{r}
visn_gap_metric %>%
  group_by(visn) %>%
  summarise(avg_val = mean(gap_metric),
            sd_val = sd(gap_metric)) %>%
  ggplot(data = .,
         aes(x = reorder(visn, avg_val),
             y = avg_val,
             ymin = avg_val - sd_val,
             ymax = avg_val + sd_val)) +
  geom_point(size = 2) +
  geom_errorbar(width = 0.2) +
  scale_y_continuous(limits = c(1, NA)) +
  geom_hline(yintercept = 1.2,
             lty = 2) +
  labs(x = "VISN",
       y = "Average Gap Metric +/- SD")
```