---
title: "PC CRH Analysis: Comparing OLS Regression Results"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
library(emmeans)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
pactcc_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "PACT_CC",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12))
#===========
source("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Functions/multiplot_05jan21.R")
```

```{r reading-in}
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
# setting flag for initiated_pc_crh_b4_feb_2020
crh_flag <- dbGetQuery(oabi_con,
                       "select * from [crh_eval].C1_crh_flag") %>%
  mutate(first_mo_w_mt9_pc_crh = ymd(first_mo_w_mt9_pc_crh),
         initiated_pc_crh_b4_march_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-03-01"), TRUE, FALSE),
         initiated_pc_crh_b4_feb_2020 = if_else(first_mo_w_mt9_pc_crh < ymd("2020-02-01"), TRUE, FALSE)) %>%
  left_join(., vast %>% select(sta5a, s_abbr))
#identifying sta5as that had at least 10 PC CRH encounters per month from October, 2019 through March, 2020
sta5as_w_gt9 <- crh_flag %>%
  filter(first_6_mos_w_10_flag == 1) %>%
  select(sta5a) %>% pull
# identifying sta5as that initiated PC CRH before February, 2020
crh_sta5as <- crh_flag %>%
  filter(initiated_pc_crh_b4_feb_2020 == TRUE) %>%
  select(sta5a) %>%
  pull
# identifying pilot sta5as
pilot_sites <- dbGetQuery(pactcc_con,
                          "select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY20_working 
                          UNION
                          select distinct spoke_sta5a, vimpact_pilot
                          from PACT_CC.CRH.CRH_sites_FY21_working ") %>%
  filter(vimpact_pilot == 1) %>%
  select(sta5a = spoke_sta5a)
# propensity score-matched sta5as
ps_matched <- read_csv("H:/HSRD_General/Kaboli Access Team/CRH Evaluation/Bjarni/CRH_r_project/Input/Data/ps_matched_sta5as.csv")
# identifying ps-matched sta5as 
ps_groups_w_gt9 <- ps_matched %>%
  filter(at_least_10_pc_crh_flag == 1
         & sta5a %in% sta5as_w_gt9) %>%
  select(subclass) %>%
  inner_join(., ps_matched) %>%
  select(sta5a) %>%
  pull
# timely care success rate
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month)
#VSSC access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  left_join(timely_care)
#make dataframe of all dates and a column for time
dates <- access_metrics %>%
  filter(vssc_month <= ymd("2020-02-01")) %>%
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time")
#make time2, that i'll use in regression
dates2 <- access_metrics %>%
  filter(vssc_month <= ymd("2020-02-01") & vssc_month != "2019-10-01") %>%
  select(vssc_month) %>%
  distinct %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time2")
#Uniques in PCMM, categorized
scrssn_count <- dbGetQuery(pactcc_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PACT_CC].[econ].PatientPCP
                            	where fy = 2019
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy19, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy19 < 450 ~ "< 450",
    scrssn_count_avg_fy19 >= 450 & scrssn_count_avg_fy19 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy19 >= 2400 & scrssn_count_avg_fy19 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy19 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#x intercept at October, 2019
vline_xint <- as.numeric(ymd("2019-10-01"))
```

```{r}
sta5as_to_include <- access_metrics %>%
  select(sta5a) %>%
  inner_join(., vast %>% select(sta5a, s_abbr)) %>%# must be in VAST
  distinct %>%
  mutate(crh_flag = if_else(sta5a %in% crh_sta5as, "PC CRH", "No PC CRH")) %>%# making CRH flag
  left_join(., scrssn_count) %>%
  filter(is.na(scrssn_count_cat) == F #must have uniques in PCMM
         & str_detect(s_abbr, "CBOC")# only CBOCs
           & scrssn_count_cat != "< 450")# must have > 450 uniqeus in PCMM
#number of sta5as in each category of uniques in PCMM
scrssn_cat_count <- sta5as_to_include %>%
  group_by(crh_flag, scrssn_count_cat) %>%
  summarise(count = n()) %>%
  mutate(count = as.character(count)) %>%
  pivot_wider(names_from = scrssn_count_cat, values_from = count)
#=================
model_1 <- access_metrics %>%
      inner_join(., sta5as_to_include) %>%
      inner_join(., dates %>% filter(vssc_month != "2019-10-01")) %>% #dropping october
      left_join(., dates2) %>%#adding time2 for regression
      left_join(., crh_flag %>% select(sta5a, first_6_mos_w_10_flag)) %>%
      mutate(all_first_6_months = if_else(sta5a %in% ps_groups_w_gt9, 
                                          "All First 6 Months", "Not All First 6 Months"),
             tna_drop = if_else(third_next_avail > 100, TRUE, FALSE),
             post_crh_implementation = if_else(vssc_month >= "2019-10-01", "Post-Imp", "Pre-Imp")) %>%
  filter(tna_drop == FALSE)
#=================
model_2 <- access_metrics %>%
      inner_join(., sta5as_to_include) %>%
      inner_join(., dates) %>%
      left_join(., crh_flag %>% select(sta5a, first_6_mos_w_10_flag)) %>%
      mutate(all_first_6_months = if_else(sta5a %in% ps_groups_w_gt9, 
                                          "All First 6 Months", "Not All First 6 Months"),
             tna_drop = if_else(third_next_avail > 100, TRUE, FALSE),
             post_crh_implementation = if_else(vssc_month >= "2019-10-01", "Post-Imp", "Pre-Imp")) %>%
  filter(tna_drop == FALSE)
```

```{r, functions}
plot_fxn <- function(uniques_group, metric){
  #
  model_noOct <- if(uniques_group %in% c("450 - 2,399", "2,400 - 9,999", "10,000+"))
                    {model_1 %>% 
                        filter(scrssn_count_cat == !!uniques_group) %>%
                        select(time, sta5a, crh_flag, contains(metric)) %>%
                        pivot_longer(-c(sta5a, crh_flag, time))}
                      
                  else{model_1 %>%
                        select(time, sta5a, crh_flag, contains(metric)) %>%
                        pivot_longer(-c(sta5a, crh_flag, time))}
                    #
  model_yesOct <- if(uniques_group %in% c("450 - 2,399", "2,400 - 9,999", "10,000+")){
                      model_2 %>% 
                        filter(scrssn_count_cat == !!uniques_group) %>%
                        select(time, sta5a, crh_flag, contains(metric)) %>%
                        pivot_longer(-c(sta5a, crh_flag, time))}
                      else{model_2 %>%
                          select(time, sta5a, crh_flag, contains(metric)) %>%
                          pivot_longer(-c(sta5a, crh_flag, time))}
  #=---
  y_lab <- if(metric == "est_pc_pt_wt"){"Established Patient Wait Time (days)"}
    else{"New Patient Wait Time (days)"}
  #----
  p_noOct <- ggplot(data = model_noOct,
                    aes(x = time, y = value, group = sta5a)) +
    geom_line(alpha = 0.35) +
    geom_smooth(aes(x = time, y = value, group = crh_flag, lty = crh_flag),
                color = "red",
                inherit.aes = FALSE,
                se = TRUE,
                method = "lm") +
    ggsci::scale_color_d3() +
    guides(color = guide_legend(override.aes = list(size = 2))) +
    labs(y = y_lab,
         x = "Time",
         title = "No October, 2019") +
    coord_cartesian(xlim = c(1, 14)) +
    scale_x_continuous(breaks = seq(1, 14, 1)) +
    scale_y_continuous(limits = c(0, NA)) +
    theme(legend.position = "bottom")
  
  p_yesOct <- ggplot(data = model_yesOct,
                     aes(x = time, y = value, group = sta5a)) +
    geom_line(alpha = 0.35) +
    geom_smooth(aes(x = time, y = value, group = crh_flag, lty = crh_flag),
                color = "blue",
                inherit.aes = FALSE,
                se = TRUE,
                method = "lm") +
    ggsci::scale_color_d3() +
    guides(color = guide_legend(override.aes = list(size = 2))) +
    labs(y = y_lab,
         x = "Time",
         title = "Including October, 2019") +
    coord_cartesian(xlim = c(1, 14)) +
    scale_x_continuous(breaks = seq(1, 14, 1)) +
    scale_y_continuous(limits = c(0, NA)) +
    theme(legend.position = "bottom")
  #
  multiplot(p_noOct, p_yesOct, cols = 2)
}
#=========
regression_fxn <- function(uniques_group, metric){
  #
  model_noOct <- if(uniques_group %in% c("450 - 2,399", "2,400 - 9,999", "10,000+"))
  {model_1 %>% 
      filter(scrssn_count_cat == !!uniques_group) %>%
      select(time, time2, sta5a, crh_flag, contains(metric)) %>%
      pivot_longer(-c(sta5a, crh_flag, time, time2))}
  
  else{model_1 %>%
      select(time, time2, sta5a, crh_flag, contains(metric)) %>%
      pivot_longer(-c(sta5a, crh_flag, time, time2))}
  #
  model_yesOct <- if(uniques_group %in% c("450 - 2,399", "2,400 - 9,999", "10,000+")){
    model_2 %>% 
      filter(scrssn_count_cat == !!uniques_group) %>%
      select(time, sta5a, crh_flag, contains(metric)) %>%
      pivot_longer(-c(sta5a, crh_flag, time))}
  else{model_2 %>%
      select(time, sta5a, crh_flag, contains(metric)) %>%
      pivot_longer(-c(sta5a, crh_flag, time))}
  #----
  #
  lm_noOct <- model_noOct %>% select(-time) %>% rename(time = time2) %>%
    lm(value ~ time + crh_flag, data = .)
  #
  lm_yesOct <- model_yesOct %>% lm(value ~ time + crh_flag, data = .)
  #
  tab_model(lm_noOct, lm_yesOct,
            pred.labels = c("Intercept", "Time", "PC CRH (vs. No PC CRH)"),
            dv.labels = c("No October", "Including October"),
            show.se = TRUE)
}
```


# Established Patient Wait Time    
## All PCMM Categories  

```{r}
plot_fxn("", "est_pc_pt_wt")
```

```{r}
regression_fxn("", "est_pc_pt_wt")
```

### Including Categorical Uniques Covariate    

```{r}
lm_noOct <- model_1 %>% select(-time) %>% rename(time = time2) %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(est_pc_pt_wt ~ time + crh_flag + scrssn_count_cat, data = .)
#
lm_yesOct <- model_2 %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(est_pc_pt_wt ~ time + crh_flag + scrssn_count_cat, data = .)
#
tab_model(lm_noOct, lm_yesOct,
          pred.labels = c("Intercept", "Time", "PC CRH (vs. No PC CRH)",
                          "2,400 - 9,999 Uniques", "10,000+ Uniques"),
          dv.labels = c("No October", "Including October"),
          show.se = TRUE)
```

### PC CRH Alone  

```{r}

lm_noOct_crh <- model_1 %>% 
  select(-time) %>% 
  rename(time = time2) %>%
  filter(crh_flag == "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(est_pc_pt_wt ~ time, data = .)
#
lm_yesOct_crh <- model_2 %>%
  filter(crh_flag == "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(est_pc_pt_wt ~ time, data = .)
#
tab_model(lm_noOct_crh, lm_yesOct_crh,
          pred.labels = c("Intercept", "Time"),
          dv.labels = c("PC CRH\nNo October", "PC CRH\nIncluding October"),
          show.se = TRUE)

```

### No PC CRH Alone  

```{r}

lm_noOct_noCrh <- model_1 %>% 
  select(-time) %>% 
  rename(time = time2) %>%
  filter(crh_flag != "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(est_pc_pt_wt ~ time, data = .)
#
lm_yesOct_noCrh <- model_2 %>%
  filter(crh_flag != "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(est_pc_pt_wt ~ time, data = .)
#
tab_model(lm_noOct_noCrh, lm_yesOct_noCrh,
          pred.labels = c("Intercept", "Time"),
          dv.labels = c("No PC CRH\nNo October", "No PC CRH\nIncluding October"),
          show.se = TRUE)

```

## 450 - 2,399 Uniques    

```{r}
plot_fxn("450 - 2,399", "est_pc_pt_wt")
```

```{r}
regression_fxn("450 - 2,399", "est_pc_pt_wt")
```

## 2,400 - 9,999 Uniques    

```{r}
plot_fxn("2,400 - 9,999", "est_pc_pt_wt")
```

```{r}
regression_fxn("2,400 - 9,999", "est_pc_pt_wt")
```


## 10,000+ Uniques    

```{r}
plot_fxn("10,000+", "est_pc_pt_wt")
```

```{r}
regression_fxn("10,000+", "est_pc_pt_wt")
```



# New Patient Wait Time  
## Setting Max(Wait-Time) to 75  
```{r}
model_noOct <- model_1 %>%
    select(time, sta5a, crh_flag, new_pc_pt_wt) %>%
    pivot_longer(-c(sta5a, crh_flag, time))
#
model_yesOct <- model_2 %>%
    select(time, sta5a, crh_flag, new_pc_pt_wt) %>%
    pivot_longer(-c(sta5a, crh_flag, time))
#=---
y_lab <- "New Patient Wait Time (days)"
#----
p_noOct <- ggplot(data = model_noOct,
                  aes(x = time, y = value, group = sta5a)) +
  geom_line(alpha = 0.35) +
  geom_smooth(aes(x = time, y = value, group = crh_flag, lty = crh_flag),
              color = "red",
              inherit.aes = FALSE,
              se = TRUE,
              method = "lm") +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_lab,
       x = "Time",
       title = "No October, 2019") +
  coord_cartesian(xlim = c(1, 14)) +
  scale_x_continuous(breaks = seq(1, 14, 1)) +
  scale_y_continuous(limits = c(0, 75)) +
  theme(legend.position = "bottom")

p_yesOct <- ggplot(data = model_yesOct,
                   aes(x = time, y = value, group = sta5a)) +
  geom_line(alpha = 0.35) +
  geom_smooth(aes(x = time, y = value, group = crh_flag, lty = crh_flag),
              color = "blue",
              inherit.aes = FALSE,
              se = TRUE,
              method = "lm") +
  ggsci::scale_color_d3() +
  guides(color = guide_legend(override.aes = list(size = 2))) +
  labs(y = y_lab,
       x = "Time",
       title = "Including October, 2019") +
  coord_cartesian(xlim = c(1, 14)) +
  scale_x_continuous(breaks = seq(1, 14, 1)) +
  scale_y_continuous(limits = c(0, 75)) +
  theme(legend.position = "bottom")
#
multiplot(p_noOct, p_yesOct, cols = 2)
```

## All PCMM Categories  

```{r}
plot_fxn("", "new_pc_pt_wt")
```

```{r}
regression_fxn("", "new_pc_pt_wt")
```

### Including Categorical Uniques Covariate    

```{r}
lm_noOct <- model_1 %>% select(-time) %>% rename(time = time2) %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(new_pc_pt_wt ~ time + crh_flag + scrssn_count_cat, data = .)
#
lm_yesOct <- model_2 %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(new_pc_pt_wt ~ time + crh_flag + scrssn_count_cat, data = .)
#
tab_model(lm_noOct, lm_yesOct,
          pred.labels = c("Intercept", "Time", "PC CRH (vs. No PC CRH)",
                          "2,400 - 9,999 Uniques", "10,000+ Uniques"),
          dv.labels = c("No October", "Including October"),
          show.se = TRUE)
```

### PC CRH Alone  

```{r}

lm_noOct_crh <- model_1 %>% 
  select(-time) %>% 
  rename(time = time2) %>%
  filter(crh_flag == "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(new_pc_pt_wt ~ time, data = .)
#
lm_yesOct_crh <- model_2 %>%
  filter(crh_flag == "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(new_pc_pt_wt ~ time, data = .)
#
tab_model(lm_noOct_crh, lm_yesOct_crh,
          pred.labels = c("Intercept", "Time"),
          dv.labels = c("PC CRH\nNo October", "PC CRH\nIncluding October"),
          show.se = TRUE)

```

### No PC CRH Alone  

```{r}

lm_noOct_noCrh <- model_1 %>% 
  select(-time) %>% 
  rename(time = time2) %>%
  filter(crh_flag != "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>%
  lm(new_pc_pt_wt ~ time, data = .)
#
lm_yesOct_noCrh <- model_2 %>%
  filter(crh_flag != "PC CRH") %>%
  mutate(scrssn_count_cat = factor(scrssn_count_cat, ordered = FALSE)) %>% 
  lm(new_pc_pt_wt ~ time, data = .)
#
tab_model(lm_noOct_noCrh, lm_yesOct_noCrh,
          pred.labels = c("Intercept", "Time"),
          dv.labels = c("No PC CRH\nNo October", "No PC CRH\nIncluding October"),
          show.se = TRUE)

```

## 450 - 2,399 Uniques    

```{r}
plot_fxn("450 - 2,399", "new_pc_pt_wt")
```

```{r}
regression_fxn("450 - 2,399", "new_pc_pt_wt")
```

## 2,400 - 9,999 Uniques    

```{r}
plot_fxn("2,400 - 9,999", "new_pc_pt_wt")
```

```{r}
regression_fxn("2,400 - 9,999", "new_pc_pt_wt")
```


## 10,000+ Uniques    

```{r}
plot_fxn("10,000+", "new_pc_pt_wt")
```

```{r}
regression_fxn("10,000+", "new_pc_pt_wt")
```