---
title: "Post-COVID PC CRH Tables"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
set.seed(1234)
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             plot.title = element_text(size = 24),
             legend.position = "bottom")
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
#vast file for s_abbr and others
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06") %>%
  mutate(drop_flag = if_else(str_detect(short_name, "Mobile") & state != "AL", 1, 0),
         s_abbr2 = case_when(str_detect(s_abbr, "CBOC") ~ "CBOC",
                             str_detect(s_abbr, "VAMC|HCC") ~ "VAMC/HCC",
                             s_abbr == "OOS" ~ "OOS")) %>%
  filter(drop_flag == 0) %>%
  select(-drop_flag)
#propensity score matched sta5as, as well as 
  #flags for treated/control
  #PS matching weights
  #flags for meeting inclusion criteria in 3 periods
ps_matched <- read_csv(here("Input","Post-COVID", "ps_matched_sites_post_covid.csv")) %>%
  rename(treated_ever = treated_num)
#pulling vssc access metrics
access_metrics <- dbGetQuery(oabi_con,
                             "select * from [crh_eval].E2_VSSC_access_metrics") %>%
  mutate(vssc_month = ymd(vssc_month)) %>%
  mutate(tna_new_source = as.numeric(tna_new_source))
#making a time/date dataset
dates <- tibble(
  vssc_month = seq.Date(ymd("2019-10-01"), ymd("2023-09-01"), "1 month")) %>%
  arrange(vssc_month) %>%
  rowid_to_column(., var = "time") %>%
  mutate(fy = if_else(month(vssc_month) > 9, year(vssc_month) + 1, year(vssc_month)),
         qtr = case_when(month(vssc_month) %in% c(10, 11, 12) ~ 1,
                         month(vssc_month) %in% c(1, 2, 3) ~ 2,
                         month(vssc_month) %in% c(4, 5, 6) ~ 3,
                         month(vssc_month) %in% c(7, 8, 9) ~ 4,
                         TRUE ~ 99))
#counting average # of unique scrssns in FY2020 by sta5a and making a categorical variable
  # that we use for exclusion
scrssn_count <- dbGetQuery(oabi_con,
                           "with CTE as(
                            	select count(distinct ScrSSN_num) as scrssn_count
                            		, sta5a, fy, qtr
                            	from [PCS_PCAT].[econ].PatientPCP_2020_2024
                            	where fy = 2020
                            	group by Sta5a, fy, QTR
                            	)
                            select AVG(scrssn_count) as scrssn_count_avg_fy20, sta5a
                            from CTE
                            group by Sta5a") %>%
  mutate(scrssn_count_cat = factor(case_when(
    scrssn_count_avg_fy20 < 450 ~ "< 450",# exclusion criteria
    scrssn_count_avg_fy20 >= 450 & scrssn_count_avg_fy20 < 2400 ~ "450 - 2,399",
    scrssn_count_avg_fy20 >= 2400 & scrssn_count_avg_fy20 < 10000 ~ "2,400 - 9,999",
    scrssn_count_avg_fy20 >= 10000 ~ "10,000+"
  ), ordered = TRUE,
  levels = c("< 450", "450 - 2,399", "2,400 - 9,999", "10,000+")))
#---------------
#average age on october 1st 2022
age_sta5a_qtr <- dbGetQuery(oabi_con,
                            "select * from [OABI_MyVAAccess].[crh_eval].D1_age_sta5a_qtr")
#sta5a-fy-specific counts of gender, race, and urh, as well as total uniques
race_gender_urh <- dbGetQuery(oabi_con,
                              "select * from [OABI_MyVAAccess].[crh_eval].D2_race_gender_urh_count") %>%
  mutate(pct_male = male_count / scrssn_count * 100,
         pct_white = race_white_count / scrssn_count * 100,
         pct_rural = urh_rural_count / scrssn_count * 100)
#sta5a-fy_qtr-specific average ADI and quartile counts, as well as total
adi_sta5a_fy <- dbGetQuery(oabi_con,
                            "select * from [OABI_MyVAAccess].[crh_eval].D3_adi_sta5a_fy")
#sta5a-month-specific average Nosos, Obs:Exp, and Team PCP/AP FTE
nosos_obs_exp_team_fte <- dbGetQuery(oabi_con,
                                     "select * from [OABI_MyVAAccess].[crh_eval].F1_2_vssc_covars") %>%
  mutate(vssc_month = ymd(vssc_month))
#sta5a-fy-specific average drive distance and time to closest PC site
drive_time <- dbGetQuery(oabi_con,
                         "select * from [OABI_MyVAAccess].[crh_eval].D4_avg_drive_time")
#--
#--
sta5as_to_start <- vast %>%
  left_join(., scrssn_count %>%
              select(sta5a, scrssn_count_cat)) %>%
  filter(s_abbr %in% c("PCCBOC", "MSCBOC", "HCC", "OOS", "VAMC")
         & scrssn_count_cat != "< 450") %>%
  select(sta5a)
#
gap_metric <- dbGetQuery(oabi_con,
                         "select * from [crh_eval].H_gap_metric") %>%
  mutate(vssc_month = ymd(vssc_month),
         gap_capped = if_else(gap_metric > 3, 3, gap_metric),
         gap2_capped = if_else(gap_metric2 > 3, 3, gap_metric2),
         gap_cat = factor(case_when(gap_metric < 1.0 ~ "< 1.0",
                                    gap_metric >= 1.0 & gap_metric <= 1.2 ~ "1.0 - 1.2",
                                    gap_metric > 1.2 ~ "> 1.2",
                                     TRUE ~ "Missing"),
                          ordered = TRUE,
                          levels = c("< 1.0", "1.0 - 1.2", "> 1.2", "Missing")),
         gap_cat2 = factor(case_when(gap_metric2 < 1.0 ~ "< 1.0",
                                     gap_metric2 >= 1.0 & gap_metric2 <= 1.2 ~ "1.0 - 1.2",
                                     gap_metric2 > 1.2 ~ "> 1.2",
                                     TRUE ~ "Missing"),
                           ordered = TRUE,
                           levels = c("< 1.0", "1.0 - 1.2", "> 1.2", "Missing"))) %>%
  inner_join(., sta5as_to_start %>%
               cross_join(., dates %>%
                            select(vssc_month)),
             by = c("sta5a", "vssc_month"))
#sta5a-month-specific timely care success rate
timely_care <- dbGetQuery(oabi_con,
                          "select *
                          from [OABI_MyVAAccess].[crh_eval].[E3_daysDV_month_sta5a]") %>%
  mutate(viz_month = ymd(viz_month)) %>%
  rename(sta5a = req_sta5a,
         vssc_month = viz_month) %>%
  mutate(tc_pc_success_prop = tc_pc_success_sum / tc_requests_sum)
#sta5a-month-specific PC CRH penetration rate and it's components
pen_rate <- dbGetQuery(oabi_con, 
                       "select *
                       from [OABI_MyVAAccess].[crh_eval].B1_crh_penRate") %>%
  rename(vssc_month = crh_month) %>%
  mutate(vssc_month = ymd(vssc_month),
         treated_month = if_else(crh_encounter_count > 9, 1, 0))#time-varying treated
#
crh_fte <- read_csv(here::here("Input", "Data", "VSSC", "CRH FTE", "sta5a_month_crh_fte.csv")) %>%  
  mutate(month_c = str_to_title(str_sub(`Fiscal Date`, end = 3)),
         month_n = match(month_c, month.abb),
         fy = as.numeric(str_c("20", str_sub(`Fiscal Date`, start = -2))),
         cy = if_else(month_n > 9, fy - 1, fy),
         vssc_month = ymd(str_c(cy, month_n, "01", sep = "-"))) %>%
  select(sta5a = Sta6a, vssc_month, crh_pcp_ap_fte = 4) %>%
  mutate(crh_pcp_ap_fte = replace_na(crh_pcp_ap_fte, 0))
```

```{r time_varying_treated}
treated_sta5a <- ps_matched %>%
  filter(treated_ever == 1) %>%
  select(sta5a)
#
months_meeting_inclusion_criteria <- pen_rate %>%
  arrange(sta5a, vssc_month) %>%#ordering by station and month
  group_by(sta5a) %>%#grouping by station
  mutate(this_mo_mt9_pc_crh = if_else(crh_encounter_count > 9, 1, 0),#flag for this month meeting criteria 
         last_mo_mt9_pc_crh = if_else(lag(crh_encounter_count) > 9, 1, 0),#flag for last month
         next_mo_mt9_pc_crh = if_else(lead(crh_encounter_count) > 9, 1, 0),#flag for next month
         meets_inc_crit = if_else(this_mo_mt9_pc_crh == 1 & # IF this month meets criteria
                                    ((last_mo_mt9_pc_crh == 1 | is.na(last_mo_mt9_pc_crh)) 
                                     | (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh))),#AND either this or last month
                                  1, 0),#THEN 1, ELSE 0
         meets_inc_crit_both = meets_inc_crit,
         meets_inc_crit_fwd = if_else(this_mo_mt9_pc_crh == TRUE & (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh)), 1, 0)
         ) %>%
  filter(sta5a %in% treated_sta5a$sta5a) %>%
  right_join(., dates %>%
               select(vssc_month) %>%
               cross_join(., treated_sta5a)) %>%
  mutate(meets_inc_crit_both = replace_na(meets_inc_crit_both, 0),
         meets_inc_crit_fwd = replace_na(meets_inc_crit_fwd, 0),
         crh_enc_count_na = crh_encounter_count,
         crh_encounter_count = replace_na(crh_encounter_count, 0))
```




```{r unmatched_analytic_df}
treated_after_sep2020 <- pen_rate %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  arrange(sta5a, vssc_month) %>%#ordering by station and month
  group_by(sta5a) %>%#grouping by station
  mutate(this_mo_mt9_pc_crh = if_else(crh_encounter_count > 9, 1, 0),#flag for this month meeting criteria 
         last_mo_mt9_pc_crh = if_else(lag(crh_encounter_count) > 9, 1, 0),#flag for last month
         next_mo_mt9_pc_crh = if_else(lead(crh_encounter_count) > 9, 1, 0),#flag for next month
         meets_inc_crit = if_else(this_mo_mt9_pc_crh == 1 & # IF this month meets criteria
                                    ((last_mo_mt9_pc_crh == 1 | is.na(last_mo_mt9_pc_crh)) 
                                     | (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh))),#AND either this or last month
                                  1, 0),#THEN 1, ELSE 0
         meets_inc_crit_both = meets_inc_crit,
         meets_inc_crit_fwd = if_else(this_mo_mt9_pc_crh == TRUE & (next_mo_mt9_pc_crh == 1 | is.na(next_mo_mt9_pc_crh)), 1, 0)
  ) %>%
  filter(meets_inc_crit == 1) %>%
  select(sta5a) %>%
  distinct
#--
analytic_df2 <- vast %>%
  filter(str_detect(s_abbr, "CBOC|VAMC|HCC|OOS") == T) %>%
  select(sta5a) %>%
  inner_join(., scrssn_count %>%
               filter(is.na(scrssn_count_cat) == F
                      & scrssn_count_cat != "< 450") %>%
               select(sta5a)) %>%
  mutate(treated_ever = if_else(sta5a %in% treated_after_sep2020$sta5a, 1, 0)) %>%
  cross_join(., dates) %>%
  left_join(., timely_care %>%
              select(sta5a, vssc_month, tc_pc_success_prop)) %>%
  left_join(., access_metrics %>%
              select(sta5a, vssc_month, est_pc_pt_wt_pid, new_pc_pt_wt_create, tna_new_source, new_0_20_days_create, panel_fullness)) %>%
  left_join(., adi_sta5a_fy %>%
              select(sta5a = Sta5a, fy, adi_natRnk_avg)) %>%
  left_join(., age_sta5a_qtr %>%
              select(sta5a = Sta5a, fy = FY, qtr = QTR, avg_age_oct1_2022)) %>%
  left_join(., drive_time %>%
              select(sta5a = CLOSESTPCSITE, fy, avg_driveTime) %>%
              bind_rows(., drive_time %>%
                          filter(fy == 2022) %>%
                          select(sta5a = CLOSESTPCSITE, fy, avg_driveTime) %>%
                          mutate(fy = 2023))) %>%
  left_join(., gap_metric %>%
              select(sta5a, vssc_month, gap_metric = gap_metric2)) %>%
  left_join(., nosos_obs_exp_team_fte) %>%
  left_join(., race_gender_urh %>%
              select(sta5a = Sta5a, fy = FY, pct_male, pct_white, pct_rural)) %>%
  left_join(., vast %>%
              select(sta5a, s_abbr, s_abbr2, parent_visn)) %>%
  left_join(., pen_rate) %>%
  left_join(., scrssn_count) %>%
  left_join(., crh_fte) %>%
  mutate(treated_ever = relevel(as.factor(treated_ever), ref = "0"),
         new_0_20_days_create_pct = new_0_20_days_create * 100,
         #treated = relevel(as.factor(treated), ref = "Control"),
         treated_month = relevel(as.factor(replace_na(treated_month, 0)), ref = "0"),
         treated_month2 = if_else(treated_month == "0", 0, 1),
         tc_pc_success_pct = tc_pc_success_prop * 100,
         time_t = time,
         gap_metric_cat = factor(case_when(gap_metric >= 1.2 ~ "> 1.2",
                                    gap_metric < 1 ~ "< 1.0",
                                    gap_metric < 1.2 & gap_metric >= 1.0 ~ "1.0-1.2",
                                    TRUE ~ "Missing"),
                                 ordered = TRUE,
                                 levels = c("< 1.0", "1.0-1.2", "> 1.2", "Missing")),
         gap_metric_num = case_when(gap_metric >= 1.2 ~ 3,
                                    gap_metric < 1 ~ 1,
                                    gap_metric < 1.2 & gap_metric >= 1.0 ~ 2),
         new_0_20_binary_success = if_else(new_0_20_days_create_pct >= 80, 1, 0),
         panel_fullness_pct = panel_fullness * 100,
         panel_fullness_cat = factor(case_when(panel_fullness_pct < 80 ~ "<80%",
                                        panel_fullness_pct > 105 ~ ">105%",
                                        panel_fullness_pct >= 80 & panel_fullness_pct <= 105 ~ "80-105%")),
         gap_lt_1 = if_else(gap_metric_cat == "< 1.0", 1, 0),
         gap_1_12 = if_else(gap_metric_cat == "1.0-1.2", 1, 0),
         gap_gt_12 = if_else(gap_metric_cat == "> 1.2", 1, 0),
         scrssn_450_2399 = if_else(scrssn_count_cat == "450 - 2,399", 1, 0),
         scrssn_2400_9999 = if_else(scrssn_count_cat == "2,400 - 9,999", 1, 0),
         scrssn_ge_10k = if_else(scrssn_count_cat == "10,000+", 1, 0),
         crh_corr_fte = if_else(is.na(crh_pcp_ap_fte), team_pcp_ap_fte_total,
                                team_pcp_ap_fte_total - crh_pcp_ap_fte)) %>%
  fastDummies::dummy_cols(., select_columns = c("parent_visn", "s_abbr")) %>%
  arrange(sta5a, vssc_month) %>%
  group_by(sta5a) %>%
  fill(avg_age_oct1_2022,
       .direction = "downup") %>% ungroup
```

```{r}

row_fxn = function(variable_char, variable, variable_name, timeperiod){
  t.test_fmla = as.formula(paste0({{variable_char}}, " ~ treated_ever"))
  #
  analytic_df = if({{timeperiod}} == "3 months"){
    analytic_df2 %>%
      filter(vssc_month > ymd("2020-06-01")
             & vssc_month < ymd("2020-10-01"))
  }
  else if({{timeperiod}} == "1 year"){
    analytic_df2 %>%
      filter(vssc_month > ymd("2019-09-01")
             & vssc_month < ymd("2020-10-01"))}
  else{analytic_df2 %>%
      filter(vssc_month > ymd("2020-09-01"))}
  #
  sd_trtd = analytic_df %>%
    filter(treated_ever == "1") %>%
    summarise(val = comma(sd({{variable}}, na.rm = T), accuracy = 0.001)) %>%
    pull
  #
  sd_ctrl = analytic_df %>%
    filter(treated_ever == "0") %>%
    summarise(val = comma(sd({{variable}}, na.rm = T), accuracy = 0.001)) %>%
    pull
  #
  t.test_df = t.test(t.test_fmla, data = analytic_df)
  tibble(variable_name = {{variable_name}},
         mean_trtd = comma(t.test_df$estimate[2], accuracy = 0.001),
         sd_trtd = sd_trtd,
         mean_ctrl = comma(t.test_df$estimate[1], accuracy = 0.001),
         sd_ctrl = sd_ctrl,
         p_val = if_else(t.test_df$p.value < 0.001, "< 0.001", 
                         comma(t.test_df$p.value, accuracy = 0.001)),
         start_month = min(analytic_df$vssc_month),
         end_month = max(analytic_df$vssc_month))
}
```

# Site Type  
```{r}
site_type = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  select(sta5a, treated_ever, s_abbr2) %>%
  distinct %>%
  tabyl(s_abbr2, treated_ever) %>%
  chisq.test()
#--
site_type$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Site Type", "CRH User", "Control"),
      row.names = FALSE) %>%
  kable_classic("striped",
                full_width = F)
#
site_type
```

# Uniques  

```{r}
uniques = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  select(sta5a, treated_ever, scrssn_count_cat) %>%
  mutate(scrssn_count_cat = droplevels(scrssn_count_cat)) %>%
  distinct %>%
  tabyl(scrssn_count_cat, treated_ever) %>%
  chisq.test()
#--
uniques$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Uniques", "CRH User", "Control"),
      row.names = FALSE) %>%
  kable_classic("striped",
                full_width = F)
#
uniques
```

# Gap Metric    
## Average Gap - Categorical    

```{r}
gap_avg = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  filter(is.na(gap_metric) == F) %>% 
  group_by(sta5a, treated_ever) %>%
  summarise(mean_gap = mean(gap_metric, na.rm = T)) %>%
  mutate(gap_metric_cat = droplevels(factor(case_when(mean_gap >= 1.2 ~ "> 1.2",
                                    mean_gap < 1 ~ "< 1.0",
                                    mean_gap < 1.2 & mean_gap >= 1.0 ~ "1.0-1.2"))))
#
gap_df = gap_avg %>%
  select(sta5a, treated_ever, gap_metric_cat) %>%
  distinct %>%
  tabyl(gap_metric_cat, treated_ever) %>%
  chisq.test()
#--
gap_df$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Gap Metric", "CRH User", "Control"),
      row.names = FALSE) %>%
  kable_classic("striped",
                full_width = F)
#
gap_df
```



## Average Gap - Continuous  

```{r}
row_fxn("gap_metric", gap_metric, "Gap Metric", "foo")
```

## Number of Months  

```{r}
gap_month = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  filter(gap_metric_cat != "Missing") %>%
  mutate(gap_metric_cat = droplevels(gap_metric_cat)) %>%
  tibble() %>%
  select(sta5a, treated_ever, gap_metric_cat) %>%
  tabyl(gap_metric_cat, treated_ever) %>%
  chisq.test()
#--
gap_month$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Gap Metric", "CRH User", "Control"),
      row.names = FALSE) %>%
  kable_classic("striped",
                full_width = F)
#
gap_month
```

## Number of Months With Missing    

```{r}
gap_month = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  select(sta5a, treated_ever, gap_metric_cat) %>%
  tabyl(gap_metric_cat, treated_ever) %>%
  chisq.test()
#--
gap_month$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Gap Metric", "CRH User", "Control"),
      row.names = FALSE) %>%
  kable_classic("striped",
                full_width = F)
#
gap_month
```

# Panel Fullness  
## Continuous  

```{r}
row_fxn("panel_fullness", panel_fullness, "Panel Fullness", "3 months")
```

## Categorical  

```{r}
pf_cat = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  filter(is.na(panel_fullness_cat) == F) %>%
  select(sta5a, treated_ever, panel_fullness_cat) %>%
  tabyl(panel_fullness_cat, treated_ever) %>%
  chisq.test()
#--
pf_cat$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Panel Fullness", "CRH User", "Control")) %>%
  kable_classic("striped",
                full_width = F)
#
pf_cat
```

# CRH-Corrected PC FTE  

```{r}
row_fxn("crh_corr_fte", crh_corr_fte, "CRH-Corrected FTE", "3 months")
```

## Total PC FTE  

```{r}
row_fxn("team_pcp_ap_fte_total", team_pcp_ap_fte_total, "Total FTE", "3 months")
```

# Number of Meaningful Use Months  

```{r}
mfUse_df = analytic_df2 %>%
  filter(vssc_month > ymd("2020-09-01")) %>%
  mutate(treated_ever = factor(treated_ever,
                               ordered = TRUE,
                               levels = c("1", "0"))) %>%
  filter(is.na(treated_month) == F) %>%
  select(sta5a, treated_ever, treated_month) %>%
  tabyl(treated_month, treated_ever) %>%
  chisq.test()
#--
mfUse_df$observed %>%
  adorn_percentages("col") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns("front") %>%
  kbl(col.names = c("Meaningful Use Months", "CRH User", "Control")) %>%
  kable_classic("striped",
                full_width = F)
#
mfUse_df
#
row_fxn("treated_month2", treated_month2, "Treated Month", "foo")
```



# Patient Mix  

```{r}

#
row_fxn("adi_natRnk_avg", adi_natRnk_avg, "ADI", "3 months") %>%
  bind_rows(., 
            row_fxn("avg_age_oct1_2022", avg_age_oct1_2022, "Age", "3 months"),
            row_fxn("nosos_risk_score", nosos_risk_score, "Nosos", "3 months"),
            row_fxn("pct_male", pct_male, "Male", "3 months"),
            row_fxn("pct_white", pct_white, "White", "3 months"),
            row_fxn("pct_rural", pct_rural, "Rural", "3 months")) %>%
  kbl(col.names = c("Variable", "Mean Treated", "SD Treated", "Mean Control",
                    "SD Control", "p-value", "start month", "end month"),
      align = c("l", rep("r", 7)),
      full_width = FALSE) %>%
  kable_classic("striped")
```

# Outcomes  

```{r}
row_fxn("est_pc_pt_wt_pid", est_pc_pt_wt_pid, "EPWT", "1 year") %>%
  bind_rows(., 
            row_fxn("new_pc_pt_wt_create", new_pc_pt_wt_create, "NPWT", "1 year"), 
            row_fxn("tna_new_source", tna_new_source, "TNA", "1 year"), 
            row_fxn("tc_pc_success_pct", tc_pc_success_pct, "Timely Care", "1 year"), 
            row_fxn("new_0_20_binary_success", new_0_20_binary_success, 
                            "80% of New Seen < 20", "1 year")) %>%
  kbl(col.names = c("Outcome", "Mean Treated", "SD Treated", "Mean Control",
                    "SD Control", "p-value", "start month", "end month"),
      align = c("l", rep("r", 7)),
      full_width = FALSE) %>%
  kable_classic("striped")
```