---
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    toc_float: true
    toc: true
    toc_depth: 3
params:
  sta5a_param: "foo"
  sta5a_name_param: "bar"
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
knitr::knit_hooks$set(inline = function(x){
  prettyNum(x, big.mark = ",")
})
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(DT)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(jsonlite)
library(httr)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
pactCC_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "PACT_CC",
                      Trusted_Connection = "true")
#
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12))
#===========
source(here("input", "Functions", "multiplot_05jan21.R"))
```



```{r query_va_location_api, echo = FALSE}
#--
headers = c(
  `apikey` = 'IXCQi6rtiZFA4tMhDOWpHqJf6oeA1Cg1'
)
#
sta5a_for_pull <- params$sta5a_param
url_for_pull = paste0("https://sandbox-api.va.gov/services/va_facilities/v0/facilities/vha_", sta5a_for_pull)
#--
apiResults <- fromJSON(content(GET(url = url_for_pull,
                                   add_headers(.headers=headers)), 
                               "text"),
                       flatten = TRUE)
```

---
title: "(`r str_remove(apiResults$data$id, "vha_")`) `r apiResults$data$attributes$name`"
---


```{r, echo = FALSE}
vast <- dbGetQuery(oabi_con,
                   "select * from [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06")
#--==
# vssc_covariates <- dbGetQuery(oabi_con,
#                              "select *
#                              from [crh_eval].F1_2_vssc_covars") %>%
#   mutate(vssc_month = ymd(vssc_month)) %>%
#   filter(vssc_month >= ymd("2019-10-01") & vssc_month <= ymd("2021-12-01"))
#--===
penRate <- dbGetQuery(oabi_con,
                      "select pr.*
                    	, crh_flag = case
                    		when c1.crh_10_flag = 1 then 1
                    		else 0 end
                      from [OABI_MyVAAccess].[crh_eval].B1_crh_penRate as pr
                      left join [OABI_MyVAAccess].[crh_eval].C1_crh_flag as c1
	                    on pr.sta5a = c1.sta5a") %>%
  inner_join(., vast) %>%
  mutate(crh_month = ymd(crh_month),
         fy = if_else(month(crh_month) > 9, year(crh_month) + 1, year(crh_month)),
         qtr = case_when(
           month(crh_month) %in% c(10, 11, 12) ~ 1,
           month(crh_month) %in% c(1, 2, 3) ~ 2,
           month(crh_month) %in% c(4, 5, 6) ~ 3,
           month(crh_month) %in% c(7, 8, 9) ~ 4),
         fy_qtr = str_c(fy, qtr, sep = "-"),
         short_name = gsub(",.*", "", short_name),
         sta5a_lab = paste0("(", sta5a, ") ", short_name))
#---
age <- dbGetQuery(oabi_con,
                  "select * from [crh_eval].D1_age_sta5a_qtr")
#
race_gender_urh <- dbGetQuery(oabi_con,
                              "select * from [crh_eval].D2_race_gender_urh_count")
#
adi <- dbGetQuery(oabi_con,
                  "select * from [crh_eval].D3_adi_sta5a_qtr")
#---
pcmm_count <- dbGetQuery(pactCC_con,
                         "select count(distinct ScrSSN_char) as pcmm_scrssn_count, Sta5a
from [PACT_CC].[econ].PatientPCP
where fy = 2020 AND qtr = 1
group by sta5a") %>%
  mutate(pcmm_scrssn_count = comma(pcmm_scrssn_count, accuracy = 1))
# #---
# team_fte <- read_csv(here("Input", "Measures of Staffing", "pcp_ap_fte_by_teamType_sta6a_month.csv")) %>%
#   rename(sta5a = sta6a) %>%
#   rename_all(tolower) %>%
#   mutate(month_c = str_to_sentence(str_sub(date, end = 3)),
#          month_n = match(month_c, month.abb),
#          cy = case_when(
#            month_n < 10 ~ as.numeric(str_c("20", str_sub(date, start = -2))),
#            TRUE ~ as.numeric(str_c("20", str_sub(date, start = -2))) - 1
#          ),
#          fte_month = ymd(str_c(cy, month_n, "01", sep = "-"))) %>%
#   select(sta5a, fte_month, team, team_pcp_ap_fte_total) %>%
#   filter(fte_month >= ymd("2019-10-01") & fte_month <= ymd("2021-12-01"))
#===============
gap_metric <- read_csv("//vhacdwdwhapp15.vha.med.va.gov/PACT_CC/CRH/Documentation/Gap Metric/GapData_Jan2022.csv") %>%
  rename_all(tolower) %>%
  mutate(moyear = ymd(moyear)) %>%
  filter(moyear >= ymd("2019-10-01") & moyear <= ymd("2021-12-01")) %>%
  inner_join(., vast, by = c("sta6a" = "sta5a")) %>%
  mutate(sta5a_lab = paste0("(", sta6a, ") ", short_name))
```


```{r phrases}
location_phrase <- paste0("Located in ", apiResults$data$attributes$address$physical$city, ", ",
                          apiResults$data$attributes$address$physical$state)
#--
hours <- apiResults$data$attributes$hours %>% unlist()
days_phrase <- case_when(
  sum(hours[1:7] == "24/7") == 7 ~ "7 days per week",
  sum(hours[6:7] == "Closed") == 2 & sum(hours[1:5] == "Closed") == 0 ~ "M-F",
  sum(hours[1:4] == "800AM-430PM") == 3 & hours[3] == "800AM-630PM" ~ "",
  sum(hours[5:7] == "Closed") == 3 & sum(hours[1:4] == "Closed") == 0 ~ "M-Th",
  TRUE ~ "How do this?"
)
#
open_phrase <- case_when(
  sum(hours[1:7] == "24/7") == 7 ~ "24 hours",
  sum(hours[1:5] == "700AM-530PM") == 5 ~ "7:00-5:30",
  sum(hours[1:5] == "700AM-330PM") == 5 ~ "7:00-3:30",
  sum(hours[1:5] == "730AM-400PM") == 5 ~ "7:30-4:00",
  sum(hours[1:5] == "730AM-430PM") == 5 ~ "7:30-4:30",
  sum(hours[1:5] == "800AM-430PM") == 5 ~ "8:00-4:30",
  sum(hours[1:5] == "800AM-400PM") == 5 ~ "8:00-4:00",
  sum(hours[1:4] == "800AM-430PM") == 5 ~ "8:00-4:30",
  sum(hours[1:4] == "800AM-430PM") == 3 & hours[3] == "800AM-630PM" ~ "8:00-4:30 M, Tu, Th, 8:00-6:30 We",
  TRUE ~ "This too?"
)
#--
hours_phrase <- paste0(open_phrase, ", ", days_phrase)
#
classification_phrase <- case_when(
  str_detect(apiResults$data$attributes$classification, "OOS") == T ~ 
    paste0("They are classified as an ", apiResults$data$attributes$classification, " site"),
  TRUE ~ paste0("They are classified as a ", apiResults$data$attributes$classification, " site")
)
```

# (`r str_remove(apiResults$data$id, "vha_")`) `r apiResults$data$attributes$name`   
* [`r location_phrase`](`r apiResults$data$attributes$website`)
* They are open `r hours_phrase`
* `r classification_phrase`


## Demographics  
```{r}
#
adi_for_table <- adi %>% 
  filter(Sta5a == params$sta5a_param & fy == 2020 & qtr == 1) %>%
  mutate(label = "ADI Average (SD)",
         measure = paste0(round(adi_natRnk_avg, 1), " (", round(adi_natRnk_sd, 1), ")")) %>%
  select(label, measure)
#
age_for_table <- age %>%
  filter(Sta5a == params$sta5a_param & FY == 2020 & QTR == 1) %>%
  mutate(label = "Average Age (SD)",
         measure = paste0(round(avg_age_oct1_2020, 1), " (", round(std_age_oct1_2020, 1), ")")) %>%
  select(label, measure)
#
male_for_table <- race_gender_urh %>%
  filter(Sta5a == params$sta5a_param & FY == 2020 & QTR == 1) %>%
  mutate(label = "Male",
         measure = percent(male_count / scrssn_count, accuracy = 0.1)) %>%
  select(label, measure)
#
white_for_table <- race_gender_urh %>%
  filter(Sta5a == params$sta5a_param & FY == 2020 & QTR == 1) %>%
  mutate(label = "White",
         measure = percent(race_white_count / scrssn_count, accuracy = 0.1)) %>%
  select(label, measure)
#
rural_for_table <- race_gender_urh %>%
  filter(Sta5a == params$sta5a_param & FY == 2020 & QTR == 1) %>%
  mutate(label = "Rural",
         measure = percent(urh_rural_count / scrssn_count, accuracy = 0.1)) %>%
  select(label, measure)
#
pcmm_for_table <- pcmm_count %>%
  filter(Sta5a == params$sta5a_param) %>%
  mutate(label = "Uniques in PCMM") %>%
  select(label, measure = pcmm_scrssn_count)
#--
age_for_table %>%
  rbind(., adi_for_table) %>%
  rbind(., male_for_table) %>%
  rbind(., white_for_table) %>%
  rbind(., rural_for_table) %>%
  rbind(., pcmm_for_table) %>%
  kbl(col.names = c("Demographic", "Measure"),
      align = c("l", "r")) %>%
  kable_classic("striped",
                full_width = FALSE,
                position = "left") %>%
  row_spec(0, bold = TRUE)
```

## PC CRH Penetration  

```{r}
pr1 <- penRate %>%
  filter(sta5a == params$sta5a_param) %>%
  group_by(crh_month, sta5a_lab) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "PC Not CRH" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-c(crh_month, sta5a_lab)) %>%
  ggplot(data = .,
         aes(x = crh_month, y = value, group = name, fill = name)) +
  geom_bar(position = "stack", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = comma_format(accuracy = 1)) +
  scale_x_date(breaks = "2 months", date_labels = "%b-%Y") +
  labs(y = "Count",
       x = "Month") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        axis.title.x = element_blank(),
        legend.position = "bottom") +
  geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
             lty = 2)
#
pr2 <- penRate %>%
  filter(sta5a == params$sta5a_param) %>%
  group_by(crh_month, sta5a_lab) %>%
  summarise("PC CRH" = sum(crh_encounter_count, na.rm = T),
            "PC Not CRH" = sum(pc_encounter_total, na.rm = T)) %>%
  pivot_longer(-c(crh_month, sta5a_lab)) %>%
  ggplot(data = .,
         aes(x = crh_month, y = value, group = name, fill = name)) +
  geom_bar(position = "fill", stat = "identity") +
  ggsci::scale_fill_aaas() +
  scale_y_continuous(labels = percent_format(accuracy = 1)) +
  scale_x_date(breaks = "2 months", date_labels = "%b-%Y") +
  labs(y = "Proportion",
       x = "Month") +
  theme(axis.text.x = element_text(angle = 270, vjust = 0.3),
        legend.title = element_blank(),
        legend.position = "bottom") +
  geom_vline(xintercept = as.numeric(ymd("2020-03-15")),
             lty = 2)
#
multiplot(pr1, pr2, cols = 2)
```

## PC Staffing Gap Metric  

```{r}
gap_subset <- gap_metric %>%
  filter(sta6a == params$sta5a_param
  ) %>%
  select(sta5a_lab, moyear, gap) %>%
  pivot_longer(-c(moyear, sta5a_lab))
#
ymax_val <- (round(max(gap_subset$value) / 0.5) * 0.5)
#
gap_subset %>%
  ggplot(data = .,
         aes(x = moyear, y = value, color = name)) +
  scale_y_continuous(limits = c(0.5, ymax_val), 
                     breaks = seq(0.5, ymax_val, 0.5)) +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 270, vjust = 0.3)) +
  scale_x_date(breaks = "2 months", date_labels = "%b-%Y") +
  labs(y = "Gap Metric") +
  geom_rect(aes(xmin = ymd("2019-10-01"),
                xmax = ymd("2021-12-01"),
                ymin = 0.5,
                ymax = 1.0),
            fill = "red", 
            alpha = 0.02,
            color = NA) +
  geom_rect(aes(xmin = ymd("2019-10-01"),
                xmax = ymd("2021-12-01"),
                ymin = 1.0,
                ymax = 1.2),
            fill = "gold", 
            alpha = 0.02, 
            color = NA) +
  geom_rect(aes(xmin = ymd("2019-10-01"),
                xmax = ymd("2021-12-01"),
                ymin = 1.2,
                ymax = ymax_val),
            fill = "forestgreen", 
            alpha = 0.02,
            color = NA) +
  geom_line(size = 1,
            color = "black")
```


