---
title: "PC & MH CRH Encounters by FY-VISN"
date: "`r Sys.Date()`"
author: "Bjarni Haraldsson"
output: 
  html_document:
    code_folding: hide
    toc_float: true
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, cache = FALSE, fig.width = 10, fig.height = 10)
#
# knitr::knit_hooks$set(inline = function(x){
#   prettyNum(x, big.mark = ",")
# })
#
options(scipen = 999, knitr.kable.NA = ' ')
#
library(tidyverse)
library(lubridate)
library(gt)
library(kableExtra)
library(readxl)
library(DBI)
library(here)
library(scales)
library(janitor)
library(MatchIt)
library(lme4)
library(sjPlot)
#
##---------- Connection to SQL13
oabi_con <- dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "vhacdwsql13.vha.med.va.gov",
                      Database = "OABI_MyVAAccess",
                      Trusted_Connection = "true")
#
`%ni%` <- negate(`%in%`)
#---------
theme_update(axis.title = element_text(size = 20),
             axis.text = element_text(size = 16),
             strip.text = element_text(size = 14),
             legend.text = element_text(size = 18),
             legend.title = element_blank(),
             plot.caption = element_text(size = 12),
             legend.position = "bottom")
#===========
#source(here("input", "Functions", "multiplot_05jan21.R"))
```

```{r reading-in}
crh_encounters <- dbGetQuery(oabi_con,
                             "select count(*) as crh_encounter_count
                            	, spoke_visn_crh
                            	, fy
                            	, care_type
                            from [PACT_CC].[CRH].C_crh_utilization_final
                            group by spoke_visn_crh
                            	, fy
                            	, care_type") %>%
  filter(care_type %in% c("Primary Care", "Mental Health"))
#--
pc_uniques <- dbGetQuery(oabi_con,
                         "select count(distinct a.scrssn_char) as scrssn_count
	, b.parent_visn
	, a.FY
from [PACT_CC].[econ].PatientPCP as a
left join [OABI_MyVAAccess].[crh_eval].C2_vast_from_a06 as b
	on a.Sta5a = b.sta5a
where fy > 2019 and b.parent_visn IS NOT NULL
group by b.parent_visn
	, a.FY")
#--
table_df <- crh_encounters %>%
  left_join(., pc_uniques, by = c("spoke_visn_crh" = "parent_visn", "fy" = "FY")) %>%
  mutate(crh_encounters_per_1k_pc_uniques = crh_encounter_count / scrssn_count * 1000)
```

# Primary Care  
```{r}
table_df %>% filter(care_type == "Primary Care") %>%
  mutate(value = paste0(comma(crh_encounter_count),
                        " (",
                        comma(crh_encounters_per_1k_pc_uniques, accuracy = 0.1),
                        ")")) %>%
  select(spoke_visn_crh, fy, value) %>%
  pivot_wider(names_from = "fy", values_from = "value") %>%
  arrange(spoke_visn_crh) %>%
  select(1, 6, 3, 2) %>%
  kbl(col.names = c("VISN", "CRH Encounters (per 1k PC Uniques)", 
                    "CRH Encounters (per 1k PC Uniques)", 
                    "CRH Encounters (per 1k PC Uniques)"),
      align = c("c", "r", "r", "r")) %>%
  kable_classic("striped") %>%
  add_header_above(c("", "2020", "2021", "2022"),
                   bold = T)
```

# Mental Health  
```{r}
table_df %>% filter(care_type == "Mental Health") %>%
  mutate(value = paste0(comma(crh_encounter_count),
                        " (",
                        comma(crh_encounters_per_1k_pc_uniques, accuracy = 0.1),
                        ")")) %>%
  select(spoke_visn_crh, fy, value) %>%
  pivot_wider(names_from = "fy", values_from = "value") %>%
  arrange(spoke_visn_crh) %>%
  select(1, 3, 2, 4) %>%
  kbl(col.names = c("VISN", "CRH Encounters (per 1k PC Uniques)", 
                    "CRH Encounters (per 1k PC Uniques)", 
                    "CRH Encounters (per 1k PC Uniques)"),
      align = c("c", "r", "r", "r")) %>%
  kable_classic("striped") %>%
  add_header_above(c("", "2020", "2021", "2022"),
                   bold = T)
```